export const analytics = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto space-y-6",
  statGrid:     "grid grid-cols-2 lg:grid-cols-4 gap-4",
  statCard:     "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  statValue:    "text-3xl font-black text-gray-900",
  statLabel:    "text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  statTrend:    "text-xs font-semibold text-green-600 mt-1.5 flex items-center gap-1",
  statTrendDown:"text-xs font-semibold text-red-500 mt-1.5 flex items-center gap-1",
  chartCard:    "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  chartHead:    "flex items-center justify-between mb-5",
  chartTitle:   "font-bold text-gray-900 text-sm",
  chartFilter:  "flex items-center gap-1",
  chartTab:     "px-2.5 py-1 rounded-lg text-xs font-semibold text-gray-500 hover:bg-gray-100 transition-colors",
  chartTabActive:"px-2.5 py-1 rounded-lg text-xs font-semibold bg-blue-600 text-white",
  chartWrap:    "h-64 w-full",
  grid2:        "grid grid-cols-1 lg:grid-cols-2 gap-5",
  tableCard:    "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  tableHead:    "px-5 py-4 border-b border-gray-100 flex items-center justify-between",
  tableTitle:   "font-bold text-gray-900 text-sm",
  rankRow:      "flex items-center gap-3 px-5 py-3 border-b border-gray-50 last:border-0",
  rankNum:      "w-6 text-xs font-black text-gray-300",
  rankLabel:    "flex-1 text-sm font-semibold text-gray-900",
  rankValue:    "text-sm font-black text-blue-600",
  rankBar:      "h-1.5 rounded-full bg-blue-100 mt-1",
  rankBarFill:  "h-1.5 rounded-full bg-blue-600",
} as const;
