export const boats = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  topbar:       "flex items-center justify-between mb-5 gap-4 flex-wrap",
  title:        "text-xl font-black text-gray-900",
  grid:         "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4",
  card:         "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  cardImg:      "relative w-full aspect-video bg-gray-100",
  cardBody:     "p-4",
  cardType:     "text-[10px] font-black text-blue-600 uppercase tracking-widest",
  cardTitle:    "font-bold text-gray-900 text-sm leading-snug mt-0.5",
  cardPrice:    "text-blue-600 font-black text-base mt-2",
  cardSpec:     "flex items-center gap-3 mt-2 flex-wrap",
  specItem:     "flex items-center gap-1 text-[11px] text-gray-500",
  cardMeta:     "flex items-center justify-between mt-3 pt-3 border-t border-gray-50",
  cardActions:  "flex items-center gap-1",
  statusActive: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusSold:   "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
  typeFor:      "inline-flex items-center px-2 py-0.5 rounded-full bg-cyan-100 text-cyan-700 text-[10px] font-bold",
} as const;
