export const dash = {
  root:         "min-h-screen bg-gray-50/60",
  inner:        "max-w-7xl mx-auto px-4 py-6 space-y-6",
  topbar:       "flex items-center justify-between mb-6 gap-4",
  title:        "text-2xl font-black text-gray-900",
  subtitle:     "text-sm text-gray-400 mt-0.5",
  statGrid:     "grid grid-cols-2 lg:grid-cols-4 gap-4",
  statCard:     "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  statValue:    "text-3xl font-black text-gray-900",
  statLabel:    "text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  statTrend:    "text-xs font-semibold text-green-600 mt-1.5",
  statTrendDown:"text-xs font-semibold text-red-500 mt-1.5",
  grid2:        "grid grid-cols-1 lg:grid-cols-2 gap-5",
  grid3:        "grid grid-cols-1 lg:grid-cols-3 gap-5",
  card:         "bg-white rounded-2xl border border-gray-200 shadow-sm",
  cardHead:     "px-5 py-4 border-b border-gray-100 flex items-center justify-between",
  cardTitle:    "font-bold text-gray-900 text-base",
  cardBody:     "p-5",
  table:        "w-full",
  thead:        "border-b border-gray-100 bg-gray-50",
  th:           "text-left text-[10px] font-black text-gray-400 uppercase tracking-widest px-5 py-3",
  tr:           "border-b border-gray-50 last:border-0 hover:bg-gray-50 transition-colors",
  td:           "px-5 py-3.5 text-sm text-gray-700",
  tdMuted:      "px-5 py-3.5 text-sm text-gray-400",
  actions:      "flex items-center gap-1",
  actionEdit:   "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-blue-50 text-gray-400 hover:text-blue-600 transition-colors",
  actionDel:    "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-600 transition-colors",
  pagination:   "flex items-center justify-between px-5 py-3.5 border-t border-gray-100",
  pageInfo:     "text-xs text-gray-400",
  pageNav:      "flex items-center gap-1",
  pageBtn:      "w-8 h-8 rounded-lg text-xs font-semibold text-gray-600 hover:bg-gray-100 transition-colors inline-flex items-center justify-center",
  pageBtnActive:"w-8 h-8 rounded-lg text-xs font-semibold bg-blue-600 text-white inline-flex items-center justify-center",
  emptyState:   "flex flex-col items-center justify-center py-16 text-center",
  emptyIcon:    "w-14 h-14 rounded-2xl bg-gray-100 flex items-center justify-center mb-4 text-gray-400 text-2xl",
  emptyText:    "font-bold text-gray-700 text-base",
  emptySubtext: "text-sm text-gray-400 mt-1",
  pill:         "px-3 py-1 rounded-lg bg-gray-100 text-gray-600 text-xs font-semibold",
  pillActive:   "px-3 py-1 rounded-lg bg-blue-600 text-white text-xs font-semibold",
} as const;
