export const jobs = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  topbar:       "flex items-center justify-between mb-5 gap-4 flex-wrap",
  title:        "text-xl font-black text-gray-900",
  list:         "space-y-3",
  card:         "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  cardHead:     "flex items-start justify-between gap-3",
  cardTitle:    "font-bold text-gray-900 text-sm leading-snug",
  cardCompany:  "text-xs text-gray-400 mt-0.5",
  cardBody:     "mt-3",
  cardDesc:     "text-sm text-gray-500 leading-relaxed line-clamp-2",
  cardFoot:     "flex items-center gap-3 mt-4 flex-wrap",
  cardActions:  "flex items-center gap-1",
  typeFull:     "inline-flex items-center px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-[10px] font-bold",
  typePart:     "inline-flex items-center px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-[10px] font-bold",
  typeFreelance:"inline-flex items-center px-2 py-0.5 rounded-full bg-orange-100 text-orange-700 text-[10px] font-bold",
  typeRemote:   "inline-flex items-center px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 text-[10px] font-bold",
  statusOpen:   "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusClosed: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
  locationPill: "flex items-center gap-1 text-[11px] text-gray-500",
  salaryPill:   "flex items-center gap-1 text-[11px] text-blue-600 font-semibold",
  appCount:     "text-[11px] text-gray-400 font-semibold",
} as const;
