export const marketplace = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  topbar:       "flex items-center justify-between mb-5 gap-4 flex-wrap",
  title:        "text-xl font-black text-gray-900",
  grid:         "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4",
  card:         "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  cardImg:      "relative w-full aspect-[4/3] bg-gray-100",
  cardBody:     "p-4",
  cardTitle:    "font-bold text-gray-900 text-sm leading-snug line-clamp-2",
  cardPrice:    "text-blue-600 font-black text-base mt-1",
  cardSeller:   "text-xs text-gray-400 mt-1",
  cardMeta:     "flex items-center justify-between mt-3 pt-3 border-t border-gray-50",
  cardActions:  "flex items-center gap-1",
  statusActive: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusPending:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
  statusSold:   "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
  catBadge:     "inline-flex items-center px-2 py-0.5 rounded-full bg-blue-50 text-blue-600 text-[10px] font-bold",
  detail:       "grid grid-cols-1 lg:grid-cols-3 gap-5",
  detailMain:   "lg:col-span-2 space-y-4",
  detailAside:  "space-y-4",
} as const;
