export const payments = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  statGrid:     "grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6",
  statCard:     "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  statValue:    "text-3xl font-black text-gray-900",
  statLabel:    "text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  amountPos:    "text-base font-black text-green-600",
  amountNeg:    "text-base font-black text-red-500",
  methodTag:    "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-700 text-[10px] font-bold",
  statusPaid:   "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusFailed: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 text-red-700 text-xs font-semibold",
  statusPending:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
  txId:         "font-mono text-xs text-gray-400",
  receiptBtn:   "inline-flex items-center gap-1 text-xs font-semibold text-blue-600 hover:text-blue-700 transition-colors",
} as const;
