export const settings = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-3xl mx-auto space-y-5",
  sectionCard:  "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  sectionHead:  "px-5 py-4 border-b border-gray-100 bg-gray-50 flex items-center justify-between",
  sectionTitle: "font-bold text-gray-900 text-sm flex items-center gap-2",
  sectionBody:  "p-5 space-y-4",
  row:          "flex items-center justify-between gap-4 py-3 border-b border-gray-50 last:border-0",
  rowLabel:     "flex flex-col",
  rowLabelText: "text-sm font-semibold text-gray-900",
  rowLabelSub:  "text-xs text-gray-400 mt-0.5",
  toggle:       "relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors",
  toggleOn:     "bg-blue-600",
  toggleOff:    "bg-gray-200",
  toggleThumb:  "pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow transition",
  dangerCard:   "bg-white rounded-2xl border border-red-200 shadow-sm overflow-hidden",
  dangerHead:   "px-5 py-4 border-b border-red-100 bg-red-50",
  dangerTitle:  "font-bold text-red-700 text-sm",
  dangerBody:   "p-5",
  dangerText:   "text-sm text-red-600 mb-4",
  regionBtn:    "inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-green-600 hover:bg-green-700 text-white font-bold text-sm transition-colors touch-manipulation disabled:opacity-50",
  seedResult:   "mt-3 text-sm font-semibold",
  seedOk:       "text-green-600",
  seedErr:      "text-red-500",
} as const;
