export const subscription = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  topbar:       "flex items-center justify-between mb-5 gap-4 flex-wrap",
  title:        "text-xl font-black text-gray-900",
  grid:         "grid grid-cols-1 lg:grid-cols-3 gap-5",
  statGrid:     "grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6",
  statCard:     "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  statValue:    "text-3xl font-black text-gray-900",
  statLabel:    "text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  planCard:     "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  planHead:     "px-5 py-4 border-b border-gray-100 bg-gray-50 flex items-center justify-between",
  planName:     "font-black text-gray-900 text-base",
  planPrice:    "text-2xl font-black text-blue-600",
  planDuration: "text-xs text-gray-400 font-semibold",
  planBody:     "p-5",
  planCount:    "text-3xl font-black text-gray-900",
  planCountLabel:"text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  subRow:       "flex items-center justify-between gap-3 py-3 border-b border-gray-50 last:border-0",
  subUser:      "flex items-center gap-2.5",
  subAvatar:    "w-8 h-8 rounded-full bg-blue-100 text-blue-700 font-bold text-xs flex items-center justify-center",
  subName:      "font-semibold text-gray-900 text-sm",
  subEmail:     "text-xs text-gray-400",
  subDate:      "text-xs text-gray-400",
  statusActive: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusExpired:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 text-red-700 text-xs font-semibold",
  statusPending:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
} as const;
