export const users = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  topbar:       "flex items-center justify-between mb-5 gap-4 flex-wrap",
  title:        "text-xl font-black text-gray-900",
  statGrid:     "grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6",
  statCard:     "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  statValue:    "text-3xl font-black text-gray-900",
  statLabel:    "text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  userCell:     "flex items-center gap-3",
  avatar:       "w-9 h-9 rounded-full bg-blue-100 text-blue-700 font-bold text-sm flex items-center justify-center flex-shrink-0",
  userName:     "font-semibold text-gray-900 text-sm",
  userEmail:    "text-xs text-gray-400",
  userPhone:    "text-xs text-gray-400 mt-0.5",
  roleAdmin:    "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-semibold",
  roleSupport:  "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-xs font-semibold",
  roleUser:     "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
  statusActive: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusBanned: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 text-red-700 text-xs font-semibold",
  statusPending:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
  drawerRoot:   "fixed inset-y-0 right-0 w-full sm:w-[420px] bg-white shadow-2xl z-50 flex flex-col",
  drawerHead:   "px-5 py-4 border-b border-gray-100 flex items-center justify-between",
  drawerBody:   "flex-1 overflow-y-auto p-5 space-y-4",
  drawerFoot:   "px-5 py-4 border-t border-gray-100 flex items-center justify-end gap-3",
} as const;
