// app/(dashboard)/dashboard/managment/managementData.ts
import {
  FaShip,
  FaCar,
  FaHome,
  FaMotorcycle,
  FaTractor,
  FaUsers,
  FaFileInvoice,
  FaChartBar,
  FaShieldAlt,
  FaDatabase,
  FaCog,
  FaList,
  FaStore,
  FaBriefcase,
  FaStar,
  FaLayerGroup,
  FaUserCheck,
  FaUserCog,
} from "react-icons/fa";

export interface ManagementSection {
  id: string;
  name: string;
  path: string;
  icon: any;
  description: string;
  category: string;
  featured?: boolean;
}

export const managementSections: ManagementSection[] = [
  {
    id: "marketplace",
    name: "Marketplace",
    path: "/managment/marketplace",
    icon: FaStore,
    description: "Manage marketplace listings",
    category: "listings",
    featured: true,
  },
  {
    id: "realestate",
    name: "Real Estate",
    path: "/managment/real-estate",
    icon: FaHome,
    description: "Create and manage real estate properties",
    category: "listings",
    featured: true,
  },
  {
    id: "cars",
    name: "Cars",
    path: "/managment/cars",
    icon: FaCar,
    description: "Create and manage car listings",
    category: "listings",
    featured: true,
  },
  {
    id: "boats",
    name: "Boats",
    path: "/managment/boats",
    icon: FaShip,
    description: "Create and manage boat listings",
    category: "listings",
    featured: true,
  },
  {
    id: "tractors",
    name: "Tractors",
    path: "/managment/tractors",
    icon: FaTractor,
    description: "Create and manage tractor listings",
    category: "listings",
  },
  {
    id: "motorcycles",
    name: "Motorcycles",
    path: "/managment/motorcycles",
    icon: FaMotorcycle,
    description: "Create and manage motorcycle listings",
    category: "listings",
  },
  {
    id: "jobs",
    name: "Jobs",
    path: "/managment/jobs",
    icon: FaBriefcase,
    description: "Manage job listings and applications",
    category: "listings",
  },
];

export const otherSections: ManagementSection[] = [
  {
    id: "listings",
    name: "All Listings",
    path: "/managment/listings",
    icon: FaList,
    description: "View and manage all marketplace listings",
    category: "content",
    featured: true,
  },
  {
    id: "featured",
    name: "Featured Items",
    path: "/managment/featured",
    icon: FaStar,
    description: "Manage featured and promoted listings",
    category: "content",
  },
  {
    id: "bulk",
    name: "Bulk Operations",
    path: "/managment/bulk",
    icon: FaLayerGroup,
    description: "Bulk import, export, and updates",
    category: "operations",
  },
  {
    id: "categories",
    name: "Categories",
    path: "/managment/categories",
    icon: FaList,
    description: "Manage listing categories and filters",
    category: "content",
  },
  {
    id: "users",
    name: "User Management",
    path: "/managment/users",
    icon: FaUsers,
    description: "Manage user accounts and permissions",
    category: "operations",
    featured: true,
  },
  {
    id: "roles",
    name: "Role Management",
    path: "/managment/roles",
    icon: FaUserCog,
    description: "Configure user roles and permissions",
    category: "operations",
  },
  {
    id: "analytics",
    name: "Analytics",
    path: "/managment/analytics",
    icon: FaChartBar,
    description: "View platform analytics and reports",
    category: "analytics",
    featured: true,
  },
  {
    id: "reports",
    name: "Reports",
    path: "/managment/reports",
    icon: FaFileInvoice,
    description: "Generate and view system reports",
    category: "analytics",
  },
  {
    id: "moderation",
    name: "Content Moderation",
    path: "/managment/moderation",
    icon: FaShieldAlt,
    description: "Moderate user content and listings",
    category: "operations",
  },
  {
    id: "content-review",
    name: "Content Review",
    path: "/managment/content-review",
    icon: FaList,
    description: "Review and approve user submissions",
    category: "content",
  },
  {
    id: "marketplace",
    name: "Marketplace Settings",
    path: "/managment/marketplace",
    icon: FaStore,
    description: "Configure marketplace settings",
    category: "settings",
  },
  {
    id: "invoices",
    name: "Invoices & Payments",
    path: "/managment/invoices",
    icon: FaFileInvoice,
    description: "Manage invoices and payment records",
    category: "operations",
  },
  {
    id: "backup",
    name: "Backup & Restore",
    path: "/managment/backup",
    icon: FaDatabase,
    description: "System backup and restore operations",
    category: "operations",
  },
  {
    id: "system-health",
    name: "System Health",
    path: "/managment/system-health",
    icon: FaFileInvoice,
    description: "Monitor system performance and health",
    category: "analytics",
  },
  {
    id: "user-support",
    name: "User Support",
    path: "/managment/user-support",
    icon: FaUserCheck,
    description: "Manage user support tickets",
    category: "operations",
  },
  {
    id: "settings",
    name: "System Settings",
    path: "/managment/settings",
    icon: FaCog,
    description: "Configure system-wide settings",
    category: "settings",
    featured: true,
  },
];
