import { ReactElement } from "react";
import {
  FaShip,
  FaTools,
  FaWrench,
  FaCarSide,
  FaCar,
  FaTrailer,
  FaBus,
  FaKey,
  FaSchool,
  FaTruck,
  FaCity,
  FaUserTie,
  FaBuilding,
  FaHospital,
  FaMotorcycle,
  FaToolbox,
  FaHome,
  FaLaptop,
  FaTv,
  FaUtensils,
  FaMugHot,
  FaWineGlass,
  FaPalette,
  FaStar,
  FaBicycle,
  FaCouch,
  FaTshirt,
  FaCamera,
  FaPaw,
  FaDumbbell,
  FaPuzzlePiece,
  FaCogs,
  FaTree,
  FaEnvelope,
  FaPhone,
  FaGlobe,
  FaGraduationCap,
} from "react-icons/fa";
import {
  FaComputer,
  FaPaintbrush,
  FaTruckFront,
  FaTruckMoving,
  FaVanShuttle,
} from "react-icons/fa6";
import { MdElectricCar } from "react-icons/md";
import {
  GiBoatFishing,
  GiBoatPropeller,
  GiFishingBoat,
  GiSailboat,
  GiAutoRepair,
  GiCarKey,
  GiFertilizerBag,
  GiBriefcase,
  GiGoat,
  GiFarmTractor,
  GiGrain,
  GiField,
  GiFarmer,
  GiBrickWall,
  GiCamel,
  GiCow,
  GiSheep,
  GiHorseHead,
  GiDonkey,
  GiChicken,
  GiBirdCage,
} from "react-icons/gi";
import { IoBoatSharp } from "react-icons/io5";

export const ICONS = {
  giFishingBoat: () => <GiFishingBoat />,
  faShip: () => <FaShip />,
  giSailboat: () => <GiSailboat />,
  ioBoatSharp: () => <IoBoatSharp />,
  giBoatFishing: () => <GiBoatFishing />,
  giBoatPropeller: () => <GiBoatPropeller />,
  faWrench: () => <FaWrench />,
  faTools: () => <FaTools />,
  faEnvelope: () => <FaEnvelope />,
  faPhone: () => <FaPhone />,
  globe: () => <FaGlobe />,
  graduation: () => <FaGraduationCap />,
  car: () => <FaCar />,
  carSide: () => <FaCarSide />,
  bus: () => <FaBus />,
  truck: () => <FaTruck />,
  key: () => <FaKey />,
  tools: () => <FaTools />,
  tools20: () => <FaTools />,
  autoRepair: () => <GiAutoRepair />,
  truckFront: () => <FaTruckFront />,
  wrench: () => <FaWrench />,
  cogs: () => <FaCogs />,
  electricCar: () => <MdElectricCar />,
  carKey: () => <GiCarKey />,
  trailer: () => <FaTrailer />,
  busLarge: () => <FaBus />,
  vanShuttle: () => <FaVanShuttle />,
  school: () => <FaSchool />,
  city: () => <FaCity />,
  carSideLarge: () => <FaCarSide />,
  carLarge: () => <FaCar />,
  busLarge28: () => <FaBus />,
  trailerLarge: () => <FaTrailer />,
  toolsLarge: () => <FaTools />,
  truckFrontLarge: () => <FaTruckFront />,
  electricCarLarge: () => <MdElectricCar />,
  userTie: () => <FaUserTie />,
  building: () => <FaBuilding />,
  hospital: () => <FaHospital />,
  paintbrush: () => <FaPaintbrush />,
  computer: () => <FaComputer />,
  motorcycle: () => <FaMotorcycle />,
  toolbox: () => <FaToolbox />,
  home: () => <FaHome />,
  laptop: () => <FaLaptop />,
  tv: () => <FaTv />,
  utensils: () => <FaUtensils />,
  mugHot: () => <FaMugHot />,
  wineGlass: () => <FaWineGlass />,
  palette: () => <FaPalette />,
  star: () => <FaStar />,
  bicycle: () => <FaBicycle />,
  couch: () => <FaCouch />,
  tshirt: () => <FaTshirt />,
  camera: () => <FaCamera />,
  paw: () => <FaPaw />,
  dumbbell: () => <FaDumbbell />,
  puzzlePiece: () => <FaPuzzlePiece />,
  fertilizerBag: () => <GiFertilizerBag />,
  fertilizerBag20: () => <GiFertilizerBag />,
  fertilizerBag32: () => <GiFertilizerBag />,
  briefcase: () => <GiBriefcase />,
  goat: () => <GiGoat />,
  farmTractor: () => <GiFarmTractor />,
  farmTractor20: () => <GiFarmTractor />,
  farmTractor32: () => <GiFarmTractor />,
  grain: () => <GiGrain />,
  grain20: () => <GiGrain />,
  grain32: () => <GiGrain />,
  truckMoving: () => <FaTruckMoving />,
  truckMoving32: () => <FaTruckMoving />,
  field: () => <GiField />,
  farmer: () => <GiFarmer />,
  brickWall: () => <GiBrickWall />,
  camel: () => <GiCamel />,
  cow: () => <GiCow />,
  sheep: () => <GiSheep />,
  horseHead: () => <GiHorseHead />,
  donkey: () => <GiDonkey />,
  chicken: () => <GiChicken />,
  birdCage: () => <GiBirdCage />,
  store: () => <FaBuilding />,
  warehouse: () => <FaBuilding />,
  tree: () => <FaTree />,
};

export type IconMap = typeof ICONS;
export type IconName = keyof IconMap;
