import {
  FaCarSide,
  FaCar,
  FaTrailer,
  FaTools,
  FaMotorcycle,
  FaToolbox,
  FaShip,
  FaCouch,
  FaTshirt,
  FaTv,
  FaPaintBrush,
  FaTruckMoving,
  FaHome,
  FaDollarSign,
  FaBus,
  FaBriefcase,
  FaLaptopCode,
  FaChartLine,
  FaGraduationCap,
  FaHeartbeat,
  FaUtensils,
  FaPlane,
  FaCity,
  FaAnchor,
  FaHardHat,
  FaTractor,
  FaTruck,
} from "react-icons/fa";
import { FaTruckFront, FaBuilding, FaLeaf } from "react-icons/fa6";
import {
  GiGoat,
  GiBoatFishing,
  GiBoatPropeller,
  GiFarmer,
  GiFarmTractor,
  GiFertilizerBag,
  GiField,
  GiGrain,
  GiCommercialAirplane,
  GiPublicSpeaker,
  GiShipWheel,
} from "react-icons/gi";
import {
  MdCarRental,
  MdElectricCar,
  MdOutlineMiscellaneousServices,
  MdSportsSoccer,
  MdWork,
  MdAccessTime,
  MdFitnessCenter,
  MdSchool,
  MdHomeWork,
  MdComputer,
  MdAttachMoney,
  MdLocalHospital,
  MdRestaurant,
  MdConstruction,
  MdAgriculture,
  MdLocalShipping,
} from "react-icons/md";
import { RiRemoteControlLine } from "react-icons/ri";
import { IoIosBusiness } from "react-icons/io";

export const CategoryIcons = {
  Antiques: FaPaintBrush,
  Electronics: FaTv,
  Animals: GiGoat,
  Sports: MdSportsSoccer,
  Furniture: FaCouch,
  Fashion: FaTshirt,
  Rent: FaHome,
  Sale: FaDollarSign,
  Land: GiField,
  Farm: GiFarmer,
  Commercial: FaBuilding,
  CarSale: FaCarSide,
  CarLease: FaCar,
  Trailer: FaTrailer,
  Parts: FaTools,
  Truck: FaTruckFront,
  Electric: MdElectricCar,
  Bus: FaBus,
  MotorcycleSale: FaMotorcycle,
  MotorcycleRent: MdCarRental,
  SpareParts: MdOutlineMiscellaneousServices,
  OtherMotorcycle: FaToolbox,
  BoatSale: FaShip,
  BoatRent: GiBoatFishing,
  BoatEngine: GiBoatPropeller,
  BoatParts: FaTools,
  Tractor: GiFarmTractor,
  FarmTools: FaTruckMoving,
  FertilizerSpreader: GiFertilizerBag,
  Harvester: GiGrain,
  Plow: GiField,
  Irrigation: FaTractor,
  FullTime: MdWork,
  PartTime: MdAccessTime,
  Physical: MdFitnessCenter,
  Internship: MdSchool,
  Remote: RiRemoteControlLine,
  Tech: FaLaptopCode,
  Finance: FaChartLine,
  Education: FaGraduationCap,
  Healthcare: FaHeartbeat,
  Hospitality: FaUtensils,
  IT: FaLaptopCode,
  Airport: FaPlane,
  Public: FaCity,
  Seaport: FaAnchor,
  Construction: MdConstruction,
  Agriculture: MdAgriculture,
  Transportation: FaTruck,
};
