import { AiOutlineCar, AiOutlineHome } from "react-icons/ai";
import {
  FaCaravan,
  FaShip,
  FaTractor,
  FaMotorcycle,
  FaCar,
  FaStore,
  FaWarehouse,
} from "react-icons/fa";

import { MohyusLogoIcon } from "@/app/utils/icons/customerIcons";
import {
  marketplaceSubCategories,
  realEstateSubCategories,
  boatSubCategories,
  farmEquipmentSubCategories,
  vehicleSubCategories,
  jobSubCategories,
  motorcycleSubCategories,
} from "./subCategories";
import { MdWork } from "react-icons/md";
import { IoIosBoat } from "react-icons/io";
import { MainCategory } from "@/app/utils/types/categoriestype";
import { LuSofa } from "@/app/utils/icons";

export const allCategories: MainCategory[] = [
  {
    key: "Marketplace",
    name: "Marketplace",
    href: "/Marketplace",
    icon: <LuSofa />,
    so: "Suuq",
    dashboardIcon: FaStore,
    dashboardLink: "/dashboard/categories/marketplace",
    subCategories: marketplaceSubCategories,
    title: undefined,
  },
  {
    key: "RealEstate",
    name: "Real Estate",
    href: "/real-estate",
    icon: <AiOutlineHome />,
    so: "Guryaha, hantida maguurtada ah",
    dashboardIcon: FaWarehouse,
    dashboardLink: "/dashboard/categories/real-estate",
    subCategories: realEstateSubCategories,
    title: undefined,
  },
  {
    key: "Cars",
    name: "Cars",
    href: "/cars",
    icon: <AiOutlineCar />,
    so: "Gawaarida",
    dashboardIcon: FaCar,
    dashboardLink: "/dashboard/categories/cars",
    subCategories: vehicleSubCategories,
    title: undefined,
  },
  {
    key: "Boats",
    name: "Boats",
    href: "/boats",
    icon: <IoIosBoat />,
    so: "Doomo",
    dashboardIcon: FaShip,
    dashboardLink: "/dashboard/categories/boats",
    subCategories: boatSubCategories,
    title: undefined,
  },
  {
    key: "farmequipment",
    name: "Farmequipment",
    href: "/farmequipment",
    icon: <FaTractor />,
    so: "Qalabka Beeraha",
    dashboardIcon: FaTractor,
    dashboardLink: "/dashboard/categories/farmequipment",
    subCategories: farmEquipmentSubCategories,
    title: undefined,
  },
  {
    key: "Motorcycles",
    name: "Motorcycles",
    href: "/motorcycles",
    icon: <FaCaravan />,
    so: "Mootooyin",
    dashboardIcon: FaMotorcycle,
    dashboardLink: "/dashboard/categories/motorcycles",
    subCategories: motorcycleSubCategories,
    title: undefined,
  },
  {
    key: "Jobs",
    name: "Jobs",
    href: "/jobs",
    icon: <MdWork />,
    so: "Shaqo",
    dashboardIcon: MdWork,
    dashboardLink: "/dashboard/categories/jobs",
    subCategories: jobSubCategories,
    title: undefined,
  },
  {
    key: "Smartsuuq",
    logo: "/Smartsuq.jpg",
    href: "https://www.smartsuuq.com/",
    icon: <MohyusLogoIcon />,
    dashboardIcon: MohyusLogoIcon,
    dashboardLink: "/dashboard/categories/smartsuuq",
    subCategories: [],
    title: undefined,
  },
];
