ALTER TABLE "RealEstateFee" ADD COLUMN IF NOT EXISTS "other" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE "CarFee" ADD COLUMN IF NOT EXISTS "other" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE "MotorcycleFee" ADD COLUMN IF NOT EXISTS "other" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE "BoatFee" ADD COLUMN IF NOT EXISTS "other" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE "EquipmentFeeConfig" ADD COLUMN IF NOT EXISTS "other" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE "JobFeeConfig" ADD COLUMN IF NOT EXISTS "other" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
