export const mgr = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  topbar:       "flex items-center justify-between mb-6 gap-4 flex-wrap",
  title:        "text-2xl font-black text-gray-900",
  subtitle:     "text-sm text-gray-400 mt-0.5",
  searchWrap:   "flex items-center gap-2 px-3 py-2 border border-gray-200 rounded-xl bg-white w-full max-w-xs",
  searchInput:  "flex-1 outline-none text-sm placeholder:text-gray-400",
  filters:      "flex items-center gap-2 flex-wrap",
  filterBtn:    "px-3 py-1.5 rounded-lg border border-gray-200 bg-white text-xs font-semibold text-gray-600 hover:border-blue-400 hover:text-blue-600 transition-colors",
  filterActive: "px-3 py-1.5 rounded-lg border border-blue-500 bg-blue-50 text-xs font-semibold text-blue-700",
  table:        "w-full bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  thead:        "border-b border-gray-100 bg-gray-50",
  th:           "text-left text-[10px] font-black text-gray-400 uppercase tracking-widest px-5 py-3",
  tr:           "border-b border-gray-50 last:border-0 hover:bg-gray-50 transition-colors",
  td:           "px-5 py-3.5 text-sm text-gray-700",
  tdMuted:      "px-5 py-3.5 text-sm text-gray-400",
  actions:      "flex items-center gap-1",
  actionEdit:   "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-blue-50 text-gray-400 hover:text-blue-600 transition-colors",
  actionView:   "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-700 transition-colors",
  actionDel:    "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-600 transition-colors",
  userCell:     "flex items-center gap-3",
  avatar:       "w-8 h-8 rounded-full bg-blue-100 text-blue-700 font-bold text-xs flex items-center justify-center flex-shrink-0",
  userName:     "font-semibold text-gray-900 text-sm",
  userSub:      "text-xs text-gray-400",
  pagination:   "flex items-center justify-between px-5 py-3.5 border-t border-gray-100",
  pageInfo:     "text-xs text-gray-400",
  pageNav:      "flex items-center gap-1",
  pageBtn:      "w-8 h-8 rounded-lg text-xs font-semibold text-gray-600 hover:bg-gray-100 transition-colors inline-flex items-center justify-center",
  pageBtnActive:"w-8 h-8 rounded-lg text-xs font-semibold bg-blue-600 text-white inline-flex items-center justify-center",
  drawerRoot:   "fixed inset-y-0 right-0 w-full sm:w-[420px] bg-white shadow-2xl z-50 flex flex-col",
  drawerHead:   "px-5 py-4 border-b border-gray-100 flex items-center justify-between",
  drawerTitle:  "font-bold text-gray-900 text-base",
  drawerClose:  "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-gray-100 text-gray-500 transition-colors",
  drawerBody:   "flex-1 overflow-y-auto p-5 space-y-4",
  drawerFoot:   "px-5 py-4 border-t border-gray-100 flex items-center justify-end gap-3",
  roleAdmin:    "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-semibold",
  roleUser:     "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
  roleSupport:  "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-xs font-semibold",
  statusActive: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusBanned: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 text-red-700 text-xs font-semibold",
  statusPending:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
} as const;
