export const reports = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-5xl mx-auto",
  list:         "space-y-3",
  card:         "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  cardHead:     "flex items-start justify-between gap-3",
  cardType:     "text-[10px] font-black text-red-500 uppercase tracking-widest",
  cardTitle:    "font-bold text-gray-900 text-sm mt-0.5",
  reportedItem: "flex items-center gap-2 mt-2 px-3 py-2 bg-gray-50 rounded-xl",
  reportedImg:  "w-10 h-10 rounded-lg bg-gray-200 object-cover flex-shrink-0",
  reportedName: "text-xs font-semibold text-gray-700 line-clamp-1",
  reportedSub:  "text-[10px] text-gray-400",
  reporter:     "flex items-center gap-2 mt-3",
  reporterAvatar:"w-6 h-6 rounded-full bg-gray-200 text-gray-600 font-bold text-[10px] flex items-center justify-center",
  reporterName: "text-xs font-semibold text-gray-600",
  reporterTime: "text-[10px] text-gray-400 ml-auto",
  reason:       "text-xs text-gray-500 mt-2 leading-relaxed",
  cardFoot:     "flex items-center gap-2 mt-4 pt-3 border-t border-gray-50",
  statusNew:    "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 text-red-700 text-xs font-semibold",
  statusReview: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
  statusDone:   "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusDismiss:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
} as const;
