export const roles = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-4xl mx-auto",
  grid:         "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4",
  card:         "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  cardHead:     "flex items-center justify-between mb-4",
  cardIcon:     "w-10 h-10 rounded-xl flex items-center justify-center text-lg",
  cardIconAdmin:"bg-purple-100 text-purple-600",
  cardIconSupport:"bg-blue-100 text-blue-600",
  cardIconUser: "bg-gray-100 text-gray-600",
  cardName:     "font-black text-gray-900 text-sm",
  cardCount:    "text-xs text-gray-400",
  permList:     "space-y-2 mt-3",
  permItem:     "flex items-center gap-2 text-xs text-gray-600",
  permCheck:    "w-4 h-4 text-green-500 flex-shrink-0",
  permCross:    "w-4 h-4 text-gray-300 flex-shrink-0",
  roleAdmin:    "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-semibold",
  roleSupport:  "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-xs font-semibold",
  roleUser:     "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
} as const;
