export const managerUsers = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-7xl mx-auto",
  topbar:       "flex items-center justify-between mb-5 gap-4 flex-wrap",
  bulkBar:      "flex items-center gap-2 px-4 py-2.5 bg-blue-50 border border-blue-200 rounded-xl mb-4",
  bulkText:     "text-sm font-semibold text-blue-700 flex-1",
  userCell:     "flex items-center gap-3",
  avatar:       "w-9 h-9 rounded-full bg-blue-100 text-blue-700 font-bold text-sm flex items-center justify-center flex-shrink-0",
  avatarImg:    "w-9 h-9 rounded-full object-cover flex-shrink-0",
  name:         "font-semibold text-gray-900 text-sm",
  email:        "text-xs text-gray-400",
  phone:        "text-xs text-gray-400 mt-0.5",
  joined:       "text-xs text-gray-400",
  listCount:    "text-xs font-semibold text-gray-700",
  roleAdmin:    "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-semibold",
  roleSupport:  "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-xs font-semibold",
  roleUser:     "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
  statusActive: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs font-semibold",
  statusBanned: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 text-red-700 text-xs font-semibold",
  statusPending:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
} as const;
