export const devices = {
  root:        "min-h-screen bg-gray-50",
  inner:       "max-w-7xl mx-auto px-3 sm:px-4 py-5",
  grid:        "grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3",
  card:        "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden active:scale-[0.98] transition-transform touch-manipulation",
  cardImg:     "relative w-full aspect-square bg-gray-100",
  cardBody:    "p-3",
  cardTitle:   "font-bold text-gray-900 text-sm leading-snug line-clamp-2",
  cardBrand:   "text-xs text-gray-400 mt-0.5",
  cardPrice:   "text-blue-600 font-black text-base mt-1.5",
  cardMeta:    "flex items-center gap-1.5 text-[11px] text-gray-400 mt-1",
  badge:       "absolute top-2 left-2 px-1.5 py-0.5 rounded-full text-[10px] font-black",
  badgeNew:    "bg-blue-600 text-white",
  badgeUsed:   "bg-gray-200 text-gray-700",
  badgeSold:   "bg-gray-800 text-white",
  filterBar:   "flex items-center gap-2 px-3 sm:px-4 py-2.5 bg-white border-b border-gray-100 overflow-x-auto scrollbar-hide",
  filterBtn:   "flex-shrink-0 px-3 py-1.5 rounded-lg border border-gray-200 text-xs font-semibold text-gray-600 hover:border-blue-400 hover:text-blue-600 transition-colors whitespace-nowrap",
  filterActive:"flex-shrink-0 px-3 py-1.5 rounded-lg border border-blue-500 bg-blue-50 text-xs font-semibold text-blue-700 whitespace-nowrap",
  sortWrap:    "flex items-center gap-2 px-3 sm:px-4 py-2 bg-white border-b border-gray-100",
  sortLabel:   "text-xs text-gray-400 font-semibold",
  sortSelect:  "text-xs font-semibold text-gray-700 outline-none bg-transparent",
  detailImg:   "relative w-full aspect-square sm:aspect-video rounded-2xl overflow-hidden bg-gray-100",
  detailTitle: "text-xl font-black text-gray-900 leading-snug mt-4",
  detailBrand: "text-sm text-gray-400 mt-0.5",
  detailPrice: "text-3xl font-black text-blue-600 mt-2",
  detailSpec:  "grid grid-cols-2 gap-3 mt-4",
  specItem:    "bg-gray-50 rounded-xl p-3",
  specLabel:   "text-[10px] font-black text-gray-400 uppercase tracking-widest",
  specValue:   "text-sm font-bold text-gray-900 mt-0.5",
} as const;
