export const business = {
  root:        "min-h-screen bg-gray-50/60 py-8 px-4",
  inner:       "max-w-6xl mx-auto",
  header:      "text-center mb-10",
  headerTitle: "text-3xl md:text-4xl font-extrabold tracking-tight text-gray-900",
  headerSub:   "text-gray-500 mt-2 text-sm",
  planGrid:    "grid grid-cols-1 md:grid-cols-3 gap-5",
  planCard:    "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden flex flex-col",
  planCardFeat:"bg-blue-600 rounded-2xl border border-blue-600 shadow-md overflow-hidden flex flex-col",
  planHeader:  "px-6 py-5 border-b border-gray-100",
  planHeaderFeat:"px-6 py-5 border-b border-blue-500",
  planName:    "font-black text-gray-900 text-lg",
  planNameFeat:"font-black text-white text-lg",
  planPrice:   "text-3xl font-black text-blue-600 mt-1",
  planPriceFeat:"text-3xl font-black text-white mt-1",
  planDuration:"text-xs text-gray-400 font-semibold",
  planDurationFeat:"text-xs text-blue-200 font-semibold",
  planBody:    "p-6 flex-1 space-y-3",
  planFeature: "flex items-center gap-2.5 text-sm text-gray-600",
  planFeatureFeat:"flex items-center gap-2.5 text-sm text-blue-100",
  planCheck:   "w-4 h-4 text-green-500 flex-shrink-0",
  planCheckFeat:"w-4 h-4 text-blue-300 flex-shrink-0",
  planFooter:  "px-6 pb-6",
  planBtn:     "w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl text-sm transition-colors touch-manipulation",
  planBtnFeat: "w-full py-2.5 bg-white hover:bg-blue-50 text-blue-600 font-bold rounded-xl text-sm transition-colors touch-manipulation",
  planBadge:   "inline-flex items-center px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-[10px] font-black mb-2",
  planBadgeFeat:"inline-flex items-center px-2 py-0.5 rounded-full bg-white/20 text-white text-[10px] font-black mb-2",
  statGrid:    "grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8",
  statCard:    "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  statValue:   "text-3xl font-black text-gray-900",
  statLabel:   "text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  statTrend:   "text-xs font-semibold text-green-600 mt-2",
} as const;
