export const footer = {
  root:      "bg-white border-t border-gray-100 mt-auto",
  inner:     "max-w-7xl mx-auto px-4 sm:px-6 py-10",
  grid:      "grid grid-cols-2 sm:grid-cols-4 gap-8",
  brand:     "col-span-2 sm:col-span-1",
  logo:      "font-black text-blue-600 text-xl tracking-tight",
  tagline:   "text-sm text-gray-400 mt-2 leading-relaxed",
  social:    "flex items-center gap-3 mt-4",
  socialBtn: "inline-flex items-center justify-center w-8 h-8 rounded-lg bg-gray-100 hover:bg-blue-100 hover:text-blue-600 text-gray-500 transition-colors",
  colTitle:  "font-black text-gray-900 text-sm mb-3",
  colLink:   "block text-sm text-gray-500 hover:text-blue-600 transition-colors mb-2",
  bottom:    "border-t border-gray-100 mt-8 pt-6 flex flex-col sm:flex-row items-center justify-between gap-3",
  copy:      "text-xs text-gray-400",
  legalLinks:"flex items-center gap-4",
  legalLink: "text-xs text-gray-400 hover:text-blue-600 transition-colors",
  mobileBar: "fixed bottom-0 left-0 w-full bg-white border-t border-gray-200 z-40 flex items-center justify-around px-2 pb-[env(safe-area-inset-bottom)] pt-2",
  mobileTab: "flex flex-col items-center gap-0.5 px-3 py-1 text-gray-400 hover:text-blue-600 transition-colors touch-manipulation",
  mobileTabActive:"flex flex-col items-center gap-0.5 px-3 py-1 text-blue-600 touch-manipulation",
  mobileTabLabel:"text-[10px] font-semibold",
} as const;
