export const page = {
  root:         "min-h-screen bg-gray-50",
  inner:        "max-w-4xl mx-auto px-3 sm:px-4 py-5 sm:py-7",
  innerWide:    "max-w-7xl mx-auto px-3 sm:px-4 py-5 sm:py-7",
  innerNarrow:  "max-w-xl mx-auto px-4 py-8",
  header:       "sticky top-0 z-20 bg-white border-b border-gray-100 px-4 py-3.5 flex items-center gap-3 shadow-sm",
  headerTitle:  "text-base font-black text-gray-900 leading-tight",
  headerSub:    "text-[11px] text-gray-400 font-medium leading-none mt-0.5",
  section:      "mb-8",
  sectionLabel: "text-[10px] font-black text-gray-400 uppercase tracking-widest mb-3 px-1",
  hero:         "text-center py-16 px-4",
  heroTitle:    "text-4xl sm:text-5xl font-black text-gray-900 leading-tight",
  heroSub:      "text-lg text-gray-400 mt-4 max-w-xl mx-auto",
  heroCta:      "flex items-center justify-center gap-3 mt-8 flex-wrap",
  profile:      "max-w-2xl mx-auto px-4 py-8 space-y-5",
  profileCard:  "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  profileAvatar:"w-20 h-20 rounded-2xl bg-blue-100 text-blue-700 font-black text-2xl flex items-center justify-center",
  profileName:  "text-xl font-black text-gray-900",
  profileEmail: "text-sm text-gray-400",
  profileRow:   "flex items-center justify-between gap-4 px-5 py-4 border-b border-gray-50 last:border-0",
  profileLabel: "text-[10px] font-black text-gray-400 uppercase tracking-widest",
  profileValue: "text-sm font-semibold text-gray-900",
  dangerZone:   "px-5 py-4 bg-red-50 border-t border-red-100",
  dangerText:   "text-sm font-semibold text-red-700 mb-3",
} as const;
