export const FIELD_NAMES = {
  ID: "id",
  TITLE: "title",
  PRICE: "price",
  DESCRIPTION: "description",
  MAIN_CATEGORY: "mainCategory",
  CATEGORY: "category",
  SUBCATEGORY: "subcategory",
  REGION: "region",
  CITY: "city",
  IMAGES: "images",
  CREATED_AT: "createdAt",
  EXPIRY_DATE: "expiryDate",
  IS_PAID: "isPaid",
  IS_BASIC_30: "isBasic30",
  IS_STANDARD_60: "isStandard60",
  IS_PREMIUM_90: "isPremium90",
  MA_GADAY: "maGaday",
  USER: "user",
  FEE: "fee",
  PLAN: "plan",
  USERNAME: "username",
  EMAIL: "email",
  PHONE: "phone",
  PROFILE_IMAGE: "profileImage",
  USER_ID: "userId",
  PLAN_ID: "planId",
  PLAN_AMOUNT: "planAmount",
  CAR_ID: "carId",
  STATUS: "status",
  PAID_AT: "paidAt",
  SUCCESS: "success",
  DATA: "data",
  MESSAGE: "message",
  ERROR: "error",
  BRAND: "brand",
  VEHICLE_MODEL: "vehicleModel",
  YEAR: "year",
  MILEAGE: "mileage",
  TRANSMISSION: "transmission",
  FUEL_TYPE: "fuelType",
  COLOR: "color",
  FEE_ID: "feeId",
  FEE_AMOUNT: "feeAmount",
  IS_EXPIRED: "isExpired",
  DAYS_UNTIL_EXPIRY: "daysUntilExpiry",
  FORMATTED_EXPIRY: "formattedExpiry",
  FOUND_BY_FALLBACK: "foundByFallback",
} as const;

export const ERROR_MESSAGES = {
  SERVER_ERROR: "Server Error",
  NOT_FOUND: "Car not found",
  INVALID_ID: "Invalid ID",
  MISSING_USER_ID: "Missing userId in request",
  CREATE_FAILED: "Failed to create car listing",
  UPDATE_FAILED: "Update failed",
  IS_PAID_MUST_BE_BOOLEAN: "isPaid must be boolean",
} as const;

export const SUCCESS_MESSAGES = {
  DELETED: "Car deleted successfully",
} as const;

export const CACHE_KEYS = {
  TOTAL: "cars:total",
  UNFILTERED: "cars:all:unfiltered",
  PAID_PREFIX: "cars:all:paid",
  DETAIL_PREFIX: "car:detail",
};
