service: karaadi-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION, "us-east-1"}
  stage: ${opt:stage, 'prod'}
  memorySize: 128
  timeout: 10

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

package:
  individually: true

plugins:
  - serverless-offline
