import { BASE_API_URL } from "@/actions/constant/BASE_API_URL";
import {
  ADS_ENDPOINTS,
  ADVERTISEMENT_ENDPOINTS,
  AGENCY_ENDPOINTS,
  AUTH_ENDPOINTS,
  AUTH_TOKEN_KEY,
  CATEGORY_TOTALS_ENDPOINTS,
  FEE_ENDPOINTS,
  FILTERING_ENDPOINTS,
  PAYMENT_ENDPOINTS,
  REPORT_ENDPOINTS,
  SUBS_ENDPOINTS,
  SUPPORT_ENDPOINTS,
  USER_ENDPOINTS,
} from "@/actions/constant/constant";

export const API_ENDPOINTS = {
  AUTH_ENDPOINTS,
  USER_ENDPOINTS,
  ADS_ENDPOINTS,
  CATEGORY_TOTALS_ENDPOINTS,
  ADVERTISEMENT_ENDPOINTS: {
    BASE: ADVERTISEMENT_ENDPOINTS.BASE,
    GET_ALL: ADVERTISEMENT_ENDPOINTS.GET_ALL,
    CREATE: ADVERTISEMENT_ENDPOINTS.CREATE,
    STATS: ADVERTISEMENT_ENDPOINTS.STATS,
    TODAY_STATS: ADVERTISEMENT_ENDPOINTS.TODAY_STATS,
  },
  FEE_ENDPOINTS: {
    GET_ACTIVE: FEE_ENDPOINTS.GET_ACTIVE,
    GET_ALL: FEE_ENDPOINTS.GET_ALL,
    CREATE: FEE_ENDPOINTS.CREATE,
    STATS: FEE_ENDPOINTS.STATS,
    CALCULATE: FEE_ENDPOINTS.CALCULATE,
    TOTAL_FEE: FEE_ENDPOINTS.TOTAL_FEE,
    GET_LOGS: (id: string) => `${BASE_API_URL}/api/Fee/${id}/logs`,
  },
  PAYMENT_ENDPOINTS,
  SUBS_ENDPOINTS,
  AGENCY_ENDPOINTS,
  REPORT_ENDPOINTS,
  FILTERING_ENDPOINTS,
  SUPPORT_ENDPOINTS,
  AUTH_TOKEN_KEY,
};

export default API_ENDPOINTS;
