export const login = {
  root:        "min-h-screen bg-gray-50 flex items-center justify-center px-4 py-12",
  card:        "w-full max-w-md bg-white rounded-2xl border border-gray-200 shadow-sm p-8",
  logo:        "flex items-center justify-center mb-6",
  title:       "text-2xl font-black text-gray-900 text-center mb-1",
  subtitle:    "text-sm text-gray-400 text-center mb-7",
  form:        "space-y-4",
  field:       "flex flex-col gap-1.5",
  label:       "block text-[10px] font-semibold text-gray-400 uppercase tracking-widest",
  pwWrap:      "relative",
  pwToggle:    "absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors",
  submit:      "w-full py-3 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-bold rounded-xl transition-colors text-sm touch-manipulation disabled:opacity-50 disabled:cursor-not-allowed",
  divider:     "flex items-center gap-3 my-4",
  dividerLine: "flex-1 border-t border-gray-200",
  dividerText: "text-xs text-gray-400 font-semibold",
  footer:      "text-sm text-gray-500 text-center mt-6",
  footerLink:  "text-blue-600 hover:text-blue-700 font-semibold transition-colors",
  terms:       "text-[11px] text-gray-400 text-center mt-4 leading-relaxed",
  errorBox:    "flex items-center gap-2 px-4 py-3 rounded-xl bg-red-50 border border-red-100 text-red-700 text-sm font-medium",
  successBox:  "flex items-center gap-2 px-4 py-3 rounded-xl bg-green-50 border border-green-100 text-green-700 text-sm font-medium",
  fieldError:  "text-red-500 text-xs font-medium mt-1",
} as const;

export const register = {
  root:        "min-h-screen bg-gray-50 flex items-center justify-center px-4 py-12",
  card:        "w-full max-w-md bg-white rounded-2xl border border-gray-200 shadow-sm p-8",
  logo:        "flex items-center justify-center mb-6",
  title:       "text-2xl font-black text-gray-900 text-center mb-1",
  subtitle:    "text-sm text-gray-400 text-center mb-7",
  form:        "space-y-4",
  grid2:       "grid grid-cols-2 gap-3",
  field:       "flex flex-col gap-1.5",
  label:       "block text-[10px] font-semibold text-gray-400 uppercase tracking-widest",
  pwWrap:      "relative",
  pwToggle:    "absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors",
  pwStrength:  "h-1 rounded-full mt-1.5 transition-all",
  pwWeak:      "bg-red-400 w-1/3",
  pwFair:      "bg-yellow-400 w-2/3",
  pwStrong:    "bg-green-500 w-full",
  submit:      "w-full py-3 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-bold rounded-xl transition-colors text-sm touch-manipulation disabled:opacity-50 disabled:cursor-not-allowed",
  footer:      "text-sm text-gray-500 text-center mt-6",
  footerLink:  "text-blue-600 hover:text-blue-700 font-semibold transition-colors",
  terms:       "text-[11px] text-gray-400 text-center mt-4 leading-relaxed",
  termsLink:   "text-blue-600 hover:underline",
  errorBox:    "flex items-center gap-2 px-4 py-3 rounded-xl bg-red-50 border border-red-100 text-red-700 text-sm font-medium",
  fieldError:  "text-red-500 text-xs font-medium mt-1",
} as const;

export const confirm = {
  root:        "min-h-screen bg-gray-50 flex items-center justify-center px-4 py-12",
  card:        "w-full max-w-md bg-white rounded-2xl border border-gray-200 shadow-sm p-8",
  icon:        "w-16 h-16 rounded-2xl bg-blue-50 flex items-center justify-center mx-auto mb-5",
  title:       "text-2xl font-black text-gray-900 text-center mb-1",
  subtitle:    "text-sm text-gray-400 text-center mb-7 leading-relaxed",
  codeWrap:    "flex items-center justify-center gap-2 my-6",
  codeInput:   "w-11 h-14 text-center text-xl font-black border border-gray-200 rounded-xl outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 transition-all bg-white",
  codeInputErr:"w-11 h-14 text-center text-xl font-black border border-red-400 rounded-xl outline-none focus:border-red-500 focus:ring-2 focus:ring-red-100 transition-all bg-white",
  submit:      "w-full py-3 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-bold rounded-xl transition-colors text-sm touch-manipulation disabled:opacity-50 disabled:cursor-not-allowed",
  resend:      "text-sm text-gray-500 text-center mt-4",
  resendBtn:   "text-blue-600 hover:text-blue-700 font-semibold transition-colors disabled:opacity-40 disabled:cursor-not-allowed",
  timer:       "text-xs text-gray-400 font-semibold",
  errorBox:    "flex items-center gap-2 px-4 py-3 rounded-xl bg-red-50 border border-red-100 text-red-700 text-sm font-medium",
  successBox:  "flex items-center gap-2 px-4 py-3 rounded-xl bg-green-50 border border-green-100 text-green-700 text-sm font-medium",
  backLink:    "flex items-center justify-center gap-1.5 text-sm text-gray-500 hover:text-blue-600 transition-colors mt-5 font-semibold",
} as const;
