export const dash = {
  page:        "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:       "max-w-7xl mx-auto space-y-6",
  header:      "flex items-center justify-between",
  title:       "text-2xl font-black text-gray-900",
  subtitle:    "text-sm text-gray-400 mt-0.5",
  card:        "bg-white rounded-2xl border border-gray-200 shadow-sm",
  cardHead:    "px-5 py-4 border-b border-gray-100 flex items-center justify-between",
  cardTitle:   "font-bold text-gray-900 text-base",
  cardBody:    "p-5",
  statCard:    "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  statValue:   "text-3xl font-black text-gray-900",
  statLabel:   "text-xs text-gray-400 font-semibold uppercase tracking-widest mt-1",
  statTrend:   "text-xs font-semibold text-green-600",
  grid4:       "grid grid-cols-2 lg:grid-cols-4 gap-4",
  grid3:       "grid grid-cols-1 lg:grid-cols-3 gap-5",
  grid2:       "grid grid-cols-1 lg:grid-cols-2 gap-5",
  table:       "w-full text-sm",
  tableHead:   "text-left text-[10px] font-black text-gray-400 uppercase tracking-widest border-b border-gray-100",
  th:          "px-4 py-3",
  td:          "px-4 py-3 border-b border-gray-50 last:border-0",
  trHover:     "hover:bg-gray-50 transition-colors",
  emptyState:  "flex flex-col items-center justify-center py-16 text-center",
  emptyIcon:   "w-14 h-14 rounded-2xl bg-gray-100 flex items-center justify-center mb-4 text-gray-400 text-2xl",
  emptyText:   "font-bold text-gray-700 text-base",
  emptySubtext:"text-sm text-gray-400 mt-1",
  pill:        "px-3 py-1 rounded-lg bg-gray-100 text-gray-600 text-xs font-semibold",
  pillActive:  "px-3 py-1 rounded-lg bg-blue-600 text-white text-xs font-semibold",
} as const;
