export const form = {
  root:        "space-y-5",
  section:     "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  sectionHead: "px-5 py-3.5 border-b border-gray-100 bg-gray-50",
  sectionBody: "p-5 space-y-4",
  grid2:       "grid grid-cols-1 sm:grid-cols-2 gap-4",
  grid3:       "grid grid-cols-1 sm:grid-cols-3 gap-4",
  field:       "flex flex-col gap-1.5",
  label:       "text-[10px] font-black text-gray-400 uppercase tracking-widest",
  required:    "text-red-400 ml-0.5",
  helper:      "text-[10px] text-gray-400 leading-relaxed",
  errorMsg:    "text-red-500 text-xs font-medium",
  input:       "w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm font-medium outline-none transition-all bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400",
  inputError:  "w-full px-3 py-2.5 border border-red-400 rounded-lg text-sm font-medium outline-none transition-all bg-white focus:border-red-500 focus:ring-2 focus:ring-red-100 placeholder:text-gray-400",
  select:      "w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm font-medium outline-none bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 appearance-none",
  textarea:    "w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm font-medium outline-none transition-all bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400 resize-none",
  checkbox:    "w-4 h-4 accent-blue-600 rounded cursor-pointer",
  radio:       "w-4 h-4 accent-blue-600 cursor-pointer",
  imageUpload: "flex flex-col items-center justify-center gap-2 border-2 border-dashed border-gray-200 rounded-2xl p-8 hover:border-blue-400 hover:bg-blue-50 transition-all cursor-pointer",
  actions:     "flex items-center justify-end gap-3 pt-4 border-t border-gray-100",
} as const;
