export const mgr = {
  page:       "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:      "max-w-7xl mx-auto",
  topbar:     "flex items-center justify-between mb-6 gap-4",
  title:      "text-2xl font-black text-gray-900",
  subtitle:   "text-sm text-gray-400 mt-0.5",
  search:     "flex items-center gap-2 px-3 py-2 border border-gray-200 rounded-xl bg-white text-sm w-full max-w-xs",
  searchInput:"flex-1 outline-none text-sm placeholder:text-gray-400",
  filters:    "flex items-center gap-2 flex-wrap",
  filterBtn:  "px-3 py-1.5 rounded-lg border border-gray-200 bg-white text-xs font-semibold text-gray-600 hover:border-blue-400 hover:text-blue-600 transition-colors",
  filterActive:"px-3 py-1.5 rounded-lg border border-blue-500 bg-blue-50 text-xs font-semibold text-blue-700",
  table:      "w-full bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  thead:      "border-b border-gray-100 bg-gray-50",
  th:         "text-left text-[10px] font-black text-gray-400 uppercase tracking-widest px-5 py-3",
  tr:         "border-b border-gray-50 last:border-0 hover:bg-gray-50 transition-colors",
  td:         "px-5 py-3.5 text-sm text-gray-700",
  tdMuted:    "px-5 py-3.5 text-sm text-gray-400",
  actions:    "flex items-center gap-1",
  actionEdit: "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-blue-50 text-gray-400 hover:text-blue-600 transition-colors",
  actionDel:  "inline-flex items-center justify-center w-8 h-8 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-600 transition-colors",
  avatar:     "w-8 h-8 rounded-full bg-blue-100 text-blue-700 font-bold text-xs flex items-center justify-center",
  userCell:   "flex items-center gap-3",
  userInfo:   "flex flex-col",
  userName:   "font-semibold text-gray-900 text-sm",
  userSub:    "text-xs text-gray-400",
  pagination: "flex items-center justify-between px-5 py-3.5 border-t border-gray-100",
  pageInfo:   "text-xs text-gray-400",
  pageNav:    "flex items-center gap-1",
  pageBtn:    "w-8 h-8 rounded-lg text-xs font-semibold text-gray-600 hover:bg-gray-100 transition-colors inline-flex items-center justify-center",
  pageBtnActive:"w-8 h-8 rounded-lg text-xs font-semibold bg-blue-600 text-white inline-flex items-center justify-center",
} as const;
