export const newad = {
  root:         "min-h-screen bg-gray-50",
  header:       "sticky top-0 z-20 bg-white border-b border-gray-100 px-4 py-3.5 flex items-center gap-3 shadow-sm",
  headerIcon:   "w-8 h-8 rounded-lg bg-blue-600 flex items-center justify-center flex-shrink-0",
  headerTitle:  "text-base font-black text-gray-900 leading-tight",
  headerSub:    "text-[11px] text-gray-400 font-medium leading-none mt-0.5",
  inner:        "max-w-4xl mx-auto px-3 sm:px-4 py-5 sm:py-7",
  catGrid:      "grid grid-cols-2 sm:grid-cols-3 gap-3",
  catCard:      "flex flex-col items-center justify-center gap-3 bg-white rounded-2xl border border-gray-200 px-3 py-6 shadow-sm active:scale-[0.97] active:bg-blue-50 active:border-blue-400 transition-all touch-manipulation select-none",
  catIcon:      "text-4xl leading-none",
  catLabel:     "font-bold text-gray-800 text-sm text-center leading-snug",
  desktopWrap:  "hidden lg:flex gap-5 items-start",
  desktopNav:   "w-56 flex-shrink-0 bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm",
  desktopNavHead:"px-4 py-3 border-b border-gray-100 bg-gray-50",
  desktopNavItem:"w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 last:border-b-0 text-sm font-semibold transition-colors touch-manipulation select-none",
  desktopNavActive:"bg-blue-600 text-white",
  desktopNavIdle: "text-gray-700 hover:bg-gray-50 active:bg-gray-100",
  optionPanel:  "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  optionHead:   "px-5 py-3.5 border-b border-gray-100 bg-gray-50",
  optionRow:    "w-full flex items-center justify-between gap-3 px-5 py-4 text-left hover:bg-gray-50 active:bg-gray-100 transition-colors touch-manipulation select-none",
  optionTitle:  "font-semibold text-gray-900 text-sm block",
  optionDesc:   "text-xs text-gray-400 block mt-0.5",
  placeholder:  "flex flex-col items-center justify-center py-28 text-center bg-white rounded-2xl border border-gray-200 shadow-sm",
  placeholderIcon:"w-16 h-16 rounded-2xl bg-blue-50 flex items-center justify-center mb-4",
  placeholderText:"font-bold text-gray-700 text-base mb-1",
  placeholderSub: "text-sm text-gray-400",
  sectionLabel: "text-[10px] font-black text-gray-400 uppercase tracking-widest mb-3 px-1",
  mobileWrap:   "lg:hidden",
} as const;
