export const notifications = {
  trigger:    "relative inline-flex items-center justify-center w-9 h-9 rounded-xl hover:bg-gray-100 text-gray-600 transition-colors touch-manipulation",
  badge:      "absolute -top-1 -right-1 w-4 h-4 rounded-full bg-blue-600 text-white text-[9px] font-black flex items-center justify-center",
  dropdown:   "absolute right-0 top-full mt-2 w-80 bg-white rounded-2xl border border-gray-200 shadow-lg z-50 overflow-hidden",
  header:     "px-4 py-3 border-b border-gray-100 flex items-center justify-between",
  title:      "font-bold text-gray-900 text-sm",
  markAll:    "text-xs font-semibold text-blue-600 hover:text-blue-700 transition-colors",
  list:       "max-h-[360px] overflow-y-auto",
  item:       "flex items-start gap-3 px-4 py-3.5 hover:bg-gray-50 transition-colors cursor-pointer border-b border-gray-50 last:border-0",
  itemUnread: "flex items-start gap-3 px-4 py-3.5 bg-blue-50 hover:bg-blue-100 transition-colors cursor-pointer border-b border-blue-50 last:border-0",
  iconBlue:   "w-9 h-9 rounded-xl bg-blue-100 text-blue-600 flex items-center justify-center flex-shrink-0 mt-0.5",
  iconGreen:  "w-9 h-9 rounded-xl bg-green-100 text-green-600 flex items-center justify-center flex-shrink-0 mt-0.5",
  iconRed:    "w-9 h-9 rounded-xl bg-red-100 text-red-600 flex items-center justify-center flex-shrink-0 mt-0.5",
  iconYellow: "w-9 h-9 rounded-xl bg-yellow-100 text-yellow-600 flex items-center justify-center flex-shrink-0 mt-0.5",
  body:       "flex-1 min-w-0",
  bodyTitle:  "text-sm font-semibold text-gray-900 leading-snug",
  bodyText:   "text-xs text-gray-400 mt-0.5 leading-relaxed",
  bodyTime:   "text-[10px] text-gray-400 mt-1",
  dot:        "w-2 h-2 rounded-full bg-blue-600 flex-shrink-0 mt-1.5",
  empty:      "flex flex-col items-center justify-center py-10 text-center px-4",
  emptyText:  "text-sm font-semibold text-gray-500 mt-2",
  footer:     "px-4 py-3 border-t border-gray-100 text-center",
  footerLink: "text-sm font-semibold text-blue-600 hover:text-blue-700 transition-colors",
} as const;
