export interface BoatItem {
  title: string;
  so: string;
  description: string;
  price: number;
  mainCategory: "Boats";
  category: string[];
  subcategory: string[];
  region: string;
  city: string;
  images: string[];
  type: string;
  boatModel: string;
  transmission: string;
  color: string;
  userId: string;
  maGaday: boolean;
  isPaid: boolean;
  id: string;
}
const USER_A = "user_74x01";
const USER_B = "user_89y02";
const USER_C = "user_56z03";

export const boatItems: BoatItem[] = [
  {
    id: "boat_001",
    title: "Commercial Fishing Dhow",
    so: "Doon kalluumaysi oo weyn",
    description:
      "A heavy-duty wooden dhow designed for deep-sea commercial fishing. Includes net hauling equipment.",
    price: 12000,
    mainCategory: "Boats",
    category: ["Boats for Sale"],
    subcategory: ["Doon kalluumaysi", "Doomo iib ah"],
    region: "Hamar",
    city: "Xamar Jajab",

    images: ["https://images.unsplash.com/photo-1520626639860-f0f34bd63189"],
    type: "Dhow",
    boatModel: "Traditional-2024",
    transmission: "Manual",
    color: "Brown",
    userId: USER_A,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_002",
    title: "Modern Fiberglass Boat",
    so: "Doon fiberglass ah oo casri ah",
    description:
      "Fast and stable fiberglass boat for coastal travel or fishing. Lightweight and easy to maintain.",
    price: 8500,
    mainCategory: "Boats",
    category: ["Boats for Sale"],
    subcategory: ["Doon yar", "Doomo iib ah"],
    region: "Jubada Hoose",
    city: "Kismaayo",

    images: [
      "https://plus.unsplash.com/premium_photo-1668723712079-7665d7a2d524",
    ],
    type: "Fiberglass",
    boatModel: "CoastMaster",
    transmission: "Outboard",
    color: "White/Blue",
    userId: USER_B,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_003",
    title: "Luxury Leisure Yacht",
    so: "Doon raaxo oo heer sare ah",
    description:
      "Luxury yacht for private events and leisure. Features two bedrooms and a sun deck.",
    price: 75000,
    mainCategory: "Boats",
    category: ["Boats for Sale"],
    subcategory: ["Doon raaxo", "Doomo iib ah"],
    region: "Hamar",
    city: "Cabdi Casiis",

    images: ["https://images.unsplash.com/photo-1517217004452-4ff260cb5598"],
    type: "Yacht",
    boatModel: "Elite-50",
    transmission: "Inboard",
    color: "White",
    userId: USER_A,
    maGaday: true,
    isPaid: true,
  },
  {
    id: "boat_004",
    title: "Daily Fishing Boat Rental",
    so: "Kiree doon kalluumaysi",
    description:
      "Professional fishing boat available for daily rental. Great for tourists.",
    price: 150,
    mainCategory: "Boats",
    category: ["Boats for Rent"],
    subcategory: ["Doomo kireysi ah", "Rental"],
    region: "Hamar",
    city: "Dharkeynley",

    images: [
      "https://plus.unsplash.com/premium_photo-1668723712079-7665d7a2d524",
    ],
    type: "Fishing Boat",
    boatModel: "Rental-Pro",
    transmission: "Outboard",
    color: "Blue",
    userId: USER_B,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_005",
    title: "Yamaha 200HP Outboard Engine",
    so: "Matoor Yamaha 200HP ah",
    description:
      "Brand new Yamaha V6 outboard engine. 200 horsepower, high fuel efficiency.",
    price: 15000,
    mainCategory: "Boats",
    category: ["Boat Engines for Sale"],
    subcategory: ["Matoorada doomo iib ah", "Outboard"],
    region: "Hamar",
    city: "Hodan",

    images: ["https://images.unsplash.com/photo-1520626639860-f0f34bd63189"],
    type: "Engine",
    boatModel: "Yamaha-V6",
    transmission: "N/A",
    color: "Gray",
    userId: USER_C,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_006",
    title: "Stainless Steel Propeller",
    so: "Shaanbaal bir ah (Propeller)",
    description:
      "High-grade stainless steel propeller for boat engines. Durable and rust-resistant.",
    price: 600,
    mainCategory: "Boats",
    category: ["Boat Parts"],
    subcategory: ["Qaybaha doomo", "Propeller"],
    region: "Jubada Hoose",
    city: "Kismaayo",

    images: ["https://images.unsplash.com/photo-1528154291023-a6525fabe5b4"],
    type: "Part",
    boatModel: "Universal-X",
    transmission: "N/A",
    color: "Silver",
    userId: USER_C,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_007",
    title: "Weekly Yacht Charter",
    so: "Kiree doon raaxo toddobaadkii",
    description: "Fully crewed luxury charter with catering services included.",
    price: 4500,
    mainCategory: "Boats",
    category: ["Boats for Rent"],
    subcategory: ["Doomo kireysi ah", "Charter"],
    region: "Woqooyi Galbeed",
    city: "Berbera",

    images: ["https://images.unsplash.com/photo-1517217004452-4ff260cb5598"],
    type: "Yacht",
    boatModel: "Charter-Luxe",
    transmission: "Inboard",
    color: "White",
    userId: USER_A,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_008",
    title: "Suzuki 115HP Boat Engine",
    so: "Matoor Suzuki 115HP ah",
    description:
      "Well-maintained used Suzuki outboard engine. Four-stroke, recently serviced.",
    price: 5500,
    mainCategory: "Boats",
    category: ["Boat Engines for Sale"],
    subcategory: ["Matoorada doomo iib ah", "Engine"],
    region: "Hamar",
    city: "Waaberi",

    images: ["https://images.unsplash.com/photo-1520626639860-f0f34bd63189"],
    type: "Engine",
    boatModel: "Suzuki-Four",
    transmission: "N/A",
    color: "Black",
    userId: USER_B,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_009",
    title: "Boat Navigation GPS System",
    so: "Qalabka GPS-ka ee doonta",
    description:
      "Marine GPS with pre-loaded maps of the Somali coast. Waterproof.",
    price: 750,
    mainCategory: "Boats",
    category: ["Boat Parts"],
    subcategory: ["Qaybaha doomo", "Electronics"],
    region: "Hamar",
    city: "Hodan",

    images: ["https://images.unsplash.com/photo-1528154291023-a6525fabe5b4"],
    type: "Part",
    boatModel: "Navi-Sea",
    transmission: "N/A",
    color: "Black",
    userId: USER_C,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_010",
    title: "Small Speedboat for Sale",
    so: "Doon yar oo dheeraysa",
    description:
      "Fast speedboat ideal for short trips or water sports. Fuel-efficient.",
    price: 11000,
    mainCategory: "Boats",
    category: ["Boats for Sale"],
    subcategory: ["Doomo iib ah", "Speedboat"],
    region: "Hamar",
    city: "Xamar Weyne",

    images: ["https://images.unsplash.com/photo-1528154291023-a6525fabe5b4"],
    type: "Speedboat",
    boatModel: "Swift-20",
    transmission: "Outboard",
    color: "Red",
    userId: USER_A,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_011",
    title: "Mercury Inboard Engine 300HP",
    so: "Matoor Mercury 300HP ah",
    description:
      "Powerful Mercury inboard engine for large cruisers. Low running hours.",
    price: 18000,
    mainCategory: "Boats",
    category: ["Boat Engines for Sale"],
    subcategory: ["Matoorada doomo iib ah", "Inboard"],
    region: "Shabeellaha Hoose",
    city: "Marka",

    images: ["https://images.unsplash.com/photo-1517217004452-4ff260cb5598"],
    type: "Engine",
    boatModel: "Mercury-V8",
    transmission: "Inboard",
    color: "Black",
    userId: USER_C,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_012",
    title: "Marine Battery 12V",
    so: "Baytariga doonta 12V",
    description:
      "Heavy-duty marine battery designed for starting engines in salty environments.",
    price: 250,
    mainCategory: "Boats",
    category: ["Boat Parts"],
    subcategory: ["Qaybaha doomo", "Electrical"],
    region: "Hamar",
    city: "Dharkeynley",

    images: ["https://images.unsplash.com/photo-1520626639860-f0f34bd63189"],
    type: "Part",
    boatModel: "Sea-Power",
    transmission: "N/A",
    color: "Black",
    userId: USER_B,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_013",
    title: "Rescue Boat for Rent",
    so: "Doon gurmad oo kireysi ah",
    description:
      "Inflatable rescue boat available for emergency services or standby.",
    price: 300,
    mainCategory: "Boats",
    category: ["Boats for Rent"],
    subcategory: ["Doomo kireysi ah", "Rescue"],
    region: "Jubada Hoose",
    city: "Kismaayo",

    images: ["https://images.unsplash.com/photo-1528154291023-a6525fabe5b4"],
    type: "Inflatable",
    boatModel: "Rescue-S",
    transmission: "Outboard",
    color: "Orange",
    userId: USER_A,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_014",
    title: "Traditional Sail Boat",
    so: "Doon shiraac ah oo iib ah",
    description: "Authentic Somali wooden sailboat built by local craftsmen.",
    price: 3500,
    mainCategory: "Boats",
    category: ["Boats for Sale"],
    subcategory: ["Doomo iib ah", "Traditional"],
    region: "Awdal",
    city: "Zaylac",

    images: ["https://images.unsplash.com/photo-1517217004452-4ff260cb5598"],
    type: "Sailboat",
    boatModel: "Trad-Heritage",
    transmission: "Manual/Wind",
    color: "Natural Wood",
    userId: USER_B,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_015",
    title: "Boat Steering Wheel System",
    so: "Qalabka isteerinka doonta",
    description:
      "Complete hydraulic steering system for motorboats. Includes wheel and pump.",
    price: 1100,
    mainCategory: "Boats",
    category: ["Boat Parts"],
    subcategory: ["Qaybaha doomo", "Steering"],
    region: "Hamar",
    city: "Xamar Weyne",

    images: ["https://images.unsplash.com/photo-1520626639860-f0f34bd63189"],
    type: "Part",
    boatModel: "Hydro-Turn",
    transmission: "N/A",
    color: "Silver/Black",
    userId: USER_C,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_016",
    title: "Cargo Transport Boat",
    so: "Doon weyn oo xamuul ah",
    description:
      "Large vessel designed for transporting goods with high cargo hold capacity.",
    price: 45000,
    mainCategory: "Boats",
    category: ["Boats for Sale"],
    subcategory: ["Doomo iib ah", "Cargo"],
    region: "Woqooyi Galbeed",
    city: "Berbera",

    images: [
      "https://plus.unsplash.com/premium_photo-1668723712079-7665d7a2d524",
    ],
    type: "Cargo",
    boatModel: "Transport-Heavy",
    transmission: "Inboard",
    color: "Gray",
    userId: USER_A,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_017",
    title: "Yamaha 40HP Engine (Used)",
    so: "Matoor Yamaha 40HP ah oo la isticmaalay",
    description:
      "Reliable 40HP Yamaha engine. Recently overhauled and ready for use.",
    price: 2800,
    mainCategory: "Boats",
    category: ["Boat Engines for Sale"],
    subcategory: ["Matoorada doomo iib ah", "Used Engine"],
    region: "Hamar",
    city: "Cabdi Casiis",

    images: ["https://images.unsplash.com/photo-1520626639860-f0f34bd63189"],
    type: "Engine",
    boatModel: "Enduro-40",
    transmission: "N/A",
    color: "Blue",
    userId: USER_B,
    maGaday: true,
    isPaid: true,
  },
  {
    id: "boat_018",
    title: "Diving Boat for Rent",
    so: "Kiree doon quusidda ah",
    description:
      "Specially equipped boat for diving excursions with oxygen tank racks.",
    price: 500,
    mainCategory: "Boats",
    category: ["Boats for Rent"],
    subcategory: ["Doomo kireysi ah", "Diving"],
    region: "Hamar",
    city: "Shangaani",

    images: ["https://images.unsplash.com/photo-1528154291023-a6525fabe5b4"],
    type: "Diving Boat",
    boatModel: "Deep-Sea-10",
    transmission: "Outboard",
    color: "White",
    userId: USER_C,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_019",
    title: "High-Quality Boat Anchor",
    so: "Baroor (Anchor) doonta ah",
    description:
      "Heavy-duty galvanised steel anchor suitable for sandy and rocky floors.",
    price: 350,
    mainCategory: "Boats",
    category: ["Boat Parts"],
    subcategory: ["Qaybaha doomo", "Hardware"],
    region: "Shabeellaha Hoose",
    city: "Marka",

    images: ["https://images.unsplash.com/photo-1517217004452-4ff260cb5598"],
    type: "Part",
    boatModel: "Anchor-HD",
    transmission: "N/A",
    color: "Dark Gray",
    userId: USER_A,
    maGaday: false,
    isPaid: true,
  },
  {
    id: "boat_020",
    title: "Evinrude 150HP Engine",
    so: "Matoor Evinrude 150HP ah",
    description:
      "High-performance outboard engine, fuel injected for speed and efficiency.",
    price: 9500,
    mainCategory: "Boats",
    category: ["Boat Engines for Sale"],
    subcategory: ["Matoorada doomo iib ah", "Outboard"],
    region: "Hamar",
    city: "Waaberi",
    images: ["https://images.unsplash.com/photo-1520626639860-f0f34bd63189"],
    type: "Engine",
    boatModel: "E-Tec-150",
    transmission: "N/A",
    color: "White/Gray",
    userId: USER_B,
    maGaday: false,
    isPaid: true,
  },
];
