export const carItems = [
  {
    id: "car_001",
    title: "Toyota Camry 2020 - Low Mileage",
    so: "Toyota Camry 2020 - Mileej dhiman",
    description:
      "Clean title, well maintained, single owner. Excellent condition with all service records.",
    price: 18500,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Sedan iib ah"],
    brand: "Toyota",
    vehicleModel: "Camry",
    year: 2020,
    mileage: 45000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "White",
    region: "Hamar",
    city: "Hodan",
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_003",
    title: "BMW 3 Series 2020 - Luxury",
    so: "BMW 3 Series 2020 - Luxuri",
    description: "Premium package, excellent condition, low mileage.",
    price: 32000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Sedan iib ah"],
    brand: "BMW",
    vehicleModel: "3 Series",
    year: 2020,
    mileage: 28000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Blue",
    region: "Woqooyi Galbeed",
    city: "Hargeysa",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_004",
    title: "Mercedes C-Class 2021",
    so: "Mercedes C-Class 2021",
    description: "Executive luxury sedan, AMG line, excellent condition.",
    price: 42000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Sedan iib ah"],
    brand: "Mercedes-Benz",
    vehicleModel: "C-Class",
    year: 2021,
    mileage: 20000,
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "Gray",
    region: "Nugaal",
    city: "Garoowe",

    images: ["https://images.unsplash.com/photo-1555212697-194d092e3b8f"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_005",
    title: "Toyota Land Cruiser 2021",
    so: "Toyota Land Cruiser 2021",
    description: "V8 engine, 4WD, premium package, excellent for Somali roads.",
    price: 85000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["SUV/4x4 iib ah"],
    brand: "Toyota",
    vehicleModel: "Land Cruiser",
    year: 2021,
    mileage: 25000,
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "Gray",
    region: "Bari",
    city: "Qardho",

    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_006",
    title: "Nissan Patrol 2020 - V8",
    so: "Nissan Patrol 2020 - V8",
    description: "Leather seats, navigation system, excellent condition.",
    price: 75000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["SUV/4x4 iib ah"],
    brand: "Nissan",
    vehicleModel: "Patrol",
    year: 2020,
    mileage: 30000,
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "Silver",
    region: "Woqooyi Galbeed",
    city: "Hargeysa",

    images: ["https://images.unsplash.com/photo-1553440569-bcc63803a83d"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_007",
    title: "Mitsubishi Pajero Sport 2020",
    so: "Mitsubishi Pajero Sport 2020",
    description: "7-seater, 4WD, excellent family SUV.",
    price: 38000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["SUV/4x4 iib ah"],
    brand: "Mitsubishi",
    vehicleModel: "Pajero Sport",
    year: 2020,
    mileage: 30000,
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "Gray",
    region: "Hamar",
    city: "Xamar Jajab",

    images: ["https://images.unsplash.com/photo-1544636331-e26879cd4d9b"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_008",
    title: "Hyundai Tucson 2022 - Like New",
    so: "Hyundai Tucson 2022 - Sida cusub",
    description: "Only 10,000km, still under warranty, perfect condition.",
    price: 28000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["SUV/4x4 iib ah"],
    brand: "Hyundai",
    vehicleModel: "Tucson",
    year: 2022,
    mileage: 10000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Silver",
    region: "Hamar",
    city: "Bondhere",

    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_009",
    title: "Toyota Yaris 2018 - Economical",
    so: "Toyota Yaris 2018 - Qiimo jaban",
    description:
      "Great fuel efficiency, perfect for city driving, well maintained.",
    price: 12000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Hatchback iib ah"],
    brand: "Toyota",
    vehicleModel: "Yaris",
    year: 2018,
    mileage: 60000,
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Red",
    region: "Hamar",
    city: "Waaberi",

    images: ["https://images.unsplash.com/photo-1549927744-7c0fcfd3b8c1"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_010",
    title: "Volkswagen Golf 2019",
    so: "Volkswagen Golf 2019",
    description: "German engineering, fuel efficient, reliable hatchback.",
    price: 19000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Hatchback iib ah"],
    brand: "Volkswagen",
    vehicleModel: "Golf",
    year: 2019,
    mileage: 40000,
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Blue",
    region: "Woqooyi Galbeed",
    city: "Berbera",

    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_011",
    title: "Ford Mustang Convertible 2018",
    so: "Ford Mustang Convertible 2018",
    description: "American muscle car, V8 engine, automatic transmission.",
    price: 35000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Convertible iib ah"],
    brand: "Ford",
    vehicleModel: "Mustang",
    year: 2018,
    mileage: 28000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Red",
    region: "Woqooyi Galbeed",
    city: "Gebilay",

    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_012",
    title: "BMW 4 Series Convertible 2020",
    so: "BMW 4 Series Convertible 2020",
    description: "Luxury convertible, excellent condition, low mileage.",
    price: 45000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Convertible iib ah"],
    brand: "BMW",
    vehicleModel: "4 Series",
    year: 2020,
    mileage: 22000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Black",
    region: "Hamar",
    city: "Cabdi Casiis",

    images: ["https://images.unsplash.com/photo-1494976388531-d1058494cdd8"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_013",
    title: "Toyota Hiace Minivan 2020",
    so: "Toyota Hiace Minivan 2020",
    description: "15-seater, perfect for transport business, well maintained.",
    price: 32000,
    mainCategory: "Gawaari",
    category: ["Gawaari iib ah"],
    subcategory: ["Minivan iib ah"],
    brand: "Toyota",
    vehicleModel: "Hiace",
    year: 2020,
    mileage: 60000,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "White",
    region: "Hamar",
    city: "Hodan",

    images: ["https://images.unsplash.com/photo-1553440569-bcc63803a83d"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_014",
    title: "Toyota Corolla 2022 - Monthly Lease",
    so: "Toyota Corolla 2022 - Kiro bil ah",
    description:
      "Available for long-term lease, includes maintenance and insurance.",
    price: 800,
    mainCategory: "Gawaari",
    category: ["Gawaari kirayn"],
    subcategory: ["Kiree Sedan"],

    brand: "Toyota",
    vehicleModel: "Corolla",
    year: 2022,
    mileage: 15000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "White",
    region: "Hamar",
    city: "Waaberi",

    images: ["https://images.unsplash.com/photo-1544636331-e26879cd4d9b"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_015",
    title: "Nissan Altima 2019 - Lease",
    so: "Nissan Altima 2019 - Kiro",
    description: "Family sedan available for monthly lease, good condition.",
    price: 600,
    mainCategory: "Gawaari",
    category: ["Gawaari kirayn"],
    subcategory: ["Kiree Sedan"],

    brand: "Nissan",
    vehicleModel: "Altima",
    year: 2019,
    mileage: 45000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Silver",
    region: "Woqooyi Galbeed",
    city: "Hargeysa",

    images: ["https://images.unsplash.com/photo-1514316454349-750a7fd3da3a"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_016",
    title: "Toyota Prado - Daily/Weekly Lease",
    so: "Toyota Prado - Kiro maalinle/Usbuucle",
    description:
      "Available for daily/weekly/monthly lease. Driver available upon request.",
    price: 150,
    mainCategory: "Gawaari",
    category: ["Gawaari kirayn"],
    subcategory: ["Kiree SUV/4x4"],

    brand: "Toyota",
    vehicleModel: "Prado",
    year: 2019,
    mileage: 55000,
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "Black",
    region: "Woqooyi Galbeed",
    city: "Hargeysa",

    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_017",
    title: "BMW X5 - Monthly Luxury Lease",
    so: "BMW X5 - Kiro bil oo luxuri ah",
    description: "Monthly lease with full insurance coverage, premium SUV.",
    price: 1200,
    mainCategory: "Gawaari",
    category: ["Gawaari kirayn"],
    subcategory: ["Kiree SUV/4x4"],

    brand: "BMW",
    vehicleModel: "X5",
    year: 2020,
    mileage: 35000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Black",
    region: "Hamar",
    city: "Cabdi Casiis",

    images: ["https://images.unsplash.com/photo-1555212697-194d092e3b8f"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_018",
    title: "Toyota Coaster Bus - Monthly Lease",
    so: "Toyota Coaster Bas - Kiro bil ah",
    description:
      "30-seater bus available for lease, perfect for transport business.",
    price: 2000,
    mainCategory: "Gawaari",
    category: ["Gawaari kirayn"],
    subcategory: ["Kiree Bas/Gaari weyn"],

    brand: "Toyota",
    vehicleModel: "Coaster",
    year: 2018,
    mileage: 80000,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "White",
    region: "Hamar",
    city: "Yaaqshiid",

    images: ["https://images.unsplash.com/photo-1544636331-e26879cd4d9b"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_019",
    title: "Toyota Hilux - Monthly Truck Lease",
    so: "Toyota Hilux - Kiro bil oo truck ah",
    description: "Available for construction or transport business lease.",
    price: 1000,
    mainCategory: "Gawaari",
    category: ["Gawaari kirayn"],
    subcategory: ["Kiree Gaari Xamuul"],

    brand: "Toyota",
    vehicleModel: "Hilux",
    year: 2020,
    mileage: 45000,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "White",
    region: "Bari",
    city: "Boosaaso",

    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_020",
    title: "Toyota Hilux Double Cab 2021",
    so: "Toyota Hilux Double Cab 2021",
    description: "Diesel, 4x4, excellent for business and transport.",
    price: 35000,
    mainCategory: "Gawaari",
    category: ["Baabuur xamuul"],
    subcategory: ["Pickup Truck iib ah"],
    brand: "Toyota",
    vehicleModel: "Hilux",
    year: 2021,
    mileage: 40000,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "White",
    region: "Bari",
    city: "Boosaaso",

    images: ["https://images.unsplash.com/photo-1553440569-bcc63803a83d"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_021",
    title: "Isuzu D-Max - Work Truck",
    so: "Isuzu D-Max - Truck shaqo",
    description: "Perfect for construction and hauling, well maintained.",
    price: 32000,
    mainCategory: "Gawaari",
    category: ["Baabuur xamuul"],
    subcategory: ["Pickup Truck iib ah"],
    brand: "Isuzu",
    vehicleModel: "D-Max",
    year: 2020,
    mileage: 45000,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "White",
    region: "Nugaal",
    city: "Garoowe",

    images: ["https://images.unsplash.com/photo-1549927744-7c0fcfd3b8c1"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_022",
    title: "Volvo Heavy Truck - 2017",
    so: "Volvo Heavy Truck - 2017",
    description: "For cargo transport, well maintained, ready for work.",
    price: 55000,
    mainCategory: "Gawaari",
    category: ["Baabuur xamuul"],
    subcategory: ["Heavy Truck iib ah"],
    brand: "Volvo",
    vehicleModel: "FH16",
    year: 2017,
    mileage: 250000,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "Red",
    region: "Bari",
    city: "Boosaaso",

    images: ["https://images.unsplash.com/photo-1494976388531-d1058494cdd8"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_023",
    title: "Flatbed Truck - For Construction",
    so: "Flatbed Truck - Dhismo loogu talagalay",
    description:
      "Heavy duty flatbed truck, perfect for construction materials.",
    price: 45000,
    mainCategory: "Gawaari",
    category: ["Baabuur xamuul"],
    subcategory: ["Truck Furan/Cisterno iib ah"],
    brand: "Mercedes",
    vehicleModel: "Actros",
    year: 2019,
    mileage: 180000,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "White",
    region: "Hamar",
    city: "Hawl Wadaag",

    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_024",
    title: "Tesla Model 3 - Electric Car",
    so: "Tesla Model 3 - Gaari koronto",
    description:
      "Long range, autopilot, premium interior, excellent condition.",
    price: 45000,
    mainCategory: "Gawaari",
    category: ["Gawaari Koronto"],
    subcategory: ["Electric Sedan iib ah"],
    brand: "Tesla",
    vehicleModel: "Model 3",
    year: 2021,
    mileage: 20000,
    transmission: "Automatic",
    fuelType: "Electric",
    color: "Blue",
    region: "Hamar",
    city: "Cabdi Casiis",

    images: ["https://images.unsplash.com/photo-1514316454349-750a7fd3da3a"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_025",
    title: "Tesla Model X - Electric SUV",
    so: "Tesla Model X - SUV koronto",
    description: "Falcon wing doors, long range, premium electric SUV.",
    price: 85000,
    mainCategory: "Gawaari",
    category: ["Gawaari Koronto"],
    subcategory: ["Electric SUV iib ah"],
    brand: "Tesla",
    vehicleModel: "Model X",
    year: 2020,
    mileage: 25000,
    transmission: "Automatic",
    fuelType: "Electric",
    color: "White",
    region: "Woqooyi Galbeed",
    city: "Hargeysa",

    images: ["https://images.unsplash.com/photo-1555212697-194d092e3b8f"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_026",
    title: "Boat Trailer - Heavy Duty",
    so: "Boat Trailer - Culus",
    description: "Can carry boats up to 25 feet, good condition, ready to use.",
    price: 2500,
    mainCategory: "Gawaari",
    category: ["rimoor"],
    subcategory: ["Boat Trailer iib ah"],
    brand: "Custom",
    vehicleModel: "Boat Trailer",
    year: 2018,
    mileage: 0,
    transmission: "N/A",
    fuelType: "N/A",
    color: "Black",
    region: "Bari",
    city: "Boosaaso",

    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_027",
    title: "Heavy Duty Trailer - For Construction",
    so: "Trailer Culus - Dhismo loogu talagalay",
    description: "Large capacity trailer for construction equipment transport.",
    price: 5000,
    mainCategory: "Gawaari",
    category: ["rimoor"],
    subcategory: ["Rimoor Xamuul Culus iib ah"],
    brand: "Custom",
    vehicleModel: "Heavy Trailer",
    year: 2020,
    mileage: 0,
    transmission: "N/A",
    fuelType: "N/A",
    color: "Yellow",
    region: "Hamar",
    city: "Hawl Wadaag",

    images: ["https://images.unsplash.com/photo-1549927744-7c0fcfd3b8c1"],
    maGaday: true,
    isPaid: true,
  },
  {
    id: "car_028",
    title: "Toyota 2JZ Engine - Good Condition",
    so: "Toyota 2JZ Engine - Xaalad wanaagsan",
    description:
      "Toyota 2JZ engine in good working condition, perfect for swap.",
    price: 2500,
    mainCategory: "Gawaari",
    category: ["Qaybaha gawaarida"],
    subcategory: ["Matoorrada"],
    brand: "Toyota",
    vehicleModel: "2JZ-GTE",
    year: 2015,
    mileage: 0,
    transmission: "N/A",
    fuelType: "Petrol",
    color: "Metal",
    region: "Hamar",
    city: "Xamar Weyne",

    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537"],
    maGaday: false,
    isPaid: true,
  },
  {
    id: "car_029",
    title: "Alloy Rims Set - 18 inch",
    so: "Setka Rim-ka Alloy - 18 inch",
    description: "Set of 4 alloy rims for SUV/Truck, excellent condition.",
    price: 800,
    mainCategory: "Gawaari",
    category: ["Qaybaha gawaarida"],
    subcategory: ["Tires iyo Rimms"],
    brand: "BBS",
    vehicleModel: "Alloy Rims",
    year: 2022,
    mileage: 0,
    transmission: "N/A",
    fuelType: "N/A",
    color: "Silver",
    region: "Woqooyi Galbeed",
    city: "Hargeysa",

    images: ["https://images.unsplash.com/photo-1494976388531-d1058494cdd8"],
    maGaday: true,
    isPaid: true,
  },
];
