export const equipmentItems = [
  // 1. TRACTOR FOR SALE: NEW TRACTOR (1/3)
  {
    title: "John Deere JD100 New Utility Tractor",
    so: "Cagaf cagaf cusub (John Deere)",
    mainCategory: "Equipment",
    description:
      "Powerful tractor for large-scale farming. Brand new condition.",
    price: 12000.0,
    category: ["Tractor for Sale"],
    subcategory: ["New Tractor"],
    type: "Utility",
    make: "John Deere",
    traktortModel: "JD100",
    year: 2024,
    condition: "New",
    hours: 5,
    enginePower: "150HP",
    fuelType: "Diesel",
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hamarweyne",
    subDistrict: "Shibis",
    images: [
      "https://images.unsplash.com/photo-1614977645540-7abd88ba8e56?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dHJhY3RvcnxlbnwwfHwwfHx8MA%3D%3D",
    ],
    maGaday: true,
  },
  // 2. TRACTOR FOR SALE: USED TRACTOR (1/3)
  {
    title: "Kubota KX200 Used Farm Tractor",
    so: "Cagaf cagaf la isticmaalay (Kubota)",
    mainCategory: "Equipment",
    description: "Efficient tractor for small farms. Well-maintained.",
    price: 10000.0,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "Kubota",
    traktortModel: "KX200",
    year: 2019,
    condition: "Used - Good",
    hours: 150,
    enginePower: "130HP",
    fuelType: "Diesel",
    region: "Somaliland",
    city: "Hargeysa",
    district: "Kaaraan",
    subDistrict: "Hargeisa Central",
    images: [
      "https://plus.unsplash.com/premium_photo-1664301163726-78773dc77bfd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhY3RvcnxlbnwwfHwwfHx8MA%3D%3D",
    ],
    maGaday: false,
  },
  // 3. FARM TOOLS: PLOW/TILLAGE EQUIPMENT (1/3)
  {
    title: "Heavy-Duty Disc Plow for Sale",
    so: "Qalabka wax lagu qoto (Disc Plow)",
    mainCategory: "Equipment",
    description:
      "Reliable disc plow for deep soil tillage. Attaches to 170HP+ tractors.",
    price: 3500.0,
    category: ["Farm Tools"],
    subcategory: ["Plow/Tillage Equipment"],
    type: "Implement",
    make: "Case IH",
    traktortModel: "CIH-DP10",
    year: 2021,
    condition: "Used - Like New",
    hours: 50,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Puntland",
    city: "Garowe",
    district: "Garowe District",
    subDistrict: "Garowe Central",
    images: [
      "https://plus.unsplash.com/premium_photo-1661809297697-ba16de6e3646?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dHJhY3RvcnxlbnwwfHwwfHx8MA%3D%3D",
    ],
    maGaday: true,
  },
  // 4. FERTILIZER SPREADER: MOUNTED SPREADER (1/3)
  {
    title: "Mounted Fertilizer Spreader (800L)",
    so: "Faafiyaha Mounted (800L)",
    mainCategory: "Equipment",
    description:
      "Tractor-mounted fertilizer spreader, 800-liter capacity. Excellent for medium farms.",
    price: 1500.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Mounted Spreader"],
    type: "Implement",
    make: "Amazone",
    traktortModel: "ZA-M 800",
    year: 2018,
    condition: "Used - Good",
    hours: 200,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Galmudug",
    city: "Galkayo",
    district: "Galkayo South",
    subDistrict: "Galkayo East",
    images: [
      "https://images.unsplash.com/photo-1629807473015-41699c4471b5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 5. GRAIN HARVESTER: SELF-PROPELLED HARVESTER (1/3)
  {
    title: "Self-Propelled Wheat Harvester",
    so: "Harvester iswada (Qamadi)",
    mainCategory: "Equipment",
    description:
      "Large capacity harvester for grain and wheat. Well-maintained engine.",
    price: 35000.0,
    category: ["Grain Harvester"],
    subcategory: ["Self-Propelled Harvester"],
    type: "Self-Propelled",
    make: "Claas",
    traktortModel: "Lexion 500",
    year: 2015,
    condition: "Used - Fair",
    hours: 500,
    enginePower: "350HP",
    fuelType: "Diesel",
    region: "Hiiraan",
    city: "Beledweyne",
    district: "Beledweyne District",
    subDistrict: "Beledweyne Central",
    images: [
      "https://images.unsplash.com/photo-1568680870491-590cd4e224ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 6. FARM TOOLS: SEEDING EQUIPMENT (1/3)
  {
    title: "Precision Row Planter (Used)",
    so: "Qalabka abuuritaanka (Precision Planter)",
    mainCategory: "Equipment",
    description: "6-row planter for corn/sorghum. Highly accurate seeding.",
    price: 5500.0,
    category: ["Farm Tools"],
    subcategory: ["Seeding Equipment"],
    type: "Implement",
    make: "Kinze",
    traktortModel: "K-6R",
    year: 2017,
    condition: "Used - Good",
    hours: 120,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Bari",
    city: "Bosaso",
    district: "Bosaso District",
    subDistrict: "Bosaso Port",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 7. FARM TOOLS: HARVESTING EQUIPMENT (1/3)
  {
    title: "Small Sickle Bar Mower (Hay/Fodder)",
    so: "Qalabka goosashada (Mower)",
    mainCategory: "Equipment",
    description:
      "Used sickle bar mower for cutting hay and fodder. Easy to attach.",
    price: 1300.0,
    category: ["Farm Tools"],
    subcategory: ["Harvesting Equipment"],
    type: "Implement",
    make: "BCS",
    traktortModel: "BCS-728",
    year: 2019,
    condition: "Used - Good",
    hours: 80,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Bay",
    city: "Baidoa",
    district: "Baidoa District",
    subDistrict: "Baidoa East",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 8. TRACTOR FOR SALE: USED TRACTOR (2/3)
  {
    title: "Case IH CIH300 Used Tractor",
    so: "Cagaf cagaf la isticmaalay (Case IH)",
    mainCategory: "Equipment",
    description: "Reliable medium-sized tractor for general farm work.",
    price: 18000.0,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "Case IH",
    traktortModel: "CIH300",
    year: 2018,
    condition: "Used - Good",
    hours: 500,
    enginePower: "180HP",
    fuelType: "Diesel",
    region: "Lower Shabelle",
    city: "Merca",
    district: "Merca District",
    subDistrict: "Merca Port",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 9. FARM TOOLS: PLOW/TILLAGE EQUIPMENT (2/3)
  {
    title: "Heavy Tandem Disc Harrow",
    so: "Qalabka wax lagu qoto (Disc Harrow)",
    mainCategory: "Equipment",
    description:
      "Tandem disc harrow for secondary tillage and preparing seedbeds.",
    price: 4500.0,
    category: ["Farm Tools"],
    subcategory: ["Plow/Tillage Equipment"],
    type: "Implement",
    make: "Maschio",
    traktortModel: "Gaspardo",
    year: 2022,
    condition: "Used - Like New",
    hours: 90,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Mudug",
    city: "Galkayo",
    district: "Galkayo North",
    subDistrict: "Galkayo West",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 10. FERTILIZER SPREADER: TOWED SPREADER (1/3)
  {
    title: "High-Capacity Trailed Spreader",
    so: "Faafiyaha Towed (Capacity sare)",
    mainCategory: "Equipment",
    description:
      "Very large trailed spreader, ideal for high acreage operations.",
    price: 9000.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Towed Spreader"],
    type: "Implement",
    make: "Krone",
    traktortModel: "TS 5000",
    year: 2023,
    condition: "New",
    hours: 10,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Gedo",
    city: "Luuq",
    district: "Luuq District",
    subDistrict: "Luuq Central",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 11. GRAIN HARVESTER: PULL-TYPE HARVESTER (1/3)
  {
    title: "Pull-Type Rice Harvester",
    so: "Harvester jiidan (Bariis)",
    mainCategory: "Equipment",
    description:
      "Tractor-drawn harvester specifically designed for rice fields.",
    price: 11000.0,
    category: ["Grain Harvester"],
    subcategory: ["Pull-Type Harvester"],
    type: "Attachment",
    make: "Massey Ferguson",
    traktortModel: "MF-R100",
    year: 2018,
    condition: "Used - Good",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Banaadir",
    city: "Muqdisho",
    district: "Waberi",
    subDistrict: "Afarta Irdoodka",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 12. FARM TOOLS: HARVESTING EQUIPMENT (2/3)
  {
    title: "Used Potato Harvester",
    so: "Qalabka goosashada (Baradho)",
    mainCategory: "Equipment",
    description:
      "Single-row potato harvester, good for small to medium fields.",
    price: 3800.0,
    category: ["Farm Tools"],
    subcategory: ["Harvesting Equipment"],
    type: "Implement",
    make: "Grimme",
    traktortModel: "GR-1R",
    year: 2017,
    condition: "Used - Fair",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Somaliland",
    city: "Boorame",
    district: "Baki",
    subDistrict: "Wadajir",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 13. TRACTOR FOR SALE: NEW TRACTOR (2/3)
  {
    title: "New Holland NH180 New Tractor",
    so: "Cagaf cagaf cusub (New Holland)",
    mainCategory: "Equipment",
    description: "New and powerful tractor, excellent fuel efficiency.",
    price: 16000.0,
    category: ["Tractor for Sale"],
    subcategory: ["New Tractor"],
    type: "Utility",
    make: "New Holland",
    traktortModel: "NH180",
    year: 2024,
    condition: "New",
    hours: 5,
    enginePower: "180HP",
    fuelType: "Diesel",
    region: "Hiiraan",
    city: "Beledweyne",
    district: "Beledweyne District",
    subDistrict: "Beledweyne Central",
    images: [
      "https://images.unsplash.com/photo-1568680870491-590cd4e224ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 14. FARM TOOLS: PLOW/TILLAGE EQUIPMENT (3/3)
  {
    title: "Heavy Moldboard Plow",
    so: "Qalabka wax lagu qoto (Moldboard Plow)",
    mainCategory: "Equipment",
    description:
      "Sturdy moldboard plow for primary tillage, deep soil turning.",
    price: 3200.0,
    category: ["Farm Tools"],
    subcategory: ["Plow/Tillage Equipment"],
    type: "Attachment",
    make: "Kuhn",
    traktortModel: "Kuhn-MP5",
    year: 2021,
    condition: "Used - Good",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Galmudug",
    city: "Galkayo",
    district: "Galkayo South",
    subDistrict: "Galkayo East",
    images: [
      "https://images.unsplash.com/photo-1629807473015-41699c4471b5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 15. FERTILIZER SPREADER: MOUNTED SPREADER (2/3)
  {
    title: "Medium Mounted Spreader (1200L)",
    so: "Faafiyaha Mounted (Dhexdhexaad)",
    mainCategory: "Equipment",
    description: "Mounted fertilizer spreader, large working width.",
    price: 1800.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Mounted Spreader"],
    type: "Implement",
    make: "Vicon",
    traktortModel: "PS1200",
    year: 2020,
    condition: "Used - Good",
    hours: 100,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Gedo",
    city: "Luuq",
    district: "Luuq District",
    subDistrict: "Luuq Central",
    images: [
      "https://images.unsplash.com/photo-1568680870491-590cd4e224ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 16. GRAIN HARVESTER: SELF-PROPELLED HARVESTER (2/3)
  {
    title: "Large Self-Propelled Harvester (Barley)",
    so: "Harvester iswada (Shaciir)",
    mainCategory: "Equipment",
    description:
      "Used Combine Harvester for barley and small grains. High capacity.",
    price: 32000.0,
    category: ["Grain Harvester"],
    subcategory: ["Self-Propelled Harvester"],
    type: "Self-Propelled",
    make: "Claas",
    traktortModel: "Lexion 600",
    year: 2014,
    condition: "Used - Fair",
    hours: 900,
    enginePower: "450HP",
    fuelType: "Diesel",
    region: "Banaadir",
    city: "Muqdisho",
    district: "Dharkenley",
    subDistrict: "Garasbaaley",
    images: [
      "https://images.unsplash.com/photo-1614977645540-7abd88ba8e56?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dHJhY3RvcnxlbnwwfHwwfHx8MA%3D%3D",
    ],
    maGaday: false,
  },
  // 17. FARM TOOLS: SEEDING EQUIPMENT (2/3)
  {
    title: "Air Seeder for Grains",
    so: "Qalabka abuuritaanka (Air Seeder)",
    mainCategory: "Equipment",
    description: "Air seeder for uniform distribution of grain seeds.",
    price: 7500.0,
    category: ["Farm Tools"],
    subcategory: ["Seeding Equipment"],
    type: "Implement",
    make: "Horsch",
    traktortModel: "Horsch-AS",
    year: 2022,
    condition: "Used - Good",
    hours: 150,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Somaliland",
    city: "Hargeysa",
    district: "Maxamed Mooge",
    subDistrict: "New Hargeisa",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 18. FERTILIZER SPREADER: TOWED SPREADER (2/3)
  {
    title: "Small Trailed Spreader (2 Tons)",
    so: "Faafiyaha Towed (Yar)",
    mainCategory: "Equipment",
    description: "Trailed spreader for small to medium scale farms.",
    price: 4500.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Towed Spreader"],
    type: "Implement",
    make: "Kuhn",
    traktortModel: "Kuhn-TS20",
    year: 2019,
    condition: "Used - Good",
    hours: 150,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Puntland",
    city: "Garowe",
    district: "Garowe District",
    subDistrict: "Garowe Central",
    images: [
      "https://images.unsplash.com/photo-1568680870491-590cd4e224ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 19. TRACTOR FOR SALE: NEW TRACTOR (3/3)
  {
    title: "Fendt F250 High-End Tractor",
    so: "Cagaf cagaf cusub (Fendt)",
    mainCategory: "Equipment",
    description:
      "Premium new tractor with advanced GPS technology and comfort.",
    price: 30000.0,
    category: ["Tractor for Sale"],
    subcategory: ["New Tractor"],
    type: "High-End",
    make: "Fendt",
    traktortModel: "F250",
    year: 2024,
    condition: "New",
    hours: 8,
    enginePower: "250HP",
    fuelType: "Diesel",
    region: "Galmudug",
    city: "Cadaado",
    district: "Cadaado District",
    subDistrict: "Cadaado North",
    images: [
      "https://images.unsplash.com/photo-1629807473015-41699c4471b5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 20. TRACTOR FOR SALE: USED TRACTOR (3/3)
  {
    title: "John Deere JD150 Used Tractor",
    so: "Cagaf cagaf la isticmaalay (John Deere)",
    mainCategory: "Equipment",
    description:
      "Reliable older John Deere model, well maintained for its age.",
    price: 8500.0,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "John Deere",
    traktortModel: "JD150",
    year: 2010,
    condition: "Used - Fair",
    hours: 2500,
    enginePower: "100HP",
    fuelType: "Diesel",
    region: "Gedo",
    city: "Kismayo",
    district: "Kismayo District",
    subDistrict: "Kismayo Port",
    images: [
      "https://images.unsplash.com/photo-1568680870491-590cd4e224ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 21. FARM TOOLS: SEEDING EQUIPMENT (3/3)
  {
    title: "Small Plot Seeder",
    so: "Qalabka abuuritaanka (Plot Seeder)",
    mainCategory: "Equipment",
    description: "Manual/small-scale seeder for small vegetable plots.",
    price: 350.0,
    category: ["Farm Tools"],
    subcategory: ["Seeding Equipment"],
    type: "Manual",
    make: "EarthWay",
    traktortModel: "EW-1001B",
    year: 2023,
    condition: "New",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hamarweyne",
    subDistrict: "Shibis",
    images: [
      "https://images.unsplash.com/photo-1619719826894-89d6c4fd5739?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 22. GRAIN HARVESTER: SELF-PROPELLED HARVESTER (3/3)
  {
    title: "Medium Self-Propelled Harvester (Sorghum)",
    so: "Harvester iswada (Digir/Qasab)",
    mainCategory: "Equipment",
    description:
      "Combine Harvester suitable for sorghum and small grains. Fully operational.",
    price: 25000.0,
    category: ["Grain Harvester"],
    subcategory: ["Self-Propelled Harvester"],
    type: "Self-Propelled",
    make: "New Holland",
    traktortModel: "NH-CX5",
    year: 2016,
    condition: "Used - Good",
    hours: 750,
    enginePower: "300HP",
    fuelType: "Diesel",
    region: "Somaliland",
    city: "Berbera",
    district: "Berbera District",
    subDistrict: "Berbera Port",
    images: [
      "https://images.unsplash.com/photo-1568680870491-590cd4e224ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
  // 23. FERTILIZER SPREADER: MOUNTED SPREADER (3/3)
  {
    title: "New Mounted Spreader (600L)",
    so: "Faafiyaha Mounted (Cusub)",
    mainCategory: "Equipment",
    description: "Brand new mounted spreader, never used.",
    price: 1300.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Mounted Spreader"],
    type: "Implement",
    make: "Amazone",
    traktortModel: "ZA-M 600",
    year: 2024,
    condition: "New",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "Puntland",
    city: "Bossaso",
    district: "Bosaso District",
    subDistrict: "Bosaso Central",
    images: [
      "https://images.unsplash.com/photo-1629807473015-41699c4471b5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: true,
  },
  // 24. FARM TOOLS: HARVESTING EQUIPMENT (3/3)
  {
    title: "Hand-Held Grass Cutter",
    so: "Qalabka goosashada (Grass Cutter)",
    mainCategory: "Equipment",
    description:
      "Motorized grass cutter for trimming and small harvesting tasks.",
    price: 250.0,
    category: ["Farm Tools"],
    subcategory: ["Harvesting Equipment"],
    type: "Hand-Held",
    make: "Husqvarna",
    traktortModel: "H-GCX",
    year: 2023,
    condition: "New",
    hours: 5,
    enginePower: "5HP",
    fuelType: "Petrol",
    region: "Galmudug",
    city: "Hobyo",
    district: "Hobyo District",
    subDistrict: "Hobyo Central",
    images: [
      "https://images.unsplash.com/photo-1629807473015-41699c4471b5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYWN0b3J8ZW58MHx8MHx8fDA%3D%3D",
    ],
    maGaday: false,
  },
];
