export interface EquipmentItem {
  id: string;
  title: string;
  so: string;
  mainCategory: "Equipment";
  description: string;
  price: number;
  category: string[];
  subcategory: string[];
  type: string;
  make: string;
  traktortModel: string;
  year: number;
  condition: string;
  hours: number;
  enginePower: string;
  fuelType: string;
  region: string;
  city: string;
  images: string[];
  maGaday: boolean;
  isPaid: boolean;
}
export const equipmentItems = [
  {
    title: "John Deere JD100 New Utility Tractor",
    so: "Cagaf cagaf cusub (John Deere)",
    mainCategory: "Equipment",
    description:
      "Powerful tractor for large-scale farming. Brand new condition.",
    price: 12000.0,
    category: ["Tractor for Sale"],
    subcategory: ["New Tractor"],
    type: "Utility",
    make: "John Deere",
    traktortModel: "JD100",
    year: 2024,
    condition: "New",
    hours: 5,
    enginePower: "150HP",
    fuelType: "Diesel",
    region: "hamar",
    city: "hamar",

    images: ["https://images.unsplash.com/photo-1614977645540-7abd88ba8e56"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Kubota KX200 Used Farm Tractor",
    so: "Cagaf cagaf la isticmaalay (Kubota)",
    mainCategory: "Equipment",
    description: "Efficient tractor for small farms. Well-maintained.",
    price: 10000.0,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "Kubota",
    traktortModel: "KX200",
    year: 2019,
    condition: "Used - Good",
    hours: 150,
    enginePower: "130HP",
    fuelType: "Diesel",
    region: "wqdl",
    city: "hargeysa",

    images: [
      "https://plus.unsplash.com/premium_photo-1664301163726-78773dc77bfd",
    ],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Heavy-Duty Disc Plow for Sale",
    so: "Qalabka wax lagu qoto (Disc Plow)",
    mainCategory: "Equipment",
    description:
      "Reliable disc plow for deep soil tillage. Attaches to 170HP+ tractors.",
    price: 3500.0,
    category: ["Farm Tools"],
    subcategory: ["Plow/Tillage Equipment"],
    type: "Implement",
    make: "Case IH",
    traktortModel: "CIH-DP10",
    year: 2021,
    condition: "Used - Like New",
    hours: 50,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bari",
    city: "garowe",

    images: [
      "https://plus.unsplash.com/premium_photo-1661809297697-ba16de6e3646",
    ],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Mounted Fertilizer Spreader (800L)",
    so: "Faafiyaha Mounted (800L)",
    mainCategory: "Equipment",
    description:
      "Tractor-mounted fertilizer spreader, 800-liter capacity. Excellent for medium farms.",
    price: 1500.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Mounted Spreader"],
    type: "Implement",
    make: "Amazone",
    traktortModel: "ZA-M 800",
    year: 2018,
    condition: "Used - Good",
    hours: 200,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "mudug",
    city: "galkayo",

    images: ["https://images.unsplash.com/photo-1629807473015-41699c4471b5"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Self-Propelled Wheat Harvester",
    so: "Harvester iswada (Qamadi)",
    mainCategory: "Equipment",
    description:
      "Large capacity harvester for grain and wheat. Well-maintained engine.",
    price: 35000.0,
    category: ["Grain Harvester"],
    subcategory: ["Self-Propelled Harvester"],
    type: "Self-Propelled",
    make: "Claas",
    traktortModel: "Lexion 500",
    year: 2015,
    condition: "Used - Fair",
    hours: 500,
    enginePower: "350HP",
    fuelType: "Diesel",
    region: "hiiraan",
    city: "beledweyne",

    images: ["https://images.unsplash.com/photo-1568680870491-590cd4e224ab"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Precision Row Planter (Used)",
    so: "Qalabka abuuritaanka (Precision Planter)",
    mainCategory: "Equipment",
    description: "6-row planter for corn/sorghum. Highly accurate seeding.",
    price: 5500.0,
    category: ["Farm Tools"],
    subcategory: ["Seeding Equipment"],
    type: "Implement",
    make: "Kinze",
    traktortModel: "K-6R",
    year: 2017,
    condition: "Used - Good",
    hours: 120,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bari",
    city: "bosaso",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Small Sickle Bar Mower (Hay/Fodder)",
    so: "Qalabka goosashada (Mower)",
    mainCategory: "Equipment",
    description:
      "Used sickle bar mower for cutting hay and fodder. Easy to attach.",
    price: 1300.0,
    category: ["Farm Tools"],
    subcategory: ["Harvesting Equipment"],
    type: "Implement",
    make: "BCS",
    traktortModel: "BCS-728",
    year: 2019,
    condition: "Used - Good",
    hours: 80,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bay",
    city: "baidoa",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Case IH CIH300 Used Tractor",
    so: "Cagaf cagaf la isticmaalay (Case IH)",
    mainCategory: "Equipment",
    description: "Reliable medium-sized tractor for general farm work.",
    price: 18000.0,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "Case IH",
    traktortModel: "CIH300",
    year: 2018,
    condition: "Used - Good",
    hours: 500,
    enginePower: "180HP",
    fuelType: "Diesel",
    region: "shabeellaha-hoose",
    city: "merca",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Heavy Tandem Disc Harrow",
    so: "Qalabka wax lagu qoto (Disc Harrow)",
    mainCategory: "Equipment",
    description:
      "Tandem disc harrow for secondary tillage and preparing seedbeds.",
    price: 4500.0,
    category: ["Farm Tools"],
    subcategory: ["Plow/Tillage Equipment"],
    type: "Implement",
    make: "Maschio",
    traktortModel: "Gaspardo",
    year: 2022,
    condition: "Used - Like New",
    hours: 90,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "mudug",
    city: "galkayo",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "High-Capacity Trailed Spreader",
    so: "Faafiyaha Towed (Capacity sare)",
    mainCategory: "Equipment",
    description:
      "Very large trailed spreader, ideal for high acreage operations.",
    price: 9000.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Towed Spreader"],
    type: "Implement",
    make: "Krone",
    traktortModel: "TS 5000",
    year: 2023,
    condition: "New",
    hours: 10,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "gedo",
    city: "luuq",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Pull-Type Rice Harvester",
    so: "Harvester jiidan (Bariis)",
    mainCategory: "Equipment",
    description:
      "Tractor-drawn harvester specifically designed for rice fields.",
    price: 11000.0,
    category: ["Grain Harvester"],
    subcategory: ["Pull-Type Harvester"],
    type: "Attachment",
    make: "Massey Ferguson",
    traktortModel: "MF-R100",
    year: 2018,
    condition: "Used - Good",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "hamar",
    city: "hamar",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Used Potato Harvester",
    so: "Qalabka goosashada (Baradho)",
    mainCategory: "Equipment",
    description:
      "Single-row potato harvester, good for small to medium fields.",
    price: 3800.0,
    category: ["Farm Tools"],
    subcategory: ["Harvesting Equipment"],
    type: "Implement",
    make: "Grimme",
    traktortModel: "GR-1R",
    year: 2017,
    condition: "Used - Fair",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "awdal",
    city: "boorame",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "New Holland NH180 New Tractor",
    so: "Cagaf cagaf cusub (New Holland)",
    mainCategory: "Equipment",
    description: "New and powerful tractor, excellent fuel efficiency.",
    price: 16000.0,
    category: ["Tractor for Sale"],
    subcategory: ["New Tractor"],
    type: "Utility",
    make: "New Holland",
    traktortModel: "NH180",
    year: 2024,
    condition: "New",
    hours: 5,
    enginePower: "180HP",
    fuelType: "Diesel",
    region: "hiiraan",
    city: "beledweyne",

    images: ["https://images.unsplash.com/photo-1568680870491-590cd4e224ab"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Heavy Moldboard Plow",
    so: "Qalabka wax lagu qoto (Moldboard Plow)",
    mainCategory: "Equipment",
    description:
      "Sturdy moldboard plow for primary tillage, deep soil turning.",
    price: 3200.0,
    category: ["Farm Tools"],
    subcategory: ["Plow/Tillage Equipment"],
    type: "Attachment",
    make: "Kuhn",
    traktortModel: "Kuhn-MP5",
    year: 2021,
    condition: "Used - Good",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "mudug",
    city: "galkayo",

    images: ["https://images.unsplash.com/photo-1629807473015-41699c4471b5"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Medium Mounted Spreader (1200L)",
    so: "Faafiyaha Mounted (Dhexdhexaad)",
    mainCategory: "Equipment",
    description: "Mounted fertilizer spreader, large working width.",
    price: 1800.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Mounted Spreader"],
    type: "Implement",
    make: "Vicon",
    traktortModel: "PS1200",
    year: 2020,
    condition: "Used - Good",
    hours: 100,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "gedo",
    city: "luuq",

    images: ["https://images.unsplash.com/photo-1568680870491-590cd4e224ab"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Large Self-Propelled Harvester (Barley)",
    so: "Harvester iswada (Shaciir)",
    mainCategory: "Equipment",
    description:
      "Used Combine Harvester for barley and small grains. High capacity.",
    price: 32000.0,
    category: ["Grain Harvester"],
    subcategory: ["Self-Propelled Harvester"],
    type: "Self-Propelled",
    make: "Claas",
    traktortModel: "Lexion 600",
    year: 2014,
    condition: "Used - Fair",
    hours: 900,
    enginePower: "450HP",
    fuelType: "Diesel",
    region: "hamar",
    city: "hamar",

    images: ["https://images.unsplash.com/photo-1614977645540-7abd88ba8e56"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Air Seeder for Grains",
    so: "Qalabka abuuritaanka (Air Seeder)",
    mainCategory: "Equipment",
    description: "Air seeder for uniform distribution of grain seeds.",
    price: 7500.0,
    category: ["Farm Tools"],
    subcategory: ["Seeding Equipment"],
    type: "Implement",
    make: "Horsch",
    traktortModel: "Horsch-AS",
    year: 2022,
    condition: "Used - Good",
    hours: 150,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "wqdl",
    city: "hargeysa",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Small Trailed Spreader (2 Tons)",
    so: "Faafiyaha Towed (Yar)",
    mainCategory: "Equipment",
    description: "Trailed spreader for small to medium scale farms.",
    price: 4500.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Towed Spreader"],
    type: "Implement",
    make: "Kuhn",
    traktortModel: "Kuhn-TS20",
    year: 2019,
    condition: "Used - Good",
    hours: 150,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bari",
    city: "garowe",

    images: ["https://images.unsplo-1568680870491-590cd4e224ab"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Fendt F250 High-End Tractor",
    so: "Cagaf cagaf cusub (Fendt)",
    mainCategory: "Equipment",
    description:
      "Premium new tractor with advanced GPS technology and comfort.",
    price: 30000.0,
    category: ["Tractor for Sale"],
    subcategory: ["New Tractor"],
    type: "High-End",
    make: "Fendt",
    traktortModel: "F250",
    year: 2024,
    condition: "New",
    hours: 8,
    enginePower: "250HP",
    fuelType: "Diesel",
    region: "galmudug",
    city: "cadaado",
    images: ["https://images.unsplash.com/photo-1629807473015-41699c4471b5"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "John Deere JD150 Used Tractor",
    so: "Cagaf cagaf la isticmaalay (John Deere)",
    mainCategory: "Equipment",
    description:
      "Reliable older John Deere model, well maintained for its age.",
    price: 8500.0,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "John Deere",
    traktortModel: "JD150",
    year: 2010,
    condition: "Used - Fair",
    hours: 2500,
    enginePower: "100HP",
    fuelType: "Diesel",
    region: "jubadda-hoose",
    city: "kismaayo",

    images: ["https://images.unsplash.com/photo-1568680870491-590cd4e224ab"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "Small Plot Seeder",
    so: "Qalabka abuuritaanka (Plot Seeder)",
    mainCategory: "Equipment",
    description: "Manual/small-scale seeder for small vegetable plots.",
    price: 350.0,
    category: ["Farm Tools"],
    subcategory: ["Seeding Equipment"],
    type: "Manual",
    make: "EarthWay",
    traktortModel: "EW-1001B",
    year: 2023,
    condition: "New",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "hamar",
    city: "hamar",

    images: ["https://images.unsplash.com/photo-1619719826894-89d6c4fd5739"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Medium Self-Propelled Harvester (Sorghum)",
    so: "Harvester iswada (Digir/Qasab)",
    mainCategory: "Equipment",
    description:
      "Combine Harvester suitable for sorghum and small grains. Fully operational.",
    price: 25000.0,
    category: ["Grain Harvester"],
    subcategory: ["Self-Propelled Harvester"],
    type: "Self-Propelled",
    make: "New Holland",
    traktortModel: "NH-CX5",
    year: 2016,
    condition: "Used - Good",
    hours: 750,
    enginePower: "300HP",
    fuelType: "Diesel",
    region: "berbera",
    city: "berbera",

    images: ["https://images.unsplash.com/photo-1568680870491-590cd4e224ab"],
    maGaday: false,
    isPaid: true,
  },
  {
    title: "New Mounted Spreader (600L)",
    so: "Faafiyaha Mounted (Cusub)",
    mainCategory: "Equipment",
    description: "Brand new mounted spreader, never used.",
    price: 1300.0,
    category: ["Fertilizer Spreader"],
    subcategory: ["Mounted Spreader"],
    type: "Implement",
    make: "Amazone",
    traktortModel: "ZA-M 600",
    year: 2024,
    condition: "New",
    hours: 0,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bari",
    city: "bossaso",

    images: ["https://images.unsplash.com/photo-1629807473015-41699c4471b5"],
    maGaday: true,
    isPaid: true,
  },
  {
    title: "Hand-Held Grass Cutter",
    so: "Qalabka goosashada (Grass Cutter)",
    mainCategory: "Equipment",
    description:
      "Motorized grass cutter for trimming and small harvesting tasks.",
    price: 250.0,
    category: ["Farm Tools"],
    subcategory: ["Harvesting Equipment"],
    type: "Hand-Held",
    make: "Husqvarna",
    traktortModel: "H-GCX",
    year: 2023,
    condition: "New",
    hours: 5,
    enginePower: "5HP",
    fuelType: "Petrol",
    region: "galmudug",
    city: "hobyo",

    images: ["https://images.unsplash.com/photo-1629807473015-41699c4471b5"],
    maGaday: false,
    isPaid: true,
  },
];
