import { v4 as uuidv4 } from "uuid";
import { USER_A, USER_B } from "./seederConstants.ts";

export interface EquipmentItem {
  id: string;
  title: string;
  mainCategory: "Equipment";
  description: string;
  price: number;
  category: string[];
  subcategory: string[];
  type: string;
  make: string;
  farmequipmentModel: string;
  year: number;
  condition: string;
  hours: number;
  enginePower: string;
  fuelType: string;
  region: string;
  city: string;
  images: string[];
  maGaday: boolean;
  isPaid: boolean;
  isBasic30: boolean;
  isStandard60: boolean;
  isPremium90: boolean;
  userId: string;
}

export const equipmentItems: EquipmentItem[] = [
  {
    id: uuidv4(),
    title: "John Deere JD100 New Utility Tractor",
    mainCategory: "Equipment",
    description:
      "Powerful new utility tractor designed for large-scale farming operations. The John Deere JD100 features a 150HP diesel engine with exceptional fuel efficiency and low emissions. This tractor comes equipped with modern hydraulic systems, comfortable air-conditioned cabin, GPS guidance compatible display, and a 12-speed transmission for optimal performance. The 5-hour use only means it's practically brand new with full warranty remaining. Perfect for plowing, planting, hauling, and other heavy-duty agricultural tasks. Includes front-end loader attachment and three-point hitch for versatile implement connection. A reliable workhorse that will serve your farm for decades with proper maintenance.",
    price: 12000,
    category: ["Tractor for Sale"],
    subcategory: ["New Tractor"],
    type: "Utility",
    make: "John Deere",
    farmequipmentModel: "JD100",
    year: 2024,
    condition: "New",
    hours: 5,
    enginePower: "150HP",
    fuelType: "Diesel",
    region: "hamar",
    city: "hamar",
    images: [""],
    maGaday: true,
    isPaid: true,
    isBasic30: false,
    isStandard60: true,
    isPremium90: false,
    userId: USER_A,
  },
  {
    id: uuidv4(),
    title: "Kubota KX200 Used Farm Tractor",
    mainCategory: "Equipment",
    description:
      "Efficient and reliable used tractor perfect for small to medium-sized farms. The Kubota KX200 delivers 130HP from its durable diesel engine while maintaining excellent fuel economy. This well-maintained machine has only 150 hours of operation and has been serviced regularly at authorized Kubota dealerships. Features include power steering, comfortable seating, easy-to-use controls, and compatibility with most standard farm implements. The tractor has been used primarily for light field work and hay operations. Recent service includes oil change, filter replacements, and new tires. A great value for farmers seeking quality equipment at an affordable price point.",
    price: 10000,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "Kubota",
    farmequipmentModel: "KX200",
    year: 2019,
    condition: "Used - Good",
    hours: 150,
    enginePower: "130HP",
    fuelType: "Diesel",
    region: "wqdl",
    city: "hargeysa",
    images: [],
    maGaday: false,
    isPaid: true,
    isBasic30: true,
    isStandard60: false,
    isPremium90: false,
    userId: USER_B,
  },
  {
    id: uuidv4(),
    title: "Heavy-Duty Disc Plow for Sale",
    mainCategory: "Equipment",
    description:
      "Reliable heavy-duty disc plow designed for deep soil tillage and primary cultivation. This implement attaches easily to tractors with 170HP or more and features 10 hardened steel discs that cut through tough soil conditions. The plow has been used for only 50 hours and remains in like-new condition. It effectively breaks up compacted soil, buries crop residue, and prepares seedbeds for planting. The discs are adjustable for different soil types and depths up to 12 inches. Built with high-strength steel construction for durability and longevity. Includes safety chains and lighting for road transport. An essential tool for serious farming operations.",
    price: 3500,
    category: ["Farm Tools"],
    subcategory: ["Plow/Tillage Equipment"],
    type: "Implement",
    make: "Case IH",
    farmequipmentModel: "CIH-DP10",
    year: 2021,
    condition: "Used - Like New",
    hours: 50,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bari",
    city: "garowe",
    images: [],
    maGaday: true,
    isPaid: true,
    isBasic30: false,
    isStandard60: false,
    isPremium90: true,
    userId: USER_A,
  },
  {
    id: uuidv4(),
    title: "Mounted Fertilizer Spreader (800L)",
    mainCategory: "Equipment",
    description:
      "Tractor-mounted fertilizer spreader with 800-liter capacity, excellent for medium-sized farms. This Amazone ZA-M 800 features adjustable spreading patterns for precise application of granular fertilizers, lime, or seeds. The spreader has been used for 200 hours and remains in good working condition. It offers a working width of up to 24 meters, reducing the number of passes needed across fields. The stainless steel hopper resists corrosion and is easy to clean. Includes a calibration kit for accurate application rates and a PTO-driven spreading mechanism. A cost-effective solution for improving crop yields through proper nutrient management.",
    price: 1500,
    category: ["Fertilizer Spreader"],
    subcategory: ["Mounted Spreader"],
    type: "Implement",
    make: "Amazone",
    farmequipmentModel: "ZA-M 800",
    year: 2018,
    condition: "Used - Good",
    hours: 200,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "mudug",
    city: "galkayo",
    images: [""],
    maGaday: false,
    isPaid: true,
    isBasic30: true,
    isStandard60: false,
    isPremium90: false,
    userId: USER_B,
  },
  {
    id: uuidv4(),
    title: "Self-Propelled Wheat Harvester",
    mainCategory: "Equipment",
    description:
      "Large capacity self-propelled harvester specifically designed for wheat and grain crops. The Claas Lexion 500 features a 350HP diesel engine, 25-foot cutting header, and advanced threshing technology that minimizes grain loss. With 500 operating hours, this machine has been well-maintained and is in fair condition. It includes a comfortable cabin with air conditioning, grain tank capacity of 300 bushels, and unloading speed of 3 bushels per second. The harvester is equipped with GPS guidance and yield monitoring systems. Perfect for large-scale grain operations looking to increase harvesting efficiency and reduce labor costs.",
    price: 35000,
    category: ["Grain Harvester"],
    subcategory: ["Self-Propelled Harvester"],
    type: "Self-Propelled",
    make: "Claas",
    farmequipmentModel: "Lexion 500",
    year: 2015,
    condition: "Used - Fair",
    hours: 500,
    enginePower: "350HP",
    fuelType: "Diesel",
    region: "hiiraan",
    city: "beledweyne",
    images: [""],
    maGaday: true,
    isPaid: true,
    isBasic30: false,
    isStandard60: true,
    isPremium90: false,
    userId: USER_A,
  },
  {
    id: uuidv4(),
    title: "Precision Row Planter (Used)",
    mainCategory: "Equipment",
    description:
      "6-row precision planter for corn, sorghum, and other row crops with highly accurate seeding capabilities. The Kinze K-6R features individual row units with vacuum seed meters that ensure precise seed spacing and depth control. With 120 hours of use, this planter is in good condition and ready for the next planting season. It offers adjustable row spacing from 30-36 inches and includes liquid fertilizer injection capability. The planter monitors seed delivery and provides real-time feedback to the tractor cabin. Compatible with most tractors equipped with standard hydraulics. Increase your crop yields through proper plant population management with this professional-grade planter.",
    price: 5500,
    category: ["Farm Tools"],
    subcategory: ["Seeding Equipment"],
    type: "Implement",
    make: "Kinze",
    farmequipmentModel: "K-6R",
    year: 2017,
    condition: "Used - Good",
    hours: 120,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bari",
    city: "bosaso",
    images: [""],
    maGaday: false,
    isPaid: true,
    isBasic30: false,
    isStandard60: false,
    isPremium90: true,
    userId: USER_B,
  },
  {
    id: uuidv4(),
    title: "Small Sickle Bar Mower (Hay/Fodder)",
    mainCategory: "Equipment",
    description:
      "Used sickle bar mower for cutting hay, fodder, and field grasses. This BCS-728 mower is easy to attach to small tractors or two-wheel tractors and features a 5-foot cutting width. The reciprocating sickle blade provides a clean cut close to the ground, maximizing forage yield. With 80 hours of use, this mower remains in good condition with sharp blades and smooth operation. Ideal for small-scale hay production or maintaining pasture lands. The mower is lightweight yet durable, making it easy to transport and store. Includes spare blades and maintenance manual. A practical tool for livestock farmers needing quality forage.",
    price: 1300,
    category: ["Farm Tools"],
    subcategory: ["Harvesting Equipment"],
    type: "Implement",
    make: "BCS",
    farmequipmentModel: "BCS-728",
    year: 2019,
    condition: "Used - Good",
    hours: 80,
    enginePower: "N/A",
    fuelType: "N/A",
    region: "bay",
    city: "baidoa",
    images: [""],
    maGaday: true,
    isPaid: true,
    isBasic30: true,
    isStandard60: false,
    isPremium90: false,
    userId: USER_A,
  },
  {
    id: uuidv4(),
    title: "Case IH CIH300 Used Tractor",
    mainCategory: "Equipment",
    description:
      "Reliable medium-sized used tractor for general farm work and daily operations. The Case IH CIH300 delivers 180HP from its fuel-efficient diesel engine and has accumulated 500 hours of use. This well-maintained tractor features power shift transmission, comfortable operator station, and excellent visibility. Recent maintenance includes new filters, fluids, and a full inspection by certified technicians. The tractor is compatible with a wide range of implements including loaders, mowers, planters, and tillage equipment. It's been used primarily for hay production and light field work. A versatile machine that offers great value for mixed farming operations seeking proven reliability at a reasonable price point.",
    price: 18000,
    category: ["Tractor for Sale"],
    subcategory: ["Used Tractor"],
    type: "Utility",
    make: "Case IH",
    farmequipmentModel: "CIH300",
    year: 2018,
    condition: "Used - Good",
    hours: 500,
    enginePower: "180HP",
    fuelType: "Diesel",
    region: "shabeellaha-hoose",
    city: "merca",
    images: [""],
    maGaday: false,
    isPaid: true,
    isBasic30: false,
    isStandard60: true,
    isPremium90: false,
    userId: USER_B,
  },
];
