export interface JobSeedData {
  title: string;
  description: string;
  category: string[];
  subcategory: string[];
  salary: number;
  mainCategory: string;
  region: string;
  city: string;
  employmentType: string;
  experienceLevel: string;
  userId: string;
  isPaid: boolean;
  expiryDate: Date;
}

export const jobsData: JobSeedData[] = [
  {
    title: "Senior React Developer",
    description:
      "Looking for an expert in React.js and TypeScript to build modern web interfaces.",
    category: ["IT"],
    subcategory: ["Software"],
    salary: 90000,
    mainCategory: "Jobs",
    region: "Banaadir",
    city: "Mogadishu",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Node.js Backend Engineer",
    description:
      "Build scalable APIs and microservices using Node.js, Express, and PostgreSQL.",
    category: ["IT"],
    subcategory: ["Software"],
    salary: 85000,
    mainCategory: "Jobs",
    region: "Bari",
    city: "Bosaso",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "DevOps Specialist",
    description:
      "Manage AWS infrastructure, Docker containers, and CI/CD automation pipelines.",
    category: ["IT"],
    subcategory: ["Infrastructure"],
    salary: 95000,
    mainCategory: "Jobs",
    region: "Nugaal",
    city: "Garowe",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Cybersecurity Analyst",
    description:
      "Monitor network security, perform audits, and implement threat protection protocols.",
    category: ["IT"],
    subcategory: ["Security"],
    salary: 82000,
    mainCategory: "Jobs",
    region: "Hiraan",
    city: "Beledweyne",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Cloud Architect",
    description:
      "Design and implement cloud-native solutions with a focus on high availability.",
    category: ["IT"],
    subcategory: ["Infrastructure"],
    salary: 110000,
    mainCategory: "Jobs",
    region: "Galgaduud",
    city: "Dhusamareb",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Data Scientist",
    description:
      "Analyze large datasets to extract actionable insights and build predictive models.",
    category: ["IT"],
    subcategory: ["Data Science"],
    salary: 105000,
    mainCategory: "Jobs",
    region: "Mudug",
    city: "Galkacyo",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "QA Automation Engineer",
    description:
      "Develop automated testing scripts for web and mobile applications.",
    category: ["IT"],
    subcategory: ["Testing"],
    salary: 78000,
    mainCategory: "Jobs",
    region: "Bay",
    city: "Baidoa",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Mobile App Developer",
    description:
      "Create cross-platform mobile apps using React Native or Flutter.",
    category: ["IT"],
    subcategory: ["Software"],
    salary: 88000,
    mainCategory: "Jobs",
    region: "Lower Juba",
    city: "Kismayo",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "UI/UX Designer",
    description:
      "Design intuitive user journeys and high-fidelity wireframes in Figma.",
    category: ["IT"],
    subcategory: ["Design"],
    salary: 72000,
    mainCategory: "Jobs",
    region: "Togdheer",
    city: "Burao",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Database Administrator",
    description:
      "Optimize database performance, backups, and security management.",
    category: ["IT"],
    subcategory: ["Data Management"],
    salary: 84000,
    mainCategory: "Jobs",
    region: "Awdal",
    city: "Borama",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Air Traffic Controller",
    description:
      "Direct aircraft movement on the ground and through controlled airspace.",
    category: ["Airport"],
    subcategory: ["Aviation"],
    salary: 110000,
    mainCategory: "Jobs",
    region: "Banaadir",
    city: "Mogadishu",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Airport Operations Manager",
    description:
      "Oversee daily airport activities, safety compliance, and staff management.",
    category: ["Airport"],
    subcategory: ["Management"],
    salary: 85000,
    mainCategory: "Jobs",
    region: "Bari",
    city: "Bosaso",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Ground Handling Lead",
    description:
      "Supervise ground crews for efficient aircraft turnaround and passenger service.",
    category: ["Airport"],
    subcategory: ["Operations"],
    salary: 45000,
    mainCategory: "Jobs",
    region: "Lower Juba",
    city: "Kismayo",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Cargo Supervisor",
    description:
      "Manage logistics for air freight, including loading and documentation.",
    category: ["Airport"],
    subcategory: ["Logistics"],
    salary: 52000,
    mainCategory: "Jobs",
    region: "Nugaal",
    city: "Garowe",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Aviation Security Officer",
    description:
      "Implement security screenings and maintain airport perimeter safety.",
    category: ["Airport"],
    subcategory: ["Security"],
    salary: 48000,
    mainCategory: "Jobs",
    region: "Mudug",
    city: "Galkacyo",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Customs Inspection Agent",
    description:
      "Inspect goods and enforce import/export regulations at the airport.",
    category: ["Airport"],
    subcategory: ["Government"],
    salary: 58000,
    mainCategory: "Jobs",
    region: "Banaadir",
    city: "Mogadishu",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Flight Dispatcher",
    description:
      "Prepare flight plans and monitor weather conditions for airline safety.",
    category: ["Airport"],
    subcategory: ["Aviation"],
    salary: 65000,
    mainCategory: "Jobs",
    region: "Bari",
    city: "Bosaso",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Terminal Safety Officer",
    description:
      "Conduct regular safety inspections within the passenger terminal area.",
    category: ["Airport"],
    subcategory: ["Safety"],
    salary: 50000,
    mainCategory: "Jobs",
    region: "Hiraan",
    city: "Beledweyne",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Baggage Handling Manager",
    description:
      "Ensure the timely and accurate sorting and delivery of passenger luggage.",
    category: ["Airport"],
    subcategory: ["Operations"],
    salary: 42000,
    mainCategory: "Jobs",
    region: "Lower Juba",
    city: "Kismayo",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Airport Engineer",
    description:
      "Maintain airport infrastructure, including runways and technical systems.",
    category: ["Airport"],
    subcategory: ["Infrastructure"],
    salary: 80000,
    mainCategory: "Jobs",
    region: "Galgaduud",
    city: "Dhusamareb",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Hospital Sanitation Lead",
    description:
      "Manage clinical waste disposal and maintain sterile hospital environments.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 35000,
    mainCategory: "Jobs",
    region: "Banaadir",
    city: "Mogadishu",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Industrial Cleaning Expert",
    description:
      "Specialized cleaning services for factories and industrial equipment.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 38000,
    mainCategory: "Jobs",
    region: "Togdheer",
    city: "Burao",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Office Maintenance Supervisor",
    description:
      "Coordinate cleaning schedules and maintenance for corporate buildings.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 30000,
    mainCategory: "Jobs",
    region: "Bay",
    city: "Baidoa",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Public Works Cleaner",
    description:
      "Maintain cleanliness in public spaces, parks, and government offices.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 25000,
    mainCategory: "Jobs",
    region: "Lower Shabelle",
    city: "Afgooye",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Window Cleaning Specialist",
    description: "High-rise and commercial window cleaning services.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 32000,
    mainCategory: "Jobs",
    region: "Awdal",
    city: "Borama",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Street Sanitation Worker",
    description:
      "Daily maintenance and sanitation of urban streets and walkways.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 22000,
    mainCategory: "Jobs",
    region: "Banaadir",
    city: "Mogadishu",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    userId: "550e8400-e29b-41d4-a716-446655440001",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Waste Management Driver",
    description:
      "Operate waste collection vehicles and transport to processing sites.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 40000,
    mainCategory: "Jobs",
    region: "Bari",
    city: "Bosaso",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Janitorial Services Manager",
    description:
      "Oversee multiple janitorial teams and client service contracts.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 45000,
    mainCategory: "Jobs",
    region: "Nugaal",
    city: "Garowe",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "School Cleaning Coordinator",
    description:
      "Ensure health and safety standards are met in educational facilities.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 28000,
    mainCategory: "Jobs",
    region: "Mudug",
    city: "Galkacyo",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
  {
    title: "Airport Janitorial Staff",
    description:
      "Round-the-clock sanitation for airport terminals and restrooms.",
    category: ["Public"],
    subcategory: ["Cleaning"],
    salary: 26000,
    mainCategory: "Jobs",
    region: "Lower Juba",
    city: "Kismayo",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    userId: "550e8400-e29b-41d4-a716-446655440002",
    isPaid: true,
    expiryDate: new Date("2026-03-26T19:00:04.203Z"),
  },
];
