export interface MarketplaceItem {
  id: string;
  title: string;
  so: string;
  description: string;
  price: number;
  mainCategory: "Marketplace";
  category: string[];
  region: string;
  city: string;
  images: string[];
  isPaid: boolean;
  userId: string;
}

export const marketplaceSeederData: MarketplaceItem[] = [
  {
    id: "item-101",
    title: "Hand-Carved Somali Artifact",
    so: "Farshaxan Gacmeed Soomaali",
    description: "A beautiful, authentic hand-carved piece of Somali history.",
    price: 120,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    region: "awdal",
    city: "boorama",
    images: [
      "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
      "https://images.unsplash.com/photo-1505576399279-565b52d4ac71",
      "https://images.unsplash.com/photo-1520697222868-4491b9a2f5b2",
    ],
    isPaid: true,
    userId: "user-alpha-001",
  },
  {
    id: "item-102",
    title: "Pro Gaming Monitor 4K",
    so: "Shaashad Ciyaarta 4K",
    description:
      "Ultra-fast response time monitor, perfect for professional gamers.",
    price: 450,
    mainCategory: "Marketplace",
    category: ["Electronics"],
    region: "hamar",
    city: "hodan",
    images: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
      "https://images.unsplash.com/photo-1547119957-630f9c475d3d",
    ],
    isPaid: true,
    userId: "user-beta-002",
  },
  {
    id: "item-103",
    title: "Organic Livestock Feed",
    so: "Raashinka Xoolaha",
    description: "High-protein feed suitable for camels, goats, and cattle.",
    price: 35,
    mainCategory: "Marketplace",
    category: ["Animal & Supplies"],
    region: "mudug",
    city: "galkacyo",
    images: [
      "https://images.unsplash.com/photo-1606787366850-de6330128bfc",
      "https://images.unsplash.com/photo-1589927986089-35812388d1f4",
    ],
    isPaid: true,
    userId: "user-gamma-003",
  },
  {
    id: "item-104",
    title: "Mountain Hiking Gear",
    so: "Qalabka Buuraha",
    description:
      "Complete set of hiking gear for professional outdoor activities.",
    price: 180,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    region: "sanaag",
    city: "ceerigaabo",
    images: [
      "https://images.unsplash.com/photo-1518655048521-f130df041f66",
      "https://images.unsplash.com/photo-1526510747491-58f928ec870f",
    ],
    isPaid: true,
    userId: "user-delta-004",
  },
  {
    id: "item-105",
    title: "Luxury Dining Set",
    so: "Kuraasta Cuntada",
    description: "Solid wood dining table with 6 velvet upholstered chairs.",
    price: 850,
    mainCategory: "Marketplace",
    category: ["Furniture"],
    region: "wqdl",
    city: "hargeysa",
    images: [
      "https://images.unsplash.com/photo-1617806118233-f8e1320536c1",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
    ],
    isPaid: true,
    userId: "user-epsilon-005",
  },
  {
    id: "item-106",
    title: "Designer Handbag",
    so: "Boorso Qurxoon",
    description: "Limited edition leather handbag with gold accents.",
    price: 150,
    mainCategory: "Marketplace",
    category: ["Fashion"],
    region: "bari",
    city: "bosaso",
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
      "https://images.unsplash.com/photo-1591561954557-26941169b49e",
    ],
    isPaid: true,
    userId: "user-zeta-006",
  },
  {
    id: "item-107",
    title: "Vintage Wall Clock",
    so: "Saacad Qadiimi ah",
    description: "Victorian style brass wall clock, fully functional.",
    price: 90,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    region: "nugaal",
    city: "garowe",
    images: [
      "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c",
      "https://images.unsplash.com/photo-1509130298739-651801c76e96",
    ],
    isPaid: true,
    userId: "user-eta-007",
  },
  {
    id: "item-108",
    title: "Smart Home Speaker",
    so: "Sameecad Casri ah",
    description: "Voice-controlled speaker with AI integration.",
    price: 210,
    mainCategory: "Marketplace",
    category: ["Electronics"],
    region: "hamar",
    city: "waaberi",
    images: [
      "https://images.unsplash.com/photo-1589492477829-5e65395b66cc",
      "https://images.unsplash.com/photo-1543512214-318c7553f230",
    ],
    isPaid: true,
    userId: "user-theta-008",
  },
  {
    id: "item-109",
    title: "Dairy Cow - High Yield",
    so: "Sac Caanood",
    description: "Healthy dairy cow capable of high daily milk production.",
    price: 1100,
    mainCategory: "Marketplace",
    category: ["Animal & Supplies"],
    region: "shabeellaha-hoose",
    city: "afgooye",
    images: [
      "https://images.unsplash.com/photo-1546445317-29f4545e9d53",
      "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e",
    ],
    isPaid: true,
    userId: "user-iota-009",
  },
  {
    id: "item-110",
    title: "Professional Football Boots",
    so: "Kabayaha Cagta",
    description: "Lightweight boots designed for maximum grip and speed.",
    price: 85,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    region: "jubada-hoose",
    city: "kismaayo",
    images: [
      "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c",
      "https://images.unsplash.com/photo-1552066344-246397153127",
    ],
    isPaid: true,
    userId: "user-kappa-010",
  },
  {
    id: "item-111",
    title: "Ergonomic Office Chair",
    so: "Kursi Xafiis",
    description: "High-back mesh chair with lumbar support.",
    price: 145,
    mainCategory: "Marketplace",
    category: ["Furniture"],
    region: "galguduud",
    city: "dhusamareb",
    images: [
      "https://images.unsplash.com/photo-1505797149-43b0069ec26b",
      "https://images.unsplash.com/photo-1580480055273-228ff50d8ef4",
    ],
    isPaid: true,
    userId: "user-lambda-011",
  },
  {
    id: "item-112",
    title: "Traditional Bridal Jewelry",
    so: "Dahabka Arooska",
    description: "Complete set of jewelry for traditional ceremonies.",
    price: 3200,
    mainCategory: "Marketplace",
    category: ["Fashion"],
    region: "hamar",
    city: "xamar-weyne",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338",
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0",
    ],
    isPaid: true,
    userId: "user-mu-012",
  },
  {
    id: "item-113",
    title: "Oil Canvas Painting",
    so: "Sawir Gacmeed",
    description: "Original oil on canvas depicting the Somali coastline.",
    price: 250,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    region: "wqdl",
    city: "berbera",
    images: [
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5",
      "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9",
    ],
    isPaid: true,
    userId: "user-nu-013",
  },
  {
    id: "item-114",
    title: "Solar Power Inverter",
    so: "Inverter-ka Cadceedda",
    description: "High efficiency solar inverter for home use.",
    price: 320,
    mainCategory: "Marketplace",
    category: ["Electronics"],
    region: "bay",
    city: "baydhabo",
    images: [
      "https://images.unsplash.com/photo-1509391366360-2e959784a276",
      "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d",
    ],
    isPaid: true,
    userId: "user-xi-014",
  },
  {
    id: "item-115",
    title: "Automatic Poultry Feeder",
    so: "Mashiinka Raashinka",
    description: "Programmable feeder for poultry farms.",
    price: 55,
    mainCategory: "Marketplace",
    category: ["Animal & Supplies"],
    region: "shabeellaha-dhexe",
    city: "jowhar",
    images: ["https://images.unsplash.com/photo-1516467508483-a7212febe31a"],
    isPaid: true,
    userId: "user-omicron-015",
  },
  {
    id: "item-116",
    title: "Electric Scooter",
    so: "Mooto Koronto",
    description: "Foldable electric scooter with 30km range.",
    price: 380,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    region: "hamar",
    city: "wadajir",
    images: [
      "https://images.unsplash.com/photo-1597892657493-6847b9640bac",
      "https://images.unsplash.com/photo-1605030283010-877232230623",
    ],
    isPaid: true,
    userId: "user-pi-016",
  },
  {
    id: "item-117",
    title: "Handmade Rug",
    so: "Roog Gacmeed",
    description: "Large handmade floor rug with intricate designs.",
    price: 275,
    mainCategory: "Marketplace",
    category: ["Furniture"],
    region: "togdheer",
    city: "burco",
    images: [
      "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7",
      "https://images.unsplash.com/photo-1600166898405-da9535204843",
    ],
    isPaid: true,
    userId: "user-rho-017",
  },
  {
    id: "item-118",
    title: "Men's Formal Suite",
    so: "Suudhka Ragga",
    description: "Slim fit formal suit for weddings and events.",
    price: 130,
    mainCategory: "Marketplace",
    category: ["Fashion"],
    region: "hamar",
    city: "wardhiigley",
    images: [
      "https://images.unsplash.com/photo-1594932224440-74693226f537",
      "https://images.unsplash.com/photo-1593032465175-481ac7f401a0",
    ],
    isPaid: true,
    userId: "user-sigma-018",
  },
  {
    id: "item-119",
    title: "Ancient Bronze Coins",
    so: "Lacag Qadiimi ah",
    description: "Collectors item bronze coins from the historical era.",
    price: 500,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    region: "sool",
    city: "laas-caanood",
    images: ["https://images.unsplash.com/photo-1589230103236-07050f243a42"],
    isPaid: true,
    userId: "user-tau-019",
  },
  {
    id: "item-120",
    title: "Tablet PC 10-inch",
    so: "Tablet Casri ah",
    description: "Portable tablet with 128GB storage and stylus support.",
    price: 290,
    mainCategory: "Marketplace",
    category: ["Electronics"],
    region: "gedo",
    city: "doolow",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0",
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97",
    ],
    isPaid: true,
    userId: "user-upsilon-020",
  },
  {
    id: "item-121",
    title: "Professional Bee Hive",
    so: "Guriga Shinni",
    description: "Modern beehive box for honey production.",
    price: 75,
    mainCategory: "Marketplace",
    category: ["Animal & Supplies"],
    region: "bakool",
    city: "xudur",
    images: ["https://images.unsplash.com/photo-1587049352846-4a222e784d38"],
    isPaid: true,
    userId: "user-phi-021",
  },
  {
    id: "item-122",
    title: "Gym Dumbbell Set",
    so: "Miisaanka Jimicsiga",
    description: "Adjustable dumbbell set up to 20kg per side.",
    price: 110,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    region: "hiiraan",
    city: "beletweyne",
    images: [
      "https://images.unsplash.com/photo-1583454110551-21f2fa200c9c",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
    ],
    isPaid: true,
    userId: "user-chi-022",
  },
  {
    id: "item-123",
    title: "Modern Coffee Table",
    so: "Miiska Kafeega",
    description: "Marble top coffee table with gold-finished metal legs.",
    price: 180,
    mainCategory: "Marketplace",
    category: ["Furniture"],
    region: "hamar",
    city: "shangaani",
    images: [
      "https://images.unsplash.com/photo-1533090161767-e6ffed986c88",
      "https://images.unsplash.com/photo-1616489953149-922718e47455",
    ],
    isPaid: true,
    userId: "user-psi-023",
  },
  {
    id: "item-124",
    title: "Silk Scarf Collection",
    so: "Garba-saar Xariir",
    description: "Pure silk scarves with traditional hand-dyed patterns.",
    price: 45,
    mainCategory: "Marketplace",
    category: ["Fashion"],
    region: "jubada-dhexe",
    city: "jilib",
    images: ["https://images.unsplash.com/photo-1584030373081-f37b7bb4fa82"],
    isPaid: true,
    userId: "user-omega-024",
  },
  {
    id: "item-125",
    title: "Smart Water Meter",
    so: "Mitirka Biyaha",
    description: "IoT enabled water meter for accurate consumption tracking.",
    price: 65,
    mainCategory: "Marketplace",
    category: ["Electronics"],
    region: "hamar",
    city: "dharkeynley",
    images: ["https://images.unsplash.com/photo-1581244277943-fe4a9c777189"],
    isPaid: true,
    userId: "user-alpha-025",
  },
];
