// marketplaceSeederData.ts

export interface MarketplaceItem {
  title: string;
  so: string | null;
  description: string;
  price: number;
  mainCategory: string;
  category: string[];
  subcategory: string[];
  region: string;
  city: string;
  district: string;
  subDistrict: string | null;
  images: string[];
  extra: any;
  userId: string;
}

export const marketplaceSeederData: MarketplaceItem[] = [
  // --- Antiques & Art ---
  {
    title: "Antique Somali Wooden Bowl (Baaquli)",
    so: "Baaquli Qadiimi ah oo Soomaali ah",
    description: "Hand-carved traditional wooden bowl, very old.",
    price: 85,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    subcategory: ["Bowls"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_a",
    images: [
      "unsplash_somali_bowl_1",
      "unsplash_somali_bowl_2",
      "unsplash_somali_bowl_3",
    ],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Vintage Coffee Pot and Cups Set",
    so: "Qalabka Bunka Qadiimiga ah",
    description: "Complete service for traditional Somali coffee ceremony.",
    price: 120,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    subcategory: ["Coffee Service"],
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_a",
    images: [
      "unsplash_vintage_coffee_set_1",
      "unsplash_vintage_coffee_set_2",
      "unsplash_vintage_coffee_set_3",
    ],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Old Calligraphy Artwork",
    so: "Farshaxan Qoraal Duug ah",
    description: "Framed Islamic calligraphy, unique piece.",
    price: 90,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    subcategory: ["Other"],
    region: "Awdal",
    city: "Boorame",
    district: "Sub-district 1",
    userId: "user_b",
    images: [
      "unsplash_islamic_calligraphy_1",
      "unsplash_islamic_calligraphy_2",
      "unsplash_islamic_calligraphy_3",
    ],
    subDistrict: "Sub-district 1",
    extra: {},
  },
  {
    title: "Chinese Blue and White Porcelain Vase",
    so: "Fooraan Buluug iyo Cad ah",
    description: "Hand-painted antique porcelain vase, excellent condition.",
    price: 450,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    subcategory: ["Other"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_b",
    images: [
      "unsplash_porcelain_vase_1",
      "unsplash_porcelain_vase_2",
      "unsplash_porcelain_vase_3",
    ],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Vintage Leather Travel Trunk",
    so: "Sanduuq Safar Harag Duug ah",
    description: "1940s genuine leather trunk, great for decor or storage.",
    price: 250,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    subcategory: ["Other"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Dharkenley",
    userId: "user_a",
    images: [
      "unsplash_leather_trunk_1",
      "unsplash_leather_trunk_2",
      "unsplash_leather_trunk_3",
    ],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Antique Clock Mechanism Parts",
    so: "Qaybo Saacad Qadiimi ah",
    description: "Box of various brass gears and springs from old clocks.",
    price: 40,
    mainCategory: "Marketplace",
    category: ["Antiques & Art"],
    subcategory: ["Other"],
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_b",
    images: [
      "unsplash_clock_parts_1",
      "unsplash_clock_parts_2",
      "unsplash_clock_parts_3",
    ],
    subDistrict: null,
    extra: {},
  },

  // --- Electronics & Home Goods ---
  {
    title: "iPhone 13 Pro (Used)",
    so: "iPhone 13 Pro (La Isticmaalay)",
    description: "Excellent condition, 128GB, battery health 90%.",
    price: 850,
    mainCategory: "Marketplace",
    category: ["Electronics & Home Goods"],
    subcategory: ["Mobile Phones"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_a",
    images: ["unsplash_iphone_1", "unsplash_iphone_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "55-inch Smart 4K UHD TV",
    so: "TV Smart ah (55-inch)",
    description: "Brand: TCL, 2 years warranty remaining.",
    price: 550,
    mainCategory: "Marketplace",
    category: ["Electronics & Home Goods"],
    subcategory: ["TVs & Accessories"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Dharkenley",
    userId: "user_a",
    images: ["unsplash_smart_tv_1", "unsplash_smart_tv_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Small Electric Refrigerator",
    so: "Qaboojiye Yar oo Koronto ah",
    description: "Perfect for a small apartment or office.",
    price: 180,
    mainCategory: "Marketplace",
    category: ["Electronics & Home Goods"],
    subcategory: ["Home Appliances"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Waberi",
    userId: "user_a",
    images: ["unsplash_refrigerator_1", "unsplash_refrigerator_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "HP Pavilion Laptop (i5)",
    so: "Kumbuyuutar Gacanta ah (HP Pavilion)",
    description: "8GB RAM, 256GB SSD, great for school or work.",
    price: 400,
    mainCategory: "Marketplace",
    category: ["Electronics & Home Goods"],
    subcategory: ["Laptops & Computers"],
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_b",
    images: ["unsplash_laptop_1", "unsplash_laptop_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Digital SLR Camera Kit",
    so: "Kamarad SLR Dijitaal ah",
    description: "Includes camera body, 18-55mm lens, and bag.",
    price: 350,
    mainCategory: "Marketplace",
    category: ["Electronics & Home Goods"],
    subcategory: ["Cameras & Photography"],
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_a",
    images: ["unsplash_camera_1", "unsplash_camera_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Box of Various Cables and Chargers",
    so: "Sanduuqa Xadhkaha iyo Charger-yada",
    description: "Includes USB, HDMI, and various power cables.",
    price: 20,
    mainCategory: "Marketplace",
    category: ["Electronics & Home Goods"],
    subcategory: ["Other"], // Matches ElectronicsNestedSub
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_b",
    images: ["unsplash_cables_1", "unsplash_cables_2"],
    subDistrict: null,
    extra: {},
  },

  // --- Animals & Supplies ---
  {
    title: "Three Healthy Goats (Riyo)",
    so: "Saddex Riyo Caafimaad Qaba",
    description: "Ready for breeding or meat, sold as a lot.",
    price: 280,
    mainCategory: "Marketplace",
    category: ["Animals & Supplies"],
    subcategory: ["Livestock (Goats, Cattle)"],
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_a",
    images: ["unsplash_goats_1", "unsplash_goats_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Persian Kitten (Male)",
    so: "Bisad Yar oo Faarisi ah",
    description: "Six months old, vaccinated, very playful.",
    price: 100,
    mainCategory: "Marketplace",
    category: ["Animals & Supplies"],
    subcategory: ["Pets (Dogs, Cats)"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_a",
    images: ["unsplash_kitten_1", "unsplash_kitten_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "50kg Bag of Cattle Feed",
    so: "Kiish Quudinta Lo'da ah (50kg)",
    description: "High-protein mixture for fast growth.",
    price: 35,
    mainCategory: "Marketplace",
    category: ["Animals & Supplies"],
    subcategory: ["Animal Feed & Hay"],
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_b",
    images: ["unsplash_feed_bag_1", "unsplash_feed_bag_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Large Dog Kennel/Crate",
    so: "Aqalka Eeyga Weyn",
    description: "Durable wire construction, suitable for large breeds.",
    price: 60,
    mainCategory: "Marketplace",
    category: ["Animals & Supplies"],
    subcategory: ["Pet Accessories"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Dharkenley",
    userId: "user_a",
    images: ["unsplash_dog_kennel_1", "unsplash_dog_kennel_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Veterinary Medicine Kit",
    so: "Qalabka Daaweynta Xoolaha",
    description: "Essential medicines for small livestock.",
    price: 90,
    mainCategory: "Marketplace",
    category: ["Animals & Supplies"],
    subcategory: ["Other"], // Matches AnimalAndSuppliesNestedSub
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_b",
    images: ["unsplash_vet_kit_1", "unsplash_vet_kit_2"],
    subDistrict: null,
    extra: {},
  },

  // --- Sports & Outdoors ---
  {
    title: "Professional Treadmill",
    so: "Mashiinka Jimicsiga (Treadmill)",
    description: "Commercial grade, inclines up to 15%.",
    price: 600,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Gym Equipment"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_b",
    images: ["unsplash_treadmill_1", "unsplash_treadmill_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Four-Person Tent",
    so: "Teendho Afar Qof ah",
    description: "Used once, quick setup, waterproof.",
    price: 65,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Camping & Hiking Gear"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_b",
    images: ["unsplash_tent_1", "unsplash_tent_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Mountain Bike (Large Frame)",
    so: "Baaskiil Buureed (Frame Weyn)",
    description: "21 gears, disc brakes, ready for trails.",
    price: 250,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Bicycles"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Waberi",
    userId: "user_a",
    images: ["unsplash_bike_1", "unsplash_bike_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Set of Soccer Balls and Pump",
    so: "Qalabka Kubadda Cagta",
    description: "Three size 5 soccer balls and a hand pump.",
    price: 45,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Sporting Goods"],
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_b",
    images: ["unsplash_soccer_balls_1", "unsplash_soccer_balls_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Heavy Duty Backpack (70L)",
    so: "Boorso Safar Weyn (70L)",
    description: "Internal frame, ideal for multi-day trips.",
    price: 80,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Other"], // Matches SportsAndOutdoorsNestedSub
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_a",
    images: ["unsplash_backpack_1", "unsplash_backpack_2"],
    subDistrict: null,
    extra: {},
  },

  // --- Furniture & Decor ---
  {
    title: "Large L-Shaped Sectional Sofa",
    so: "Fadhi Weyn oo L-Shaap ah",
    description: "Grey fabric, very comfortable, perfect for a family room.",
    price: 400,
    mainCategory: "Marketplace",
    category: ["Furniture & Decor"],
    subcategory: ["Sofas & Couches"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_a",
    images: ["unsplash_sofa_1", "unsplash_sofa_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Wooden Dining Table (6 chairs)",
    so: "Miiska Qadada oo alwaax ah (6 Kursi)",
    description: "Solid wood construction, excellent condition.",
    price: 280,
    mainCategory: "Marketplace",
    category: ["Furniture & Decor"],
    subcategory: ["Tables & Desks"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Dharkenley",
    userId: "user_a",
    images: ["unsplash_dining_table_1", "unsplash_dining_table_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Queen Size Mattress (Memory Foam)",
    so: "Furaash Weyn (Queen Size)",
    description: "Used 6 months, medium-firm, clean.",
    price: 150,
    mainCategory: "Marketplace",
    category: ["Furniture & Decor"],
    subcategory: ["Beds & Mattresses"],
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_b",
    images: ["unsplash_mattress_1", "unsplash_mattress_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Stainless Steel Kitchen Rack",
    so: "Shiibada Jikada (Stainless Steel)",
    description: "Four-tier storage rack for pots and pans.",
    price: 75,
    mainCategory: "Marketplace",
    category: ["Furniture & Decor"],
    subcategory: ["Kitchen Furnishings"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Waberi",
    userId: "user_a",
    images: ["unsplash_kitchen_rack_1", "unsplash_kitchen_rack_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Decorative Floor Lamp",
    so: "Laambada Dhulka",
    description: "Modern design, adjustable height.",
    price: 50,
    mainCategory: "Marketplace",
    category: ["Furniture & Decor"],
    subcategory: ["Other"], // Matches FurnitureNestedSub
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_b",
    images: ["unsplash_floor_lamp_1", "unsplash_floor_lamp_2"],
    subDistrict: null,
    extra: {},
  },

  // --- Fashion & Accessories ---
  {
    title: "Men's Designer Suit (Size 42)",
    so: "Suud Ragga ah (Size 42)",
    description: "Worn once, like new, Navy Blue.",
    price: 150,
    mainCategory: "Marketplace",
    category: ["Fashion & Accessories"],
    subcategory: ["Men's Clothing"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_a",
    images: ["unsplash_suit_1", "unsplash_suit_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Vintage 1980s Leather Messenger Bag",
    so: "Boorso Harag ah oo Duug ah",
    description: "Well-preserved bag with classic design.",
    price: 70,
    mainCategory: "Marketplace",
    category: ["Fashion & Accessories"],
    subcategory: ["Bags & Wallets"],
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_a",
    images: ["unsplash_messenger_bag_1", "unsplash_messenger_bag_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Women's Party Dress (Red)",
    so: "Dhar Xafladeed Haweenka ah (Cas)",
    description: "Sequined, size Small, excellent for events.",
    price: 60,
    mainCategory: "Marketplace",
    category: ["Fashion & Accessories"],
    subcategory: ["Women's Clothing"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Waberi",
    userId: "user_b",
    images: ["unsplash_dress_1", "unsplash_dress_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Leather Boots (Women's Size 39)",
    so: "Kabaha Haragga ah (Size 39)",
    description: "High-quality leather, barely worn.",
    price: 80,
    mainCategory: "Marketplace",
    category: ["Fashion & Accessories"],
    subcategory: ["Shoes & Footwear"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_a",
    images: ["unsplash_boots_1", "unsplash_boots_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Wrist Watch Collection (5 pieces)",
    so: "Saacadaha Gacanta (5 Xabbo)",
    description: "Mixed lot of fashion watches.",
    price: 45,
    mainCategory: "Marketplace",
    category: ["Fashion & Accessories"],
    subcategory: ["Other"], // Matches FashionNestedSub
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_b",
    images: ["unsplash_watches_1", "unsplash_watches_2"],
    subDistrict: null,
    extra: {},
  },

  // toys alaabta carruurta

  {
    title: "Wooden Building Blocks Set",
    so: "Alaabta & Ciyaaraha Carruurta",
    description: "100-piece classic set for toddlers.",
    price: 30,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Toys"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_a",
    images: ["unsplash_blocks_1", "unsplash_blocks_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Remote Control Monster Truck",
    so: "Gaadhi Ciidaanka Kontroolka ah",
    description: "High-speed electric RC truck, rechargeable battery.",
    price: 55,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Toys"],
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_b",
    images: ["unsplash_rc_truck_1", "unsplash_rc_truck_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Giant Plush Teddy Bear",
    so: "Xayawaan La Buuxiyey (Orso Weyn)",
    description: "Very large stuffed animal, over 1 meter tall.",
    price: 70,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Toys"],
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_a",
    images: ["unsplash_teddy_bear_1", "unsplash_teddy_bear_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Family Board Game Collection",
    so: "Ciyaaraha Guddida Qoyska",
    description: "Includes Monopoly, Chess, and Dominoes.",
    price: 40,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Toys"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Dharkenley",
    userId: "user_b",
    images: ["unsplash_board_games_1", "unsplash_board_games_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Kids' Tablet (Learning)",
    so: "Tablet Carruurta (Waxbarasho)",
    description: "Pre-loaded with educational apps, durable case.",
    price: 60,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Toys"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Waberi",
    userId: "user_a",
    images: ["unsplash_kids_tablet_1", "unsplash_kids_tablet_2"],
    subDistrict: null,
    extra: {},
  },
  {
    title: "Action Figures Lot (Mixed)",
    so: "Sawirada Ciyaaraha (Isku Qasan)",
    description: "Box of various superhero and cartoon action figures.",
    price: 35,
    mainCategory: "Marketplace",
    category: ["Sports & Outdoors"],
    subcategory: ["Toys"],
    region: "Gedo",
    city: "Doolow",
    district: "Bulo Lakow",
    userId: "user_a",
    images: ["unsplash_action_figures_1", "unsplash_action_figures_2"],
    subDistrict: null,
    extra: {},
  },

  //FurnitureSeederData

  {
    title: "Modern Three-Seater Sofa",
    so: "Fadhi Sadex Kursi Ah",
    description:
      "Comfortable velvet sofa, light grey, perfect for the living room. Excellent condition.",
    price: 650,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Sofas & Couches"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    subDistrict: null,
    images: ["/images/furniture/sofa1.jpg"],
    userId: "user-alpha-101",
    extra: undefined,
  },
  {
    title: "Leather L-Shaped Sectional",
    so: "Fadhi Maqaar Qaloocan",
    description:
      "Large black leather sectional sofa. Great for big families or entertaining.",
    price: 1200,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Sofas & Couches"],
    region: "Woqooyi Galbeed",
    city: "Hargeisa",
    district: "Gacan Libaax",
    subDistrict: null,
    images: ["/images/furniture/sofa2.jpg"],
    userId: "user-bravo-102",
    extra: undefined,
  },
  {
    title: "Queen Size Bed Frame with Storage",
    so: "Sariir Weyn oo Bakhaar Leh",
    description:
      "Solid wood queen bed frame with two drawers underneath for storage. Mattress not included.",
    price: 380,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Beds & Mattresses"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Waberi",
    subDistrict: null,
    images: ["/images/furniture/bed1.jpg"],
    userId: "user-alpha-101",
    extra: undefined,
  },
  {
    title: "New Orthopedic Single Mattress",
    so: "Furaash Caafimaad oo Cusub",
    description:
      "Brand new, never used single orthopedic mattress. Medium-firm support.",
    price: 150,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Beds & Mattresses"],
    region: "Galguduud",
    city: "Dhusamareb",
    district: "Dhusamareb",
    subDistrict: null,
    images: ["/images/furniture/mattress1.jpg"],
    userId: "user-charlie-103",
    extra: undefined,
  },
  {
    title: "Wooden Dining Table (6 Chairs)",
    so: "Miiska Qadada (6 kursi)",
    description:
      "Large, sturdy wooden dining table set with six matching chairs. Minor signs of wear.",
    price: 450,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Tables & Desks"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Karan",
    subDistrict: null,
    images: ["/images/furniture/table1.jpg"],
    userId: "user-alpha-101",
    extra: undefined,
  },
  {
    title: "Compact Computer Desk",
    so: "Miis Kombuyuutar Yar",
    description:
      "Small, white computer desk, ideal for a home office or student room.",
    price: 90,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Tables & Desks"],
    region: "Mudug",
    city: "Galkayo",
    district: "Galkayo North",
    subDistrict: null,
    images: ["/images/furniture/desk1.jpg"],
    userId: "user-bravo-102",
    extra: undefined,
  },
  {
    title: "Kitchen Storage Cabinet (White)",
    so: "Bakhaarka Jikada Cad",
    description:
      "Tall kitchen cabinet with glass doors and adjustable shelving.",
    price: 220,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Kitchen Furnishings"],
    region: "Lower Shabelle",
    city: "Marka",
    district: "Marka",
    subDistrict: null,
    images: ["/images/furniture/kitchen1.jpg"],
    userId: "user-charlie-103",
    extra: undefined,
  },
  {
    title: "Set of 4 Bar Stools (Metal)",
    so: "4 Kursi Baar Bir ah",
    description: "Four modern metal bar stools, perfect for a kitchen island.",
    price: 100,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Kitchen Furnishings"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Deyniile",
    subDistrict: null,
    images: ["/images/furniture/barstools1.jpg"],
    userId: "user-alpha-101",
    extra: undefined,
  },
  {
    title: "Large Decorative Mirror",
    so: "Muraayad Qurux Badan oo Weyn",
    description: "Floor-standing mirror with a gold frame. 180cm x 70cm.",
    price: 75,
    mainCategory: "Marketplace",
    category: ["Furniture & Interior"],
    subcategory: ["Other"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hamar Jajab",
    subDistrict: null,
    images: ["/images/furniture/mirror1.jpg"],
    userId: "user-delta-104",
    extra: undefined,
  },
  // --- Military & Uniforms (Ciidado) ---
  {
    title: "3-Piece Military Uniform (Ciidado)",
    so: "Dhar Ciidan (3 Xabbo)",
    description: "New complete uniform set, size large.",
    price: 95,
    mainCategory: "Marketplace",
    category: ["Military & Uniforms"],
    subcategory: ["Uniforms"],
    region: "Banaadir",
    city: "Mogadishu",
    district: "Hodan",
    userId: "user_military_a",
    images: ["unsplash_uniform_1", "unsplash_uniform_2"],
    subDistrict: null,
    extra: { size: "L", condition: "New" },
  },
  {
    title: "Set of Two Camouflage Nets",
    so: "Laba Shabag isqarin ah",
    description:
      "Heavy duty, 6x6 meters each, great for tactical use or shade.",
    price: 120,
    mainCategory: "Marketplace",
    category: ["Military & Uniforms"],
    subcategory: ["Equipment"],
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    userId: "user_military_b",
    images: ["unsplash_camouflage_net_1", "unsplash_camouflage_net_2"],
    subDistrict: null,
    extra: { dimensions: "6x6m" },
  },
];
