export const motorcycleItems = [
  // --- FOR SALE: NEW MOTORCYCLE ---
  {
    id: "m1",
    userId: "user-alpha-101",
    title: "Yamaha YZF-R1 High Performance Bike",
    so: "Yamaha R1 Baaskiil Xawaare Sare ah",
    mainCategory: "Motorcycle",
    category: ["For Sale"],
    subcategory: ["New Motorcycle"],
    transmission: "Manual",
    price: 15500,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    subDistrict: "Xaafada Siinaay",
    images: [
      "https://images.unsplash.com/photo-1636428819198-408d10a8a774?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fG1vdG8lMjB3aXRoJTIwdGhyZWUlMjB3aGVlbHN8ZW58MHx8MHx8fDA%3D",
    ],
    type: "Motorcycle",
    make: "Yamaha",
    modelName: "YZF-R1",
    year: 2024,
    mileage: 0,
    engineSize: "1000cc",
    fuelType: "Petrol",
    color: "Red",
    description: "High performance sports bike, brand new, zero mileage.",
  },
  // --- FOR SALE: USED MOTORCYCLE ---
  {
    id: "m2",
    userId: "user-bravo-102",
    title: "Honda CRF 250L Dual Sport (Used)",
    so: "Honda CRF 250L (La Isticmaalay)",
    mainCategory: "Motorcycle",
    category: ["For Sale"],
    subcategory: ["Used Motorcycle"],
    transmission: "Manual",
    price: 4500,
    region: "Gedo",
    city: "Garbaharey",
    district: "Garbaharey Center",
    subDistrict: "Xaafada Dayax",
    images: [
      "https://images.unsplash.com/photo-1719210699706-be76b36e9e7f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fG1vdG9jbHllc3xlbnwwfHwwfHx8MA%3D%3D",
    ],
    type: "Motorcycle",
    make: "Honda",
    modelName: "CRF 250L",
    year: 2019,
    mileage: 8000,
    engineSize: "250cc",
    fuelType: "Petrol",
    color: "White/Red",
    description: "Reliable dual-sport bike, excellent for challenging terrain.",
  },
  // --- FOR SALE: USED VESPA ---
  {
    id: "m3",
    userId: "user-delta-104",
    title: "Piaggio Vespa Scooter (Automatic)",
    so: "Vespa La Isticmaalay",
    mainCategory: "Motorcycle",
    category: ["For Sale"],
    subcategory: ["Used Vespa"],
    transmission: "Automatic",
    price: 3200,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Waberi",
    subDistrict: "Wadada Afarta Jid",
    images: [
      "https://images.unsplash.com/photo-1583875097165-444ac3a1fb53?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bW90byUyMHdpdGglMjB0aHJlZSUyMHdoZWVsc3xlbnwwfHwwfHx8MA%3D%3D",
    ],
    type: "Scooter",
    make: "Piaggio",
    modelName: "Vespa Primavera 150",
    year: 2023,
    mileage: 500,
    engineSize: "150cc",
    fuelType: "Petrol",
    color: "Light Blue",
    description: "Classic scooter, minimal use, ideal for city commuting.",
  },
  // --- RENTAL: BAJAJ FOR RENT ---
  {
    id: "m4",
    userId: "user-alpha-101",
    title: "Bajaj RE Passenger Tuk Tuk (Kiro)",
    so: "Bajaaj Kiro Ah (Raaxada)",
    mainCategory: "Motorcycle",
    category: ["Rental"],
    subcategory: ["Bajaj for Rent"],
    transmission: "Manual",
    price: 25,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Dharkenley",
    subDistrict: "Garasbaaley",
    images: [
      "https://images.unsplash.com/photo-1646845642010-fb2bb921819c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bW90byUyMHdpdGglMjB0aHJlZSUyMHdoZWVsc3xlbnwwfHwwfHx8MA%3D%3D",
    ],
    type: "Tuk Tuk",
    make: "Bajaj",
    modelName: "RE Compact",
    year: 2020,
    mileage: 30000,
    engineSize: "200cc",
    fuelType: "Petrol/Gas",
    color: "Yellow",
    description:
      "Reliable Tuk Tuk for passenger transport, available for daily rental.",
  },
  // --- RENTAL: MOTORCYCLE RENTAL ---
  {
    id: "m5",
    userId: "user-bravo-102",
    title: "Motorcycle Rental - Touring Bike",
    so: "Mooto Kiro ah (Safar)",
    mainCategory: "Motorcycle",
    category: ["Rental"],
    subcategory: ["Motorcycle Rental"],
    transmission: "Manual",
    price: 35,
    region: "Awdal",
    city: "Boorame",
    district: "Dila",
    subDistrict: "Beerta",
    images: [
      "https://images.unsplash.com/photo-1579212130000-8d5c4149c065?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG1vdG9yYmlrZSUyMHJlbnRhbHxlbnwwfHwwfHx8MA%3D%3D",
    ],
    type: "Touring Bike",
    make: "Kawasaki",
    modelName: "Versys 650",
    year: 2018,
    mileage: 45000,
    engineSize: "650cc",
    fuelType: "Petrol",
    color: "Grey",
    description:
      "Adventure touring bike available for rental, suitable for long journeys.",
  },
  // --- RENTAL: CARGO BAJAJ RENTAL ---
  {
    id: "m6",
    userId: "user-charlie-103",
    title: "Cargo Bajaj Rental (Tuk Tuk Xamuul)",
    so: "Bajaaj Xamuul Kiro Ah",
    mainCategory: "Motorcycle",
    category: ["Rental"],
    subcategory: ["Cargo Bajaj Rental"],
    transmission: "Manual",
    price: 30,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Kaaraan",
    subDistrict: "Warsheekh",
    images: [
      "https://images.unsplash.com/photo-1644185436036-c278d4dc2059?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FyZ28lMjB0dWsJdHVrfGVufDB8fDB8fHww",
    ],
    type: "Cargo Tuk Tuk",
    make: "Bajaj",
    modelName: "Maxima C",
    year: 2021,
    mileage: 20000,
    engineSize: "400cc",
    fuelType: "Diesel",
    color: "Green",
    description:
      "Heavy-duty cargo Tuk Tuk for transporting goods, available for daily or weekly rental.",
  },
  // --- PARTS: MOTORCYCLE ENGINES ---
  {
    id: "m7",
    userId: "user-alpha-101",
    title: "Used Honda 125cc Engine",
    so: "Matoorka Mooto Honda (La Isticmaalay)",
    mainCategory: "Motorcycle",
    category: ["Parts & Accessories"],
    subcategory: ["Motorcycle Engines"],
    transmission: "Manual",
    price: 350,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    subDistrict: "Isku-Filan",
    images: [
      "https://images.unsplash.com/photo-1627885908588-46654b0c2e6f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdG9yYmlrZSUyMGVuZ2luZXxlbnwwfHwwfHx8MA%3D%3D",
    ],
    type: "Engine",
    make: "Honda",
    modelName: "CG 125",
    year: 2010,
    mileage: 0,
    engineSize: "125cc",
    fuelType: "Petrol",
    color: "Silver",
    description:
      "Reliable used engine for a standard 125cc motorcycle. Recently serviced.",
  },
  // --- PARTS: TIRES/RIMS ---
  {
    id: "m8",
    userId: "user-bravo-102",
    title: "Set of New Sport Bike Tires (Dunlop)",
    so: "Taayirrada Mooto Ciyaar (Cusub)",
    mainCategory: "Motorcycle",
    category: ["Parts & Accessories"],
    subcategory: ["Tires/Rims"],
    transmission: null,
    price: 180,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Axmed Dhagax",
    subDistrict: "New Hargeysa",
    images: [
      "https://images.unsplash.com/photo-1549440624-9dc384227096?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bW90b3JiaWtlJTIwdGlyZXN8ZW58MHx8MHx8fDA%3D",
    ],
    type: "Tires",
    make: "Dunlop",
    modelName: "Sportmax",
    year: 2023,
    mileage: 0,
    engineSize: "",
    fuelType: "N/A",
    color: "Black",
    description:
      "Front and rear set of high-performance Dunlop sport bike tires.",
  },
  // --- PARTS: PROTECTIVE GEAR ---
  {
    id: "m9",
    userId: "user-charlie-103",
    title: "Full Face Motorcycle Helmet (Size L)",
    so: "Koofiyadda Mootada (Size L)",
    mainCategory: "Motorcycle",
    category: ["Parts & Accessories"],
    subcategory: ["Protective Gear"],
    transmission: null,
    price: 90,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Waberi",
    subDistrict: "Afar-Irdoodka",
    images: [
      "https://images.unsplash.com/photo-1574044199912-3023e9860c2b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG1vdG9yYmlrZSUyMGhlbG1ldHxlbnwwfHwwfHx8MA%3D%3D",
    ],
    type: "Helmet",
    make: "HJC",
    modelName: "i10",
    year: 2022,
    mileage: 0,
    engineSize: "",
    fuelType: "N/A",
    color: "Matte Black",
    description: "DOT certified full-face helmet, size Large. Used once.",
  },
  // --- FOR SALE: NEW BAJAJ ---
  {
    id: "m10",
    userId: "user-delta-104",
    title: "Brand New Bajaj Tuk Tuk",
    so: "Bajaaj Cusub (Raaxada)",
    mainCategory: "Motorcycle",
    category: ["For Sale"],
    subcategory: ["New Bajaj"],
    transmission: "Manual",
    price: 4000,
    region: "Jubadda Hoose",
    city: "Kismaayo",
    district: "Calanleey",
    subDistrict: "Beerta",
    images: [
      "https://images.unsplash.com/photo-1621516246476-880628203f57?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGJhamFqfGVufDB8fDB8fHww",
    ],
    type: "Tuk Tuk",
    make: "Bajaj",
    modelName: "RE Compact",
    year: 2024,
    mileage: 0,
    engineSize: "200cc",
    fuelType: "Petrol/Gas",
    color: "Blue",
    description: "Zero mileage Bajaj Tuk Tuk, ready for registration.",
  },
  // --- RENTAL: VESPA RENTAL ---
  {
    id: "m11",
    userId: "user-alpha-101",
    title: "Vespa Scooter Rental (Weekly)",
    so: "Vespa Kiro ah (Toddobaadle)",
    mainCategory: "Motorcycle",
    category: ["Rental"],
    subcategory: ["Vespa Rental"],
    transmission: "Automatic",
    price: 150,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Dharkenley",
    subDistrict: "Xamar Jajab",
    images: [
      "https://images.unsplash.com/photo-1606540307997-b673059e9c5e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHZlc3BhJTIwcmVudGFsfGVufDB8fDB8fHww",
    ],
    type: "Scooter",
    make: "Vespa",
    modelName: "GTS 300",
    year: 2020,
    mileage: 15000,
    engineSize: "300cc",
    fuelType: "Petrol",
    color: "White",
    description: "Powerful Vespa available for weekly rental in the city.",
  },
  // --- PARTS: BAJAJ ENGINES ---
  {
    id: "m12",
    userId: "user-bravo-102",
    title: "Bajaj RE 200cc Engine (Used)",
    so: "Matoorka Bajaaj (La Isticmaalay)",
    mainCategory: "Motorcycle",
    category: ["Parts & Accessories"],
    subcategory: ["Bajaj Engines"],
    transmission: null,
    price: 450,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Kaaraan",
    subDistrict: "Wadada Sodonka",
    images: [
      "https://images.unsplash.com/photo-1549440624-9dc384227096?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c21hbGwlMjBlbmdpbmV8ZW58MHx8MHx8fDA%3D",
    ],
    type: "Engine",
    make: "Bajaj",
    modelName: "RE 200cc",
    year: 2018,
    mileage: 0,
    engineSize: "200cc",
    fuelType: "Petrol",
    color: "N/A",
    description: "Fully working Bajaj engine, removed from a scrapped model.",
  },
];
