export const motorcycleItems = [
  {
    id: "m1",
    userId: "user-alpha-101",
    title: "Yamaha YZF-R1 High Performance Bike",
    so: "Yamaha R1 Baaskiil Xawaare Sare ah",
    mainCategory: "Motorcycle",
    category: ["For Sale"],
    subcategory: ["New Motorcycle"],
    transmission: "Manual",
    price: 15500,
    region: "hamar",
    city: "hamar",
    images: [
      "https://images.unsplash.com/photo-1636428819198-408d10a8a774?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Motorcycle",
    make: "Yamaha",
    modelName: "YZF-R1",
    year: 2024,
    mileage: 0,
    engineSize: "1000cc",
    fuelType: "Petrol",
    color: "Red",
    description: "High performance sports bike, brand new, zero mileage.",
    isPaid: true,
  },
  {
    id: "m2",
    userId: "user-bravo-102",
    title: "Honda CRF 250L Dual Sport",
    so: "Honda CRF 250L",
    mainCategory: "Motorcycle",
    category: ["For Sale"],
    subcategory: ["Used Motorcycle"],
    transmission: "Manual",
    price: 4500,
    region: "gedo",
    city: "garbaharey",
    images: [
      "https://images.unsplash.com/photo-1719210699706-be76b36e9e7f?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Motorcycle",
    make: "Honda",
    modelName: "CRF 250L",
    year: 2019,
    mileage: 8000,
    engineSize: "250cc",
    fuelType: "Petrol",
    color: "White/Red",
    description: "Reliable dual-sport bike, excellent for challenging terrain.",
    isPaid: true,
  },
  {
    id: "m3",
    userId: "user-delta-104",
    title: "Piaggio Vespa Scooter",
    so: "Vespa",
    mainCategory: "Motorcycle",
    category: ["For Sale"],
    subcategory: ["Used Vespa"],
    transmission: "Automatic",
    price: 3200,
    region: "hamar",
    city: "hamar",
    images: [
      "https://images.unsplash.com/photo-1583875097165-444ac3a1fb53?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Scooter",
    make: "Piaggio",
    modelName: "Vespa Primavera 150",
    year: 2023,
    mileage: 500,
    engineSize: "150cc",
    fuelType: "Petrol",
    color: "Light Blue",
    description: "Classic scooter, minimal use, ideal for city commuting.",
    isPaid: true,
  },
  {
    id: "m4",
    userId: "user-alpha-101",
    title: "Bajaj RE Passenger Tuk Tuk",
    so: "Bajaaj Kiro Ah",
    mainCategory: "Motorcycle",
    category: ["For Rent"],
    subcategory: ["Bajaj for Rent"],
    transmission: "Manual",
    price: 25,
    region: "hamar",
    city: "hamar",
    images: [
      "https://images.unsplash.com/photo-1646845642010-fb2bb921819c?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Tuk Tuk",
    make: "Bajaj",
    modelName: "RE Compact",
    year: 2020,
    mileage: 30000,
    engineSize: "200cc",
    fuelType: "Petrol/Gas",
    color: "Yellow",
    description:
      "Reliable Tuk Tuk for passenger transport, available for daily rental.",
    isPaid: true,
  },
  {
    id: "m5",
    userId: "user-bravo-102",
    title: "Motorcycle Rental Touring Bike",
    so: "Mooto Kiro ah",
    mainCategory: "Motorcycle",
    category: ["For Rent"],
    subcategory: ["Motorcycle Rental"],
    transmission: "Manual",
    price: 35,
    region: "awdal",
    city: "boorame",
    images: [
      "https://images.unsplash.com/photo-1579212130000-8d5c4149c065?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Touring Bike",
    make: "Kawasaki",
    modelName: "Versys 650",
    year: 2018,
    mileage: 45000,
    engineSize: "650cc",
    fuelType: "Petrol",
    color: "Grey",
    description:
      "Adventure touring bike available for rental, suitable for long journeys.",
    isPaid: true,
  },
  {
    id: "m6",
    userId: "user-charlie-103",
    title: "Cargo Bajaj Rental",
    so: "Bajaaj Xamuul Kiro Ah",
    mainCategory: "Motorcycle",
    category: ["For Rent"],
    subcategory: ["Cargo Bajaj Rental"],
    transmission: "Manual",
    price: 30,
    region: "hamar",
    city: "hamar",
    images: [
      "https://images.unsplash.com/photo-1644185436036-c278d4dc2059?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Cargo Tuk Tuk",
    make: "Bajaj",
    modelName: "Maxima C",
    year: 2021,
    mileage: 20000,
    engineSize: "400cc",
    fuelType: "Diesel",
    color: "Green",
    description:
      "Heavy-duty cargo Tuk Tuk for transporting goods, available for daily or weekly rental.",
    isPaid: true,
  },
  {
    id: "m7",
    userId: "user-alpha-101",
    title: "Used Honda 125cc Engine",
    so: "Matoorka Mooto Honda",
    mainCategory: "Motorcycle",
    category: ["Spare Parts"],
    subcategory: ["Motorcycle Engines"],
    transmission: "Manual",
    price: 350,
    region: "hamar",
    city: "hamar",
    images: [
      "https://images.unsplash.com/photo-1627885908588-46654b0c2e6f?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Engine",
    make: "Honda",
    modelName: "CG 125",
    year: 2010,
    mileage: 0,
    engineSize: "125cc",
    fuelType: "Petrol",
    color: "Silver",
    description: "Reliable used engine for a standard 125cc motorcycle.",
    isPaid: true,
  },
  {
    id: "m12",
    userId: "user-bravo-102",
    title: "Bajaj RE 200cc Engine",
    so: "Matoorka Bajaaj",
    mainCategory: "Motorcycle",
    category: ["Spare Parts"],
    subcategory: ["Bajaj Engines"],
    transmission: null,
    price: 450,
    region: "hamar",
    city: "hamar",
    images: [
      "https://images.unsplash.com/photo-1549440624-9dc384227096?w=500&auto=format&fit=crop&q=60",
    ],
    type: "Engine",
    make: "Bajaj",
    modelName: "RE 200cc",
    year: 2018,
    mileage: 0,
    engineSize: "200cc",
    fuelType: "Petrol",
    color: "N/A",
    description: "Fully working Bajaj engine, removed from a scrapped model.",
    isPaid: true,
  },
];
