export const notificationItems = [
  {
    userId: "64d4a43c9a8b0e6e8c4a5678",
    senderId: "64d4a43c9a8b0e6e8c4a5679",
    title: "New Subscription",
    message: "You have successfully subscribed to the newsletter",
    category: "service",
    subCategory: "newsletter",
    itemId: null,
    itemType: null,
    region: "Banadir",
    city: "Mogadishu",
    isRead: false,
    isDelivered: false,
    metadata: null,
  },
  {
    userId: "64d4a43c9a8b0e6e8c4a5679",
    senderId: "64d4a43c9a8b0e6e8c4a5678",
    title: "Price Drop",
    message: "Price dropped on Toyota Corolla 2020",
    category: "vehicle",
    subCategory: "car",
    itemId: null,
    itemType: null,
    region: "Bari",
    city: "Bosaso",
    isRead: false,
    isDelivered: false,
    metadata: null,
  },
  {
    userId: "64d4a43c9a8b0e6e8c4a5678",
    senderId: "64d4a43c9a8b0e6e8c4a5678",
    title: "New Message",
    message: "You have a new message from Ahmed",
    category: "communication",
    subCategory: "userMessage",
    itemId: null,
    itemType: null,
    region: "Mudug",
    city: "Gaalkacyo",
    isRead: false,
    isDelivered: false,
    metadata: null,
  },
  {
    userId: "64d4a43c9a8b0e6e8c4a5679",
    senderId: "64d4a43c9a8b0e6e8c4a5679",
    title: "Listing Expiring",
    message: "Your motorcycle listing expires in 3 days",
    category: "vehicle",
    subCategory: "motorcycle",
    itemId: null,
    itemType: null,
    region: "Hiiraan",
    city: "Beledweyne",
    isRead: false,
    isDelivered: false,
    metadata: null,
  },
];
