export interface RealEstateItem {
  id: string;
  title: string;
  so: string;
  description: string;
  price: number;
  mainCategory: string;
  category: string[];
  subcategory: string[];
  bedrooms: number;
  bathrooms: number;
  squareFeet: number;
  address: string;
  hasGarage: boolean;
  hasGarden: boolean;
  region: string;
  city: string;
  county: string;
  images: string[];
  isPaid: boolean;
}

export const realEstateItems: RealEstateItem[] = [
  {
    id: "r6",
    title: "Guri dabaq (Apartment) Kiro ah",
    so: "Guri Kiro ah oo 3 Qol jiif ah",
    description:
      "Guri dabaq ah ku yaal Xamar-weyne, ku habboon qoysaska yar yar.",
    price: 500,
    mainCategory: "RealEstate",
    category: ["Kirada"],
    subcategory: ["Guri dabaq ah"],
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1100,
    address: "Wadada Sanca, Waaberi",
    hasGarage: false,
    hasGarden: false,
    region: "Hamar",
    city: "Waaberi",
    county: "Waaberi",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"],
    isPaid: true,
  },
  {
    id: "r20",
    title: "House gooni ah oo Qoys",
    so: "Guri gooni ah oo 4 qol jiif ah",
    description: "House dabaq keli ah, deyr weyn iyo ammaan sugan.",
    price: 900,
    mainCategory: "RealEstate",
    category: ["Kirada"],
    subcategory: ["Guri gooni ah"],
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 2000,
    address: "Wadada Airport, Hodan",
    hasGarage: true,
    hasGarden: false,
    region: "Hamar",
    city: "Hodan",
    county: "Hodan",
    images: ["https://images.unsplash.com/photo-1448630360428-65456885c650"],
    isPaid: true,
  },
  {
    id: "r1",
    title: "Guri Cusub oo Iib ah",
    so: "Guri Cusub oo Xaafadda Deggan",
    description: "Guri waasac ah oo 4 qol jiif ah, leh beero iyo garaash.",
    price: 65000,
    mainCategory: "RealEstate",
    category: ["Iib"],
    subcategory: ["Guri cusub"],
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2200,
    address: "Wadada Sodonka, Kaaraan",
    hasGarage: true,
    hasGarden: true,
    region: "Hamar",
    city: "Karaan",
    county: "Karaan",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750"],
    isPaid: true,
  },
  {
    id: "r2",
    title: "Guri Dabaq iib ah",
    so: "Guri dabaq iib ah oo casri ah",
    description: "Apartment qurxoon oo ku yaal bartamaha magaalada.",
    price: 45000,
    mainCategory: "RealEstate",
    category: ["Iib"],
    subcategory: ["Guri dabaq iib ah"],
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    address: "Wadada Maka Al-mukarama",
    hasGarage: false,
    hasGarden: false,
    region: "Hamar",
    city: "Hodan",
    county: "Hodan",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267"],
    isPaid: true,
  },
  {
    id: "L1",
    title: "Dhul Degganaan ah",
    so: "Boos deegaan oo 15x20 ah",
    description: "Dhul ku habboon dhismaha guri qoys, biyo iyo koronto leh.",
    price: 15000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Degganaan"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 3000,
    address: "Xaafada Dayniile",
    hasGarage: false,
    hasGarden: false,
    region: "Hamar",
    city: "Dharkeynley",
    county: "Dharkeynley",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef"],
    isPaid: true,
  },
  {
    id: "L2",
    title: "Dhul Ganacsi",
    so: "Boos ganacsi oo wadada weyn saaran",
    description: "Dhul ku yaal wadada weyn, ku fiican dhismaha dukaamada.",
    price: 85000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Ganacsi"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 5000,
    address: "Wadada 21 October",
    hasGarage: false,
    hasGarden: false,
    region: "Hamar",
    city: "Waaberi",
    county: "Waaberi",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab"],
    isPaid: true,
  },
  {
    id: "F1",
    title: "Dhul Beereed",
    so: "Beer wax soo saar leh oo Afgooye ah",
    description: "Beer leh matoor biyo iyo geedo waaweyn.",
    price: 35000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Dhul Beereed"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 100000,
    address: "Duleedka Afgooye",
    hasGarage: false,
    hasGarden: true,
    region: "Shabeellaha Hoose",
    city: "Afgooye",
    county: "Afgooye",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef"],
    isPaid: true,
  },
  {
    id: "F2",
    title: "Beerta Xoolaha",
    so: "Beer ku habboon dhaqashada xoolaha",
    description: "Beer deyr leh oo leh xeryo loogu talagalay xoolaha.",
    price: 40000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Beerta Xoolaha"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 150000,
    address: "Wadada Jowhar",
    hasGarage: false,
    hasGarden: true,
    region: "Shabeellaha Dhexe",
    city: "Balcad",
    county: "Balcad",
    images: ["https://images.unsplash.com/photo-1500937386664-56d1dfef3854"],
    isPaid: true,
  },
  {
    id: "C1",
    title: "Goob tafaariiq",
    so: "Bakhaar iyo dukaan ku yaal suuqa",
    description: "Goob ganacsi oo ku fiican tafaariiqda, amnigeeda la sugay.",
    price: 1200,
    mainCategory: "RealEstate",
    category: ["Ganacsi"],
    subcategory: ["Goob tafaariiq"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 800,
    address: "Suuqa Bakaaraha",
    hasGarage: false,
    hasGarden: false,
    region: "Hamar",
    city: "Hawl Wadaag",
    county: "Hawl Wadaag",
    images: ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48"],
    isPaid: true,
  },
  {
    id: "C2",
    title: "Dhismaha Ganacsiga",
    so: "Dhismaha weyn oo ganacsi loogu talagalay",
    description: "Dhismaha ka kooban 3 dabaq oo loogu talagalay ganacsiga.",
    price: 5000,
    mainCategory: "RealEstate",
    category: ["Ganacsi"],
    subcategory: ["Dhismaha Ganacsiga"],
    bedrooms: 0,
    bathrooms: 4,
    squareFeet: 6000,
    address: "Wadada Makka Al Mukarama",
    hasGarage: true,
    hasGarden: false,
    region: "Hamar",
    city: "Hodan",
    county: "Hodan",
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c"],
    isPaid: true,
  },
  {
    id: "f1-extended",
    title: "Beer Weyn oo Afgooye ah",
    so: "Beer wax soo saar leh oo ku taal Afgooye",
    description:
      "Beer weyn oo leh matoor biyo, geedo mirood ah, iyo dhul ku habboon beerashada khudaarta.",
    price: 45000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Dhul Beereed"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 50000,
    address: "Wadada Afgooye, Duleedka Muqdisho",
    hasGarage: false,
    hasGarden: true,
    region: "Shabeellaha Hoose",
    city: "Afgooye",
    county: "Afgooye",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399",
      "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad",
    ],
    isPaid: true,
  },
  {
    id: "f2-extended",
    title: "Beerta Xoolaha ee Balcad",
    so: "Beer loogu talagalay dhaqashada xoolaha",
    description:
      "Goob ku habboon xoolaha, leh xeryo diyaarsan, deyr adag, iyo biyo joogto ah.",
    price: 38000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Beerta Xoolaha"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 40000,
    address: "Wadada Jowhar, Balcad",
    hasGarage: false,
    hasGarden: true,
    region: "Shabeellaha Dhexe",
    city: "Balcad",
    county: "Balcad",
    images: [
      "https://images.unsplash.com/photo-1516467508483-a7212febe31a",
      "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2",
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854",
    ],
    isPaid: true,
  },
  {
    id: "f3",
    title: "Beer Geedaha Miraha",
    so: "Beer leh liin, cambe iyo babay",
    description:
      "Beer si fiican u camiran oo ku taal meel ammaan ah, leh matoorka waraabka oo casri ah.",
    price: 55000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Agricultural Land"],
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 60000,
    address: "Agagaarka Ceelasha Biyaha",
    hasGarage: true,
    hasGarden: true,
    region: "Shabeellaha Hoose",
    city: "Afgooye",
    county: "Afgooye",
    images: [
      "https://images.unsplash.com/photo-1592419044706-39796d40f98c",
      "https://images.unsplash.com/photo-1589923188900-85dae523342a",
      "https://images.unsplash.com/photo-1560493676-04071c5f467b",
    ],
    isPaid: true,
  },

  {
    id: "r2",
    title: "Guri Dabaq iib ah",
    so: "Guri dabaq iib ah oo casri ah",
    description: "Apartment qurxoon oo ku yaal bartamaha magaalada.",
    price: 45000,
    mainCategory: "RealEstate",
    category: ["Iib"],
    subcategory: ["Guri dabaq iib ah"],
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    address: "Wadada Maka Al-mukarama",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Hodan",
    county: "Hodan",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267"],
    isPaid: true,
  },
  {
    id: "L1",
    title: "Dhul Degganaan ah",
    so: "Boos deegaan oo 15x20 ah",
    description: "Dhul ku habboon dhismaha guri qoys, biyo iyo koronto leh.",
    price: 15000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Degganaan"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 3000,
    address: "Xaafada Dayniile",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Dayniile",
    county: "Dayniile",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef"],
    isPaid: true,
  },
  {
    id: "L2",
    title: "Dhul Ganacsi",
    so: "Boos ganacsi oo wadada weyn saaran",
    description: "Dhul ku yaal wadada weyn, ku fiican dhismaha dukaamada.",
    price: 85000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Ganacsi"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 5000,
    address: "Wadada 21 October",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Waaberi",
    county: "Waaberi",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab"],
    isPaid: true,
  },
  {
    id: "F1",
    title: "Dhul Beereed",
    so: "Beer wax soo saar leh oo Afgooye ah",
    description: "Beer leh matoor biyo iyo geedo waaweyn.",
    price: 35000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Dhul Beereed"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 100000,
    address: "Duleedka Afgooye",
    hasGarage: false,
    hasGarden: true,
    region: "Lower Shabelle",
    city: "Afgooye",
    county: "Afgooye",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef"],
    isPaid: true,
  },
  {
    id: "F2",
    title: "Beerta Xoolaha",
    so: "Beer ku habboon dhaqashada xoolaha",
    description: "Beer deyr leh oo leh xeryo loogu talagalay xoolaha.",
    price: 40000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Beerta Xoolaha"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 150000,
    address: "Wadada Jowhar",
    hasGarage: false,
    hasGarden: true,
    region: "Middle Shabelle",
    city: "Balcad",
    county: "Balcad",
    images: ["https://images.unsplash.com/photo-1500937386664-56d1dfef3854"],
    isPaid: true,
  },
  {
    id: "C1",
    title: "Goob tafaariiq",
    so: "Bakhaar iyo dukaan ku yaal suuqa",
    description: "Goob ganacsi oo ku fiican tafaariiqda, amnigeeda la sugay.",
    price: 1200,
    mainCategory: "RealEstate",
    category: ["Ganacsi"],
    subcategory: ["Goob tafaariiq"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 800,
    address: "Suuqa Bakaaraha",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Howlwadaag",
    county: "Howlwadaag",
    images: ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48"],
    isPaid: true,
  },
  {
    id: "C2",
    title: "Dhismaha Ganacsiga",
    so: "Dhismaha weyn oo ganacsi loogu talagalay",
    description: "Dhismaha ka kooban 3 dabaq oo loogu talagalay ganacsiga.",
    price: 5000,
    mainCategory: "RealEstate",
    category: ["Ganacsi"],
    subcategory: ["Dhismaha Ganacsiga"],
    bedrooms: 0,
    bathrooms: 4,
    squareFeet: 6000,
    address: "Wadada Makka Al Mukarama",
    hasGarage: true,
    hasGarden: false,
    region: "Banaadir",
    city: "Hodan",
    county: "Hodan",
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c"],
    isPaid: true,
  },

  {
    id: "r6",
    title: "Guri dabaq (Apartment) Kiro ah",
    so: "Guri Kiro ah oo 3 Qol jiif ah",
    description:
      "Guri dabaq ah ku yaal Xamar-weyne, ku habboon qoysaska yar yar.",
    price: 500,
    mainCategory: "RealEstate",
    category: ["Kirada"],
    subcategory: ["Guri dabaq ah"],
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1100,
    address: "Wadada Sanca, Waaberi",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Waaberi",
    county: "Waaberi",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    ],
    isPaid: true,
  },
  {
    id: "r20",
    title: "House gooni ah oo Qoys",
    so: "Guri gooni ah oo 4 qol jiif ah",
    description: "House dabaq keli ah, deyr weyn iyo ammaan sugan.",
    price: 900,
    mainCategory: "RealEstate",
    category: ["Kirada"],
    subcategory: ["Guri gooni ah"],
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 2000,
    address: "Wadada Airport, Hodan",
    hasGarage: true,
    hasGarden: false,
    region: "Banaadir",
    city: "Hodan",
    county: "Hodan",
    images: [
      "https://images.unsplash.com/photo-1448630360428-65456885c650",
      "https://images.unsplash.com/photo-1475855581690-80accde3ae2b",
      "https://images.unsplash.com/photo-1416331108676-a22ccb276e35",
    ],
    isPaid: true,
  },
  {
    id: "f1",
    title: "Beer Weyn oo Afgooye ah",
    so: "Beer wax soo saar leh oo ku taal Afgooye",
    description:
      "Beer weyn oo leh matoor biyo, geedo mirood ah, iyo dhul ku habboon beerashada khudaarta.",
    price: 45000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Dhul Beereed"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 50000,
    address: "Wadada Afgooye, Duleedka Muqdisho",
    hasGarage: false,
    hasGarden: true,
    region: "Banaadir",
    city: "Dayniile",
    county: "Dayniile",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399",
      "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad",
    ],
    isPaid: true,
  },
  {
    id: "f2",
    title: "Beerta Xoolaha ee Balcad",
    so: "Beer loogu talagalay dhaqashada xoolaha",
    description:
      "Goob ku habboon xoolaha, leh xeryo diyaarsan, deyr adag, iyo biyo joogto ah.",
    price: 38000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Beerta Xoolaha"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 40000,
    address: "Wadada Jowhar, Balcad",
    hasGarage: false,
    hasGarden: true,
    region: "Banaadir",
    city: "Yaaqshiid",
    county: "Yaaqshiid",
    images: [
      "https://images.unsplash.com/photo-1516467508483-a7212febe31a",
      "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2",
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854",
    ],
    isPaid: true,
  },
  {
    id: "f3",
    title: "Beer Geedaha Miraha",
    so: "Beer leh liin, cambe iyo babay",
    description:
      "Beer si fiican u camiran oo ku taal meel ammaan ah, leh matoorka waraabka oo casri ah.",
    price: 55000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Agricultural Land"],
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 60000,
    address: "Agagaarka Ceelasha Biyaha",
    hasGarage: true,
    hasGarden: true,
    region: "Banaadir",
    city: "Hodan",
    county: "Hodan",
    images: [
      "https://images.unsplash.com/photo-1592419044706-39796d40f98c",
      "https://images.unsplash.com/photo-1589923188900-85dae523342a",
      "https://images.unsplash.com/photo-1560493676-04071c5f467b",
    ],
    isPaid: true,
  },
  {
    id: "r1",
    title: "Guri Cusub oo Iib ah",
    so: "Guri Cusub oo Xaafadda Deggan",
    description: "Guri waasac ah oo 4 qol jiif ah, leh beero iyo garaash.",
    price: 65000,
    mainCategory: "RealEstate",
    category: ["Iib"],
    subcategory: ["Guri cusub"],
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2200,
    address: "Wadada Sodonka, Kaaraan",
    hasGarage: true,
    hasGarden: true,
    region: "Banaadir",
    city: "Kaaraan",
    county: "Kaaraan",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
    ],
    isPaid: true,
  },
  {
    id: "r2",
    title: "Guri Dabaq iib ah",
    so: "Guri dabaq iib ah oo casri ah",
    description: "Apartment qurxoon oo ku yaal bartamaha magaalada.",
    price: 45000,
    mainCategory: "RealEstate",
    category: ["Iib"],
    subcategory: ["Guri dabaq iib ah"],
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    address: "Wadada Maka Al-mukarama",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Hodan",
    county: "Hodan",
    images: [
      "https://images.unsplash.com/photo-1515263487990-61b07816b324",
      "https://images.unsplash.com/photo-1499916078039-922301b0eb9b",
      "https://images.unsplash.com/photo-1505691938895-1758d7eaa511",
    ],
    isPaid: true,
  },
  {
    id: "L1",
    title: "Dhul Degganaan ah",
    so: "Boos deegaan oo 15x20 ah",
    description: "Dhul ku habboon dhismaha guri qoys, biyo iyo koronto leh.",
    price: 15000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Degganaan"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 3000,
    address: "Xaafada Dayniile",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Dayniile",
    county: "Dayniile",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854",
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9",
    ],
    isPaid: true,
  },
  {
    id: "L2",
    title: "Dhul Ganacsi",
    so: "Boos ganacsi oo wadada weyn saaran",
    description: "Dhul ku yaal wadada weyn, ku fiican dhismaha dukaamada.",
    price: 85000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Ganacsi"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 5000,
    address: "Wadada 21 October",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Waaberi",
    county: "Waaberi",
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab",
      "https://images.unsplash.com/photo-1497366216548-37526070297c",
      "https://images.unsplash.com/photo-1431540015161-0bf868a2d407",
    ],
    isPaid: true,
  },
  {
    id: "F1",
    title: "Dhul Beereed",
    so: "Beer wax soo saar leh oo Afgooye ah",
    description: "Beer leh matoor biyo iyo geedo waaweyn.",
    price: 35000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Dhul Beereed"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 100000,
    address: "Duleedka Afgooye",
    hasGarage: false,
    hasGarden: true,
    region: "Lower Shabelle",
    city: "Afgooye",
    county: "Afgooye",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399",
      "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad",
    ],
    isPaid: true,
  },
  {
    id: "F2",
    title: "Beerta Xoolaha",
    so: "Beer ku habboon dhaqashada xoolaha",
    description: "Beer deyr leh oo leh xeryo loogu talagalay xoolaha.",
    price: 40000,
    mainCategory: "RealEstate",
    category: ["farm for sale"],
    subcategory: ["Beerta Xoolaha"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 150000,
    address: "Wadada Jowhar",
    hasGarage: false,
    hasGarden: true,
    region: "Middle Shabelle",
    city: "Balcad",
    county: "Balcad",
    images: [
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854",
      "https://images.unsplash.com/photo-1516467508483-a7212febe31a",
      "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2",
    ],
    isPaid: true,
  },
  {
    id: "C1",
    title: "Goob tafaariiq",
    so: "Bakhaar iyo dukaan ku yaal suuqa",
    description: "Goob ganacsi oo ku fiican tafaariiqda, amnigeeda la sugay.",
    price: 1200,
    mainCategory: "RealEstate",
    category: ["Ganacsi"],
    subcategory: ["Goob tafaariiq"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 800,
    address: "Suuqa Bakaaraha",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Howlwadaag",
    county: "Howlwadaag",
    images: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48",
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad",
      "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a",
    ],
    isPaid: true,
  },
  {
    id: "C2",
    title: "Dhismaha Ganacsiga",
    so: "Dhismaha weyn oo ganacsi loogu talagalay",
    description: "Dhismaha ka kooban 3 dabaq oo loogu talagalay ganacsiga.",
    price: 5000,
    mainCategory: "RealEstate",
    category: ["Ganacsi"],
    subcategory: ["Dhismaha Ganacsiga"],
    bedrooms: 0,
    bathrooms: 4,
    squareFeet: 6000,
    address: "Wadada Makka Al Mukarama",
    hasGarage: true,
    hasGarden: false,
    region: "Banaadir",
    city: "Hodan",
    county: "Hodan",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174",
      "https://images.unsplash.com/photo-1504386106331-3e4e71712b38",
    ],
    isPaid: true,
  },
  {
    id: "L1-new",
    title: "Dhul Degganaan ah",
    so: "Boos deegaan oo 15x20 ah",
    description: "Dhul ku habboon dhismaha guri qoys, biyo iyo koronto leh.",
    price: 15000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Degganaan"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 3000,
    address: "Xaafada Dayniile",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Dayniile",
    county: "Dayniile",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854",
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9",
    ],
    isPaid: true,
  },
  {
    id: "L2-new",
    title: "Dhul Ganacsi",
    so: "Boos ganacsi oo wadada weyn saaran",
    description: "Dhul ku yaal wadada weyn, ku fiican dhismaha dukaamada.",
    price: 85000,
    mainCategory: "RealEstate",
    category: ["Dhul iib ah"],
    subcategory: ["Dhul Ganacsi"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 5000,
    address: "Wadada 21 October",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Waaberi",
    county: "Waaberi",
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab",
      "https://images.unsplash.com/photo-1497366216548-37526070297c",
      "https://images.unsplash.com/photo-1431540015161-0bf868a2d407",
    ],
    isPaid: true,
  },
];
