export interface RealEstateItem {
  id: string;
  title: string;
  so: string;
  description: string;
  price: number;
  mainCategory: string;
  category: string[];
  subcategory: string[]; // This will now contain only one Somali identifier
  bedrooms: number;
  bathrooms: number;
  squareFeet: number;
  address: string;
  hasGarage: boolean;
  hasGarden: boolean;
  region: string;
  city: string;
  district: string;
  county: string;
  subDistrict: string;
  images: string[];
}

export const realEstateItems: RealEstateItem[] = [
  // --- FOR SALE (Iib) ---
  {
    id: "r1",
    title: "Guri Cusub oo Xaafadda Deggan ku yaal",
    so: "Guri Cusub oo Xaafadda Deggan ku yaal",
    description:
      "Guri waasac ah oo 4 qol jiif ah, leh beero iyo garaash, ku yaal xaafad aamusan.",
    price: 60000,
    mainCategory: "RealEstate",
    category: ["For Sale"],
    subcategory: ["Guri cusub"],
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2200,
    address: "Wadada Sodonka, Guri No. 15",
    hasGarage: true,
    hasGarden: true,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    county: "Kaaraan",
    subDistrict: "Xaafada Siinaay",
    images: [
      "https://images.unsplash.com/photo-1742499168697-e737eeb3d201?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1644185436036-c278d4dc2059?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r2",
    title: "Apartment Casri ah oo Magaalada Dhexdeeda ah",
    so: "Apartment Casri ah oo Magaalada Dhexdeeda ah",
    description:
      "Guri dabaq ah oo ku yaal suuqa magaalada, oo leh 2 qol, balakoon, iyo adeegyo casri ah.",
    price: 35000,
    mainCategory: "RealEstate",
    category: ["For Sale"],
    subcategory: ["Guri dabaq iib ah"],
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1000,
    address: "Agagaarka Suuqa Waaheen",
    hasGarage: false,
    hasGarden: false,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Maxamed Mooge",
    county: "Gacan Libaax",
    subDistrict: "Xaafada New Hargeysa",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=500&auto=format&fit=crop&q=60",
      "https://plus.unsplash.com/premium-photo-1682377521741-66b111791809?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r3",
    title: "Guri Dhexe oo Dhul Balaaran leh",
    so: "Guri Dhexe oo Dhul Balaaran leh",
    description:
      "Guri yar oo dhulkiisu ballaaran yahay, beero iyo baarkin ku habboon.",
    price: 20000,
    mainCategory: "RealEstate",
    category: ["For Sale"],
    subcategory: ["Guri la isticmaalay"],
    bedrooms: 3,
    bathrooms: 1,
    squareFeet: 1500,
    address: "Duleedka Magaalada, Wadada Balcad",
    hasGarage: false,
    hasGarden: true,
    region: "Shabeellaha Dhexe",
    city: "Jowhar",
    district: "Jowhar",
    county: "Mahaday",
    subDistrict: "Xaafada Horseed",
    images: [
      "https://images.unsplash.com/photo-1649281808638-4c340553a2b0?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r4",
    title: "Villa Raaxo ah oo Badda u Dhow",
    so: "Villa Raaxo ah oo Badda u Dhow",
    description:
      "Villa weyn oo 5 qol jiif ah, u dhow xeebta, oo leh beero qurxoon.",
    price: 95000,
    mainCategory: "RealEstate",
    category: ["For Sale"],
    subcategory: ["Guri cusub"],
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3500,
    address: "Xeebta Liido, Wadada Jaalle Siyaad",
    hasGarage: true,
    hasGarden: true,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Cabdiasis",
    county: "Shangaani",
    subDistrict: "Xaafada Taleex",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1600585154280-df151d3e7f6c?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r11",
    title: "Guri iib ah oo Baadiyaha ku yaal",
    so: "Guri deggan oo qiimihiisu jaban yahay",
    description:
      "Guri laba qol ah, oo ku habboon degganaasho. Nalka iyo biyaha ayaa la heli karaa.",
    price: 8000,
    mainCategory: "RealEstate",
    category: ["For Sale"],
    subcategory: ["Guri la isticmaalay"],
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 900,
    address: "Meel u dhow Wadada Xamar",
    hasGarage: false,
    hasGarden: true,
    region: "Bay",
    city: "Baydhabo",
    district: "Baydhabo",
    county: "Diinsoor",
    subDistrict: "Xaafada Waaberi",
    images: [
      "https://images.unsplash.com/photo-1574362143719-79f6e5a6a6f1?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r15",
    title: "Villa Cusub oo Raaxo ah",
    so: "Villa cusub oo loogu talagalay dadka ladan",
    description:
      "Villa naqshad casri ah leh, 3 dabaq ah, oo ku taal meel aamin ah.",
    price: 120000,
    mainCategory: "RealEstate",
    category: ["For Sale"],
    subcategory: ["Guri cusub"],
    bedrooms: 6,
    bathrooms: 5,
    squareFeet: 4500,
    address: "Xaafada Guulwadayaasha, Wadada Airport",
    hasGarage: true,
    hasGarden: true,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Maxamed Mooge",
    county: "Gacan Libaax",
    subDistrict: "Xaafada New Hargeysa",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1600585154280-df151d3e7f6c?w=500&auto=format&fit=crop&q=60",
    ],
  },

  // --- FOR RENT (Kirada) ---
  {
    id: "r6",
    title: "Guri dabaq (Apartment) Kiro ah oo 3 Qol ah",
    so: "Guri Kiro ah oo 3 Qol jiif ah oo Waasac ah",
    description:
      "Guri dabaq ah/Apartment ku yaal Xamar-weyne, ku habboon qoysaska yar yar.",
    price: 500,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri dabaq ah"],
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1100,
    address: "Wadada Sanca, Guri 4",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Xamar Weyne",
    county: "Waaberi",
    subDistrict: "Xaafada Barwaaqo",
    images: [
      "https://images.unsplash.com/photo-1616047029548-fa2a8c3d8e57?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r16",
    title: "Guri Casri ah oo Flat Kirada ah",
    so: "Guri dabaq ah Flat oo casri ah oo laba qol leh",
    description:
      "Flat/Apartment dabaq cusub, leh balakoon wayn, goob amniga lagu ilaaliyo.",
    price: 750,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri dabaq ah"],
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 900,
    address: "Xaafada Guulwadayaasha",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    county: "Hodan",
    subDistrict: "Xaafada Siinaay",
    images: [
      "https://images.unsplash.com/photo-1570129477488-c07a3c3c52d0?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r17",
    title: "Apartment yar oo Degganaan u Fiican",
    so: "Guri dabaq yar oo loogu talagalay laba qof",
    description: "Apartment yar, qiimihiisu jaban yahay, u dhow suuqa.",
    price: 400,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri dabaq ah"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 600,
    address: "Bartamaha Degmada Xamar Jajab",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hamar Jajab",
    county: "Waaberi",
    subDistrict: "Xaafada Barwaaqo",
    images: [
      "https://images.unsplash.com/photo-1583608754291-a180126a1112?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r13",
    title: "Guri Dabaq (Flat) ah oo 4 Qol oo Kirada ah",
    so: "Guri weyn Flat oo kiro ah oo qoysaska waaweyn u fiican",
    description: "Guri dabaq weyn, oo afar qol jiif ah, meel deegaan u fiican.",
    price: 700,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri dabaq ah"],
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1400,
    address: "Wadada Afrikka, Xaafada Howlwadaag",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    county: "Yaaqshiid",
    subDistrict: "Xaafada Bulo Xuubey",
    images: [
      "https://images.unsplash.com/photo-1574362143719-79f6e5a6a6f1?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r19",
    title: "Villa Raaxo ah oo Baarkin leh",
    so: "Villa Kiro ah oo leh garaash laba baabuur qaada",
    description:
      "Villa weyn oo cusub, deyr wayn leh, iyo beero yaryar oo qurxoon. Waa House weyn.",
    price: 1200,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri gooni ah"],
    bedrooms: 5,
    bathrooms: 3,
    squareFeet: 3000,
    address: "Xaafada Xoosh, Hargeysa",
    hasGarage: true,
    hasGarden: true,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Axmed Dhagax",
    county: "Axmed Dhagax",
    subDistrict: "Xaafada Xoosh",
    images: [
      "https://images.unsplash.com/photo-1582268611958-ab88b273d408?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r20",
    title: "House gooni ah oo Qoys Kirada ah",
    so: "Guri gooni ah oo 4 qol jiif ah, House deggan",
    description:
      "House dabaq keli ah oo leh laba dabaq, deyr weyn iyo ammaan sugan.",
    price: 900,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri gooni ah"],
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 2000,
    address: "Wadada Airport, Muqdisho",
    hasGarage: true,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    county: "Hodan",
    subDistrict: "Xaafada Siinaay",
    images: [
      "https://images.unsplash.com/photo-1628004550186-b4d008515a4d?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r21",
    title: "Villa yar oo Kiro ah",
    so: "Villa yar oo 3 qol jiif ah oo ku taal meel aamusan",
    description: "Villa cusub oo naqshad qurxoon, ku yaal xaafad dhismo cusub.",
    price: 700,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri gooni ah"],
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1500,
    address: "Degmada Ceelasha Biyaha",
    hasGarage: false,
    hasGarden: true,
    region: "Shabeellaha Hoose",
    city: "Marka",
    district: "Marka",
    county: "Qoryooley",
    subDistrict: "Beerta Nadiif",
    images: [
      "https://images.unsplash.com/photo-1600585153492-f046f88d75e2?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r22",
    title: "House gooni ah oo beerta ka agdhow",
    so: "Guri cusub oo House ah beerta dhexe u dhow, oo waasac ah",
    description:
      "House dabaq leh, dayr weyn, ku habboon degganaasho raaxo leh.",
    price: 1000,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Guri gooni ah"],
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2500,
    address: "Wadada Makka Al Mukarama",
    hasGarage: true,
    hasGarden: true,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    county: "Hodan",
    subDistrict: "Xaafada Taleex",
    images: [
      "https://images.unsplash.com/photo-1616763445585-6490333b0ed5?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r31",
    title: "Single Room Keli ah oo Kiro ah",
    so: "Qol yar oo ardayda u fiican, meel deggan",
    description: "Single Room keli ah oo leh musqul gooni ah, u dhow jaamacad.",
    price: 150,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Qol keli ah"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 250,
    address: "Agagaarka Jaamacadda Muqdisho",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    county: "Yaaqshiid",
    subDistrict: "Xaafada Bulo Xuubey",
    images: [
      "https://images.unsplash.com/photo-1549488827-023a1a3e6f96?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r32",
    title: "Qol Keli ah (Room) oo Casri ah",
    so: "Qol cusub oo casri ah oo shaqaalaha u fiican",
    description:
      "Room yar oo leh adeegyo dhameystiran, amniga sare la ilaaliyo.",
    price: 200,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Qol keli ah"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 300,
    address: "Bartamaha Degmada Xamar Weyne",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Xamar Weyne",
    county: "Waaberi",
    subDistrict: "Xaafada Barwaaqo",
    images: [
      "https://images.unsplash.com/photo-1509614474441-2a1e1b1d7d02?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r33",
    title: "Qol Keli ah (Room) oo Beerta u Dhow",
    so: "Qol keli ah oo u dhow beerta, jawiga fiican",
    description: "Room weyn oo hawo fiican, ku yaal xaafad aamusan.",
    price: 120,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Qol keli ah"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 200,
    address: "Wadada Sodonka, Xaafada Siinaay",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Hodan",
    county: "Kaaraan",
    subDistrict: "Xaafada Siinaay",
    images: [
      "https://images.unsplash.com/photo-1518731448806-c8f4204d553e?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r34",
    title: "Single Room Keli ah oo ku yaal Agagaarka Jaamacadda",
    so: "Qol Kiro ah oo Jaamacadda u dhow",
    description: "Single Room ku habboon ardayda ama shaqaalaha, meel deggan.",
    price: 150,
    mainCategory: "RealEstate",
    category: ["For Rent"],
    subcategory: ["Qol keli ah"],
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 500,
    address: "Wadada Xaafada, Ka soo horjeedka Jaamacadda",
    hasGarage: false,
    hasGarden: false,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Cabdi Aadan",
    county: "26 June",
    subDistrict: "Xaafada Macallinka",
    images: [
      "https://images.unsplash.com/photo-1549488827-023a1a3e6f96?w=500&auto=format&fit=crop&q=60",
    ],
  },

  // --- LAND FOR SALE (Dhul iib ah) ---
  {
    id: "r5",
    title: "Dhul iib ah (Lot)",
    so: "Dhul iib ah oo Dhismihiisu u Wanaagsan Yahay",
    description: "Dhul beero iyo guri u wanaagsan, oo ku yaal meel deggan.",
    price: 15000,
    mainCategory: "RealEstate",
    category: ["Land for Sale"],
    subcategory: ["Dhul Degganaan"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 6000,
    address: "Meel u dhow Wadada Airport-ka",
    hasGarage: false,
    hasGarden: false,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Axmed Dhagax",
    county: "Daami",
    subDistrict: "Xaafada Cali Xuseen",
    images: [
      "https://media.istockphoto-photo/id/1324329244/photo/vacant-lot-for-sale.webp?b=1&s=170667a&w=0&k=20&c=p-bN-1f-P7K281_c1fS4L5w8L1iK2lQ3P6z5_FwG69c=",
    ],
  },
  {
    id: "r10",
    title: "Dhul iib ah oo Xeebeed",
    so: "Dhul ku yaal Xeebta, Dalxiis u fiican",
    description:
      "Dhul qurxoon oo ku yaal xeebta, oo u fiican in laga dhiso Hotel ama Villa.",
    price: 80000,
    mainCategory: "RealEstate",
    category: ["Land for Sale"],
    subcategory: ["Dhul Ganacsi"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 7500,
    address: "Xeebta Saaxiil",
    hasGarage: false,
    hasGarden: false,
    region: "Bari",
    city: "Boosaaso",
    district: "Boosaaso",
    county: "Waaciye",
    subDistrict: "Agagaarka Dekeda",
    images: [
      "https://images.unsplash.com/photo-1628126867761-4c12d59f3d9f?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r14",
    title: "Dhul iib ah oo Magaalada Dhexe ah",
    so: "Dhul muhiim ah oo dhismaha ganacsiga u fiican",
    description: "Dhul ku yaal bartamaha degmada, u dhow xafiisyada dowladda.",
    price: 30000,
    mainCategory: "RealEstate",
    category: ["Land for Sale"],
    subcategory: ["Dhul Ganacsi"],
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 4000,
    address: "Wadada Xorriyadda, Bartamaha Degmada",
    hasGarage: false,
    hasGarden: false,
    region: "Galgaduud",
    city: "Cadaado",
    district: "Cadaado",
    county: "Cadaado",
    subDistrict: "Xaafada Wadani",
    images: [
      "https://media.istockphoto-photo/id/1324329244/photo/vacant-lot-for-sale.webp?b=1&s=170667a&w=0&k=20&c=p-bN-1f-P7K281_c1fS4L5w8L1iK2lQ3P6z5_FwG69c=",
    ],
  },

  // --- FARM FOR SALE (Beer iib ah) ---
  {
    id: "r8",
    title: "Aqalka Beeraleyda (Farm House)",
    so: "Guri Beeraleyda ama Xoolo Dhaqashada u Fiican",
    description:
      "Dhul ballaaran oo leh guri yar, waraabka wuu u dhow yahay, wuxuuna ku fiican yahay tacabka.",
    price: 30000,
    mainCategory: "RealEstate",
    category: ["Farm for Sale"],
    subcategory: ["Dhul Beereed"],
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 40000,
    address: "Banki Weyne, Wabiga Shabeelle Duleedkiisa",
    hasGarage: false,
    hasGarden: true,
    region: "Shabeellaha Hoose",
    city: "Marka",
    district: "Marka",
    county: "Qoryooley",
    subDistrict: "Beerta Nadiif",
    images: [
      "https://images.unsplash.com/photo-1547492167-930985223c6c?w=500&auto=format&fit=crop&q=60",
    ],
  },

  // --- COMMERCIAL (Ganacsi) ---
  {
    id: "r23",
    title: "Xafiis Ganacsi (Commercial Office) oo Casri ah",
    so: "Xafiis ku yaal dabaqa kowaad ee dhismaha ganacsiga",
    description:
      "Xafiis Commercial Office weyn oo casri ah, qeyb qabale ah iyo qolal shaqo oo kala duwan.",
    price: 1500,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Xafiis Ganacsi"],
    bedrooms: 0,
    bathrooms: 2,
    squareFeet: 1200,
    address: "Dhismaha City Center, Bartamaha",
    hasGarage: false,
    hasGarden: false,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Maxamed Mooge",
    county: "Maxamed Mooge",
    subDistrict: "Xaafada New Hargeysa",
    images: [
      "https://images.unsplash.com/photo-1549887552-cb1071d3e86b?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r27",
    title: "Bakhaar Weyn oo Warehouse/Storage",
    so: "Bakhaar weyn oo ku habboon wax soo saarka iyo keydinta (Storage)",
    description:
      "Warehouse cusub oo dhererkiisu dheer yahay, oo leh albaab weyn oo xamuul qaadi kara.",
    price: 3000,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Bakhaar weyn"],
    bedrooms: 0,
    bathrooms: 2,
    squareFeet: 8000,
    address: "Aagga Warshadaha, Muqdisho",
    hasGarage: true,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Yaaqshiid",
    county: "Yaaqshiid",
    subDistrict: "Xaafada Bulo Xuubey",
    images: [
      "https://images.unsplash.com/photo-1579895024443-34e8574c3e38?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r12",
    title: "Goob Ganacsi (Shop) oo Suuqa dhexdiisa ah",
    so: "Dukaan kireeya meel mashquul ah",
    description:
      "Dukaan weyn oo ganacsi, meel muhiim ah oo macaamiil badan tagto.",
    price: 800,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Goob tafaariiq"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 700,
    address: "Suuqa Muhiimka ah ee Baydhabo",
    hasGarage: false,
    hasGarden: false,
    region: "Bay",
    city: "Baydhabo",
    district: "Baydhabo",
    county: "Diinsoor",
    subDistrict: "Xaafada Horseed",
    images: [
      "https://images.unsplash.com/photo-1558238779-11142517866e?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r7",
    title: "Townhouse oo Ganacsi u Fiican",
    so: "Guri Ganacsi u Dhow oo iib ah",
    description:
      "Guri townhouse oo ku yaal meel ganacsi u dhow, oo u furan in laba dabaq laga dhigo.",
    price: 45000,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Dhismaha Ganacsiga"],
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1800,
    address: "Agagaarka Garoonka Diyaaradaha",
    hasGarage: true,
    hasGarden: false,
    region: "Gedo",
    city: "Garbahareey",
    district: "Garbahareey",
    county: "Ceelwaaq",
    subDistrict: "Xaafada Garsoor",
    images: [
      "https://images.unsplash.com/photo-1574362143719-79f6e5a6a6f1?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r24",
    title: "Office yar oo Kirada ah",
    so: "Qol Office ah oo ku yaal meel ganacsi oo yar",
    description:
      "Office yar oo ku habboon bilawga ganacsiga, leh adeegyo dhameystiran.",
    price: 450,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Xafiis Ganacsi"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 400,
    address: "Wadada Ganacsiga, Garoowe",
    hasGarage: false,
    hasGarden: false,
    region: "Nugaal",
    city: "Garoowe",
    district: "Garoowe",
    county: "Garoowe",
    subDistrict: "Xaafada Hodan",
    images: [
      "https://images.unsplash.com/photo-1606787680213-91ac4101e4a2?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r25",
    title: "Xafiis weyn oo Office Kiro ah",
    so: "Xafiis loogu talagalay shirkad weyn, oo leh qolal shirarka",
    description:
      "Xafiis waasac ah oo 6 qol ah, leh qol shirarka casri ah iyo qabale.",
    price: 2500,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Dhismaha Ganacsiga"],
    bedrooms: 0,
    bathrooms: 3,
    squareFeet: 3000,
    address: "Dhismaha Hormuud, Muqdisho",
    hasGarage: true,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Xamar Weyne",
    county: "Waaberi",
    subDistrict: "Xaafada Barwaaqo",
    images: [
      "https://images.unsplash.com/photo-1517486413996-27a964f40f28?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r26",
    title: "Xafiis dabaq labaad oo Commercial Office ah",
    so: "Xafiis ku yaal dabaqa labaad ee goob muhiim ah",
    description:
      "Commercial Office dhexe oo amniga sare la ilaaliyo, u dhow bangiyada.",
    price: 800,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Xafiis Ganacsi"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 700,
    address: "Agagaarka Suuqa Waaheen, Hargeysa",
    hasGarage: false,
    hasGarden: false,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Maxamed Mooge",
    county: "Maxamed Mooge",
    subDistrict: "Xaafada New Hargeysa",
    images: [
      "https://images.unsplash.com/photo-1517976694663-e380540e137b?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r28",
    title: "Bakhaar yar oo Keydinta (Storage)",
    so: "Keyd yar oo alaabta lagu rarto, meel aamin ah (Warehouse)",
    description:
      "Warehouse/Storage yar oo u dhow dekeda, ku habboon alaab yar.",
    price: 800,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Bakhaar weyn"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 1500,
    address: "Agagaarka Dekeda Boosaaso",
    hasGarage: false,
    hasGarden: false,
    region: "Bari",
    city: "Boosaaso",
    district: "Boosaaso",
    county: "Waaciye",
    subDistrict: "Agagaarka Dekeda",
    images: [
      "https://images.unsplash.com/photo-1582736141386-351187d7b1e4?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r29",
    title: "Goob Keydinta (Storage) oo Waaweyn",
    so: "Bakhaar wayn oo aan dhameystirneyn, u furan in la habeeyo",
    description:
      "Warehouse dabaq weyn oo loo isticmaali karo keydinta iyo wax soo saarka fudud.",
    price: 2000,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Bakhaar weyn"],
    bedrooms: 0,
    bathrooms: 2,
    squareFeet: 5000,
    address: "Wadada Jigjiga, Hargeysa",
    hasGarage: true,
    hasGarden: false,
    region: "Maroodi Jeex",
    city: "Hargeysa",
    district: "Axmed Dhagax",
    county: "Axmed Dhagax",
    subDistrict: "Xaafada Xoosh",
    images: [
      "https://images.unsplash.com/photo-1599305141200-a549d4791c30?w=500&auto=format&fit=crop&q=60",
    ],
  },
  {
    id: "r30",
    title: "Warehouse Kirada ah oo Biyaha u Dhow",
    so: "Bakhaar u dhow xeebta, alaabta lagu kaydiyo Storage",
    description:
      "Goob keydin muhiim ah, waraabka wuu u dhow yahay, wuxuuna ku fiican yahay dhoofinta.",
    price: 1800,
    mainCategory: "RealEstate",
    category: ["Commercial"],
    subcategory: ["Bakhaar weyn"],
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 3500,
    address: "Xeebta Liido, Wadada Jaalle Siyaad",
    hasGarage: false,
    hasGarden: false,
    region: "Banaadir",
    city: "Muqdisho",
    district: "Cabdiasis",
    county: "Shangaani",
    subDistrict: "Xaafada Taleex",
    images: [
      "https://images.unsplash.com/photo-1574362143719-79f6e5a6a6f1?w=500&auto=format&fit=crop&q=60",
    ],
  },
];
