export const subscriptionItems = [
  {
    title: "Family Sedan Deals",
    category: "car",
    subCategory: "sedan",
    region: "Banadir",
    cities: ["Mogadishu"],
    selectedCityIds: [],
    customCities: [],
    priceMin: 10000,
    priceMax: 20000,
    isActive: true,
    status: "active",
    notificationCount: 0,
  },
  {
    title: "Affordable SUVs",
    category: "car",
    subCategory: "suv",
    region: "Bari",
    cities: ["Bosaso"],
    selectedCityIds: [],
    customCities: [],
    priceMin: 15000,
    priceMax: 30000,
    isActive: true,
    status: "active",
    notificationCount: 0,
  },
  {
    title: "City Hatchbacks",
    category: "car",
    subCategory: "hatchback",
    region: "Awdal",
    cities: ["Borama"],
    selectedCityIds: [],
    customCities: [],
    priceMin: 5000,
    priceMax: 15000,
    isActive: true,
    status: "active",
    notificationCount: 0,
  },
  {
    title: "Sport Motorcycles",
    category: "motorcycle",
    subCategory: "sport",
    region: "Shabeellaha Hoose",
    cities: ["Marka"],
    selectedCityIds: [],
    customCities: [],
    priceMin: 8000,
    priceMax: 20000,
    isActive: true,
    status: "active",
    notificationCount: 0,
  },
  {
    title: "Cruiser Bikes",
    category: "motorcycle",
    subCategory: "cruiser",
    region: "Bay",
    cities: ["Baydhabo"],
    selectedCityIds: [],
    customCities: [],
    priceMin: 6000,
    priceMax: 15000,
    isActive: true,
    status: "active",
    notificationCount: 0,
  },
  {
    title: "Touring Bikes",
    category: "motorcycle",
    subCategory: "touring",
    region: "Bakool",
    cities: ["Xudur"],
    selectedCityIds: [],
    customCities: [],
    priceMin: 12000,
    priceMax: 25000,
    isActive: true,
    status: "active",
    notificationCount: 0,
  },
  {
    title: "Offroad Adventures",
    category: "motorcycle",
    subCategory: "offroad",
    region: "Jubbada Hoose",
    cities: ["Kismaayo"],
    selectedCityIds: [],
    customCities: [],
    priceMin: 5000,
    priceMax: 12000,
    isActive: true,
    status: "active",
    notificationCount: 0,
  },
];
