export const subscriptionItems = [
  {
    category: "car",
    subCategory: "sedan",
    title: "Family Sedan Deals",
    priceMin: 10000,
    priceMax: 20000,
    region: "Banadir",
    city: "Mogadishu",
  },
  {
    category: "car",
    subCategory: "suv",
    title: "Affordable SUVs",
    priceMin: 15000,
    priceMax: 30000,
    region: "Bari",
    city: "Bosaso",
  },
  {
    category: "car",
    subCategory: "hatchback",
    title: "City Hatchbacks",
    priceMin: 5000,
    priceMax: 15000,
    region: "Awdal",
    city: "Borama",
  },

  {
    category: "motorcycle",
    subCategory: "sport",
    title: "Sport Motorcycles",
    priceMin: 8000,
    priceMax: 20000,
    region: "Shabeellaha Hoose",
    city: "Marka",
  },
  {
    category: "motorcycle",
    subCategory: "cruiser",
    title: "Cruiser Bikes",
    priceMin: 6000,
    priceMax: 15000,
    region: "Bay",
    city: "Baydhabo",
  },
  {
    category: "motorcycle",
    subCategory: "touring",
    title: "Touring Bikes",
    priceMin: 12000,
    priceMax: 25000,
    region: "Bakool",
    city: "Xudur",
  },
  {
    category: "motorcycle",
    subCategory: "offroad",
    title: "Offroad Adventures",
    priceMin: 5000,
    priceMax: 12000,
    region: "Jubbada Hoose",
    city: "Kismaayo",
  },
];
