export const subscriptionItems = [
  {
    category: "car",
    subCategory: "sedan",
    title: "Family Sedan Deals",
    priceMin: 10000,
    priceMax: 20000,
    region: "Banadir",
    city: "Mogadishu",
  },
  {
    category: "car",
    subCategory: "suv",
    title: "Affordable SUVs",
    priceMin: 15000,
    priceMax: 30000,
    region: "Bari",
    city: "Bosaso",
  },
  {
    category: "car",
    subCategory: "hatchback",
    title: "City Hatchbacks",
    priceMin: 5000,
    priceMax: 15000,
    region: "Awdal",
    city: "Borama",
  },
  {
    category: "car",
    subCategory: "coupe",
    title: "Sporty Coupes",
    priceMin: 20000,
    priceMax: 40000,
    region: "Mudug",
    city: "Gaalkacyo",
  },
  {
    category: "car",
    subCategory: "convertible",
    title: "Convertibles for Summer",
    priceMin: 25000,
    priceMax: 50000,
    region: "Hiiraan",
    city: "Beledweyne",
  },

  {
    category: "motorcycle",
    subCategory: "sport",
    title: "Sport Motorcycles",
    priceMin: 8000,
    priceMax: 20000,
    region: "Shabeellaha Hoose",
    city: "Marka",
  },
  {
    category: "motorcycle",
    subCategory: "cruiser",
    title: "Cruiser Bikes",
    priceMin: 6000,
    priceMax: 15000,
    region: "Bay",
    city: "Baydhabo",
  },
  {
    category: "motorcycle",
    subCategory: "touring",
    title: "Touring Bikes",
    priceMin: 12000,
    priceMax: 25000,
    region: "Bakool",
    city: "Xudur",
  },
  {
    category: "motorcycle",
    subCategory: "offroad",
    title: "Offroad Adventures",
    priceMin: 5000,
    priceMax: 12000,
    region: "Jubbada Hoose",
    city: "Kismaayo",
  },
  {
    category: "motorcycle",
    subCategory: "scooter",
    title: "Daily Commuter Scooters",
    priceMin: 2000,
    priceMax: 8000,
    region: "Shabeellaha Dhexe",
    city: "Jowhar",
  },

  {
    category: "boat",
    subCategory: "fishing",
    title: "Fishing Boats",
    priceMin: 10000,
    priceMax: 25000,
    region: "Gedo",
    city: "Beled Xaawo",
  },
  {
    category: "boat",
    subCategory: "yacht",
    title: "Luxury Yachts",
    priceMin: 100000,
    priceMax: 500000,
    region: "Jubbada Dhexe",
    city: "Bu'aale",
  },
  {
    category: "boat",
    subCategory: "sailboat",
    title: "Affordable Sailboats",
    priceMin: 20000,
    priceMax: 60000,
    region: "Nugaal",
    city: "Garowe",
  },
  {
    category: "boat",
    subCategory: "speedboat",
    title: "Speedboats for Fun",
    priceMin: 30000,
    priceMax: 100000,
    region: "Sool",
    city: "Laascaanood",
  },
  {
    category: "boat",
    subCategory: "jet-ski",
    title: "Jet Skis",
    priceMin: 8000,
    priceMax: 20000,
    region: "Togdheer",
    city: "Burco",
  },

  {
    category: "real_estate",
    subCategory: "apartment",
    title: "City Apartments",
    priceMin: 50000,
    priceMax: 150000,
    region: "Banadir",
    city: "Mogadishu",
  },
];
