import { z } from "zod";
import * as s from "../core/utils/sanitize.ts";

export const createBoatSchema = z.object({
  userId: z.string().min(1).max(128),
  title: s.title,
  description: s.description.optional(),
  price: s.price(),
  mainCategory: s.shortStr("Category"),
  category: z.array(s.shortStr()).max(5),
  subcategory: z.array(s.shortStr()).max(5),
  type: s.optShortStr(),
  make: s.optShortStr(),
  boatModel: s.optShortStr(),
  year: z.number().int().min(1900).max(2100).optional(),
  mileage: z.number().min(0).max(10_000_000).optional(),
  transmission: s.optShortStr(),
  fuelType: s.optShortStr(),
  color: s.optShortStr(),
  condition: s.optShortStr(),
  region: s.shortStr("Region"),
  city: s.shortStr("City"),
  images: s.images,
  businessId: z.string().max(128).optional(),
  website: z.string().url().max(512).optional().or(z.literal("")),
  isPaid: z.boolean().optional(),
  planId: z.string().max(128).optional(),
  planAmount: z.number().min(0).max(s.LIMITS.PRICE_MAX).optional(),
  feeId: z.string().max(128).optional(),
  feeAmount: z.number().min(0).max(s.LIMITS.PRICE_MAX).optional(),
});
