import { z } from "zod";
import * as s from "../core/utils/sanitize.ts";

export const createCarSchema = z.object({
  userId: z.string().min(1).max(128),
  title: s.title,
  description: s.description.optional(),
  price: s.price(),
  mainCategory: s.shortStr("Category"),
  category: z.array(s.shortStr()).max(5),
  subcategory: z.array(s.shortStr()).max(5),
  name: s.optShortStr(),
  brand: s.optShortStr(),
  make: s.optShortStr(),
  vehicleModel: s.optShortStr(),
  model: s.optShortStr(),
  trim: s.optShortStr(),
  year: z.union([z.number().int().min(1900).max(2100), z.string().max(10)]).optional(),
  mileage: z.union([z.number().min(0).max(10_000_000), z.string().max(20)]).optional(),
  transmission: s.optShortStr(),
  gearbox: s.optShortStr(),
  engineSize: s.optShortStr(),
  fuelType: s.optShortStr(),
  condition: s.optShortStr(),
  color: s.optShortStr(),
  doors: z.union([z.number().int().min(1).max(10), z.string().max(5)]).optional(),
  region: s.shortStr("Region"),
  city: s.shortStr("City"),
  images: s.images,
  isPaid: z.boolean().optional(),
  planId: z.string().max(128).optional(),
  planAmount: z.number().min(0).max(s.LIMITS.PRICE_MAX).optional(),
  feeId: z.string().max(128).optional(),
  feeAmount: z.number().min(0).max(s.LIMITS.PRICE_MAX).optional(),
  businessId: z.string().max(128).optional(),
  website: z.string().url().max(512).optional().or(z.literal("")),
});

export const carQuerySchema = z.object({
  type: z.string().max(100).optional(),
  listingType: z.string().max(50).optional(),
  region: z.string().max(100).optional(),
  city: z.string().max(100).optional(),
  district: z.string().max(100).optional(),
  subcategory: z.string().max(100).optional(),
  category: z.string().max(100).optional(),
});
