import { z } from "zod";

export const createCarSchema = z.object({
  userId: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
  price: z.number(),
  mainCategory: z.string().min(1),
  category: z.array(z.string()),
  subcategory: z.array(z.string()),
  name: z.string().optional(),
  brand: z.string().optional(),
  make: z.string().optional(),
  vehicleModel: z.string().optional(),
  model: z.string().optional(),
  trim: z.string().optional(),
  year: z.union([z.number(), z.string()]).optional(),
  mileage: z.union([z.number(), z.string()]).optional(),
  transmission: z.string().optional(),
  gearbox: z.string().optional(),
  engineSize: z.string().optional(),
  fuelType: z.string().optional(),
  condition: z.string().optional(),
  color: z.string().optional(),
  doors: z.union([z.number(), z.string()]).optional(),
  region: z.string().min(1),
  city: z.string().min(1),
  images: z.array(z.string()),
  so: z.string().optional(),
  isPaid: z.boolean().optional(),
  planId: z.string().optional(),
  planAmount: z.number().optional(),
  feeId: z.string().optional(),
  feeAmount: z.number().optional(),
});

export const carQuerySchema = z.object({
  type: z.string().optional(),
  listingType: z.string().optional(),
  region: z.string().optional(),
  city: z.string().optional(),
  district: z.string().optional(),
  subcategory: z.string().optional(),
  category: z.string().optional(),
});
