import { z } from "zod";

export const createFarmequipmentSchema = z.object({
  userId: z.string().optional(),
  name: z.string().optional(),
  title: z.string().min(1, "Title is required"),
  description: z.string().min(1, "Description is required"),
  price: z.coerce.number().positive("Price must be positive"),
  so: z.string().optional(),
  mainCategory: z.string().optional(),
  category: z.array(z.string()).optional(),
  subcategory: z.array(z.string()).optional(),
  region: z.string().min(1, "Region is required"),
  city: z.string().min(1, "City is required"),
  brand: z.string().optional(),
  make: z.string().optional(),
  farmequipmentModel: z.string().optional(),
  equipmentType: z.string().optional(),
  type: z.string().optional(),
  condition: z.string().optional(),
  enginePower: z.string().optional(),
  fuelType: z.string().optional(),
  year: z.union([z.number(), z.string()]).optional(),
  hours: z.union([z.number(), z.string()]).optional(),
  hoursUsed: z.union([z.number(), z.string()]).optional(),
  attachmentsIncluded: z.union([z.boolean(), z.string()]).optional(),
  images: z.array(z.string()).optional(),
  isPaid: z.boolean().optional(),
  planId: z.string().optional(),
  planAmount: z.coerce.number().optional(),
  feeId: z.string().optional(),
  feeAmount: z.coerce.number().optional(),
});

export const updateFarmequipmentSchema = createFarmequipmentSchema.partial();
