import { z } from "zod";
import * as s from "../core/utils/sanitize.ts";

export const createMotorcycleSchema = z.object({
  userId: z.string().min(1).max(128),
  title: s.title,
  description: s.description,
  price: z.coerce.number().min(0).max(s.LIMITS.PRICE_MAX),
  mainCategory: s.shortStr("Category"),
  category: z.array(s.shortStr()).max(5),
  subcategory: z.array(s.shortStr()).max(5),
  name: s.optShortStr(),
  brand: s.optShortStr(),
  make: s.optShortStr(),
  model: s.optShortStr(),
  year: z.union([z.number().int().min(1900).max(2100), z.string().max(10)]).optional(),
  mileage: z.union([z.number().min(0).max(10_000_000), z.string().max(20)]).optional(),
  engineCc: s.optShortStr(),
  transmission: s.optShortStr(),
  gearbox: s.optShortStr(),
  fuelType: s.optShortStr(),
  color: s.optShortStr(),
  condition: s.optShortStr(),
  region: s.shortStr("Region"),
  city: s.shortStr("City"),
  images: s.images,
  isPaid: z.boolean().optional(),
  planId: z.string().max(128).optional(),
  planAmount: z.coerce.number().min(0).max(s.LIMITS.PRICE_MAX).optional(),
  feeId: z.string().max(128).optional(),
  feeAmount: z.coerce.number().min(0).max(s.LIMITS.PRICE_MAX).optional(),
});
