import { z } from "zod";

export const createMotorcycleSchema = z.object({
  userId: z.string().min(1),
  name: z.string().optional(),
  so: z.string().optional(),
  title: z.string().min(1),
  description: z.string().min(1),
  price: z.coerce.number(),
  mainCategory: z.string().min(1),
  category: z.array(z.string()),
  subcategory: z.array(z.string()),
  brand: z.string().optional(),
  make: z.string().optional(),
  model: z.string().optional(),
  year: z.union([z.number(), z.string()]).optional(),
  mileage: z.union([z.number(), z.string()]).optional(),
  engineCc: z.string().optional(),
  transmission: z.string().optional(),
  gearbox: z.string().optional(),
  fuelType: z.string().optional(),
  color: z.string().optional(),
  condition: z.string().optional(),
  region: z.string().min(1),
  city: z.string().min(1),
  images: z.array(z.string()),
  isPaid: z.boolean().optional(),
  planId: z.string().optional(),
  planAmount: z.coerce.number().optional(),
  feeId: z.string().optional(),
  feeAmount: z.coerce.number().optional(),
});
