export const faq = {
  root:       "max-w-3xl mx-auto px-4 py-10",
  title:      "text-2xl font-black text-gray-900 mb-2",
  subtitle:   "text-sm text-gray-400 mb-8",
  group:      "mb-6",
  groupTitle: "text-[10px] font-black text-gray-400 uppercase tracking-widest mb-3 px-1",
  card:       "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  item:       "border-b border-gray-100 last:border-0",
  question:   "flex items-center justify-between gap-3 px-5 py-4 cursor-pointer font-semibold text-gray-900 text-sm hover:bg-gray-50 transition-colors select-none",
  chevron:    "text-gray-400 flex-shrink-0 transition-transform",
  chevronOpen:"text-blue-600 rotate-180",
  answer:     "px-5 pb-5 text-sm text-gray-500 leading-relaxed",
  searchWrap: "relative mb-6",
  searchIcon: "absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 text-sm",
  searchInput:"w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 bg-white",
} as const;
