export const faq = {
  root:        "faq-root",
  title:       "faq-title",
  subtitle:    "faq-subtitle",
  group:       "faq-group",
  groupTitle:  "faq-group-title",
  card:        "faq-card",
  item:        "faq-item",
  question:    "faq-question",
  chevron:     "faq-chevron",
  chevronOpen: "faq-chevron-open",
  answer:      "faq-answer",
  searchWrap:  "faq-search-wrap",
  searchIcon:  "faq-search-icon",
  searchInput: "faq-search-input",
} as const;
