export const support = {
  root:        "support-root",
  inner:       "support-inner",
  header:      "support-header",
  title:       "support-title",
  subtitle:    "support-subtitle",
  searchWrap:  "support-search-wrap",
  searchIcon:  "support-search-icon",
  searchInput: "support-search-input",
  topicGrid:   "support-topic-grid",
  topicCard:   "support-topic-card",
  topicIcon:   "support-topic-icon",
  topicTitle:  "support-topic-title",
  topicSub:    "support-topic-sub",
  faqCard:     "support-faq-card",
  faqHead:     "support-faq-head",
  faqTitle:    "support-faq-title",
  faqItem:     "support-faq-item",
  faqQ:        "support-faq-q",
  faqA:        "support-faq-a",
  contact:     "support-contact",
  contactIcon: "support-contact-icon",
  contactTitle:"support-contact-title",
  contactSub:  "support-contact-sub",
  alertInfo:   "support-alert-info",
  alertWarn:   "support-alert-warn",
  alertDanger: "support-alert-danger",
  alertOk:     "support-alert-ok",
} as const;
