export const support = {
  root:       "min-h-screen bg-gray-50 px-4 py-10",
  inner:      "max-w-3xl mx-auto space-y-6",
  header:     "text-center mb-10",
  title:      "text-3xl font-black text-gray-900 mb-2",
  subtitle:   "text-sm text-gray-400",
  searchWrap: "relative max-w-xl mx-auto",
  searchIcon: "absolute left-4 top-1/2 -translate-y-1/2 text-gray-400",
  searchInput:"w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 bg-white",
  topicGrid:  "grid grid-cols-2 sm:grid-cols-3 gap-4",
  topicCard:  "bg-white rounded-2xl border border-gray-200 shadow-sm p-5 hover:shadow-md hover:border-blue-200 transition-all cursor-pointer",
  topicIcon:  "w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 text-xl mb-3",
  topicTitle: "font-bold text-gray-900 text-sm",
  topicSub:   "text-xs text-gray-400 mt-0.5",
  faqCard:    "bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden",
  faqHead:    "px-5 py-4 border-b border-gray-100 bg-gray-50",
  faqTitle:   "font-bold text-gray-900 text-sm",
  faqItem:    "border-b border-gray-100 last:border-0",
  faqQ:       "flex items-center justify-between gap-3 px-5 py-4 cursor-pointer font-semibold text-gray-900 text-sm hover:bg-gray-50 transition-colors",
  faqA:       "px-5 pb-4 text-sm text-gray-500 leading-relaxed",
  contactCard:"bg-white rounded-2xl border border-gray-200 shadow-sm p-6 flex items-start gap-4",
  contactIcon:"w-11 h-11 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 text-lg flex-shrink-0",
  contactTitle:"font-bold text-gray-900 text-sm mb-1",
  contactSub: "text-xs text-gray-400 mb-3",
  ticketForm: "space-y-4",
  alertInfo:  "flex items-start gap-3 px-4 py-3.5 rounded-xl bg-blue-50 border border-blue-100 text-blue-800 text-sm",
  alertWarn:  "flex items-start gap-3 px-4 py-3.5 rounded-xl bg-yellow-50 border border-yellow-100 text-yellow-800 text-sm",
  alertDanger:"flex items-start gap-3 px-4 py-3.5 rounded-xl bg-red-50 border border-red-100 text-red-800 text-sm",
  alertOk:    "flex items-start gap-3 px-4 py-3.5 rounded-xl bg-green-50 border border-green-100 text-green-800 text-sm",
} as const;
