export const tickets = {
  root:         "min-h-screen bg-gray-50/60 py-6 px-4",
  inner:        "max-w-4xl mx-auto",
  list:         "space-y-3",
  card:         "bg-white rounded-2xl border border-gray-200 shadow-sm p-5",
  cardHead:     "flex items-start justify-between gap-3",
  cardId:       "text-[10px] font-black text-gray-400 uppercase tracking-widest",
  cardTitle:    "font-bold text-gray-900 text-sm mt-0.5",
  cardUser:     "flex items-center gap-2 mt-2",
  cardAvatar:   "w-6 h-6 rounded-full bg-blue-100 text-blue-700 font-bold text-[10px] flex items-center justify-center",
  cardUserName: "text-xs font-semibold text-gray-700",
  cardPreview:  "text-xs text-gray-400 mt-2 leading-relaxed line-clamp-2",
  cardFoot:     "flex items-center justify-between mt-3 pt-3 border-t border-gray-50",
  cardTime:     "text-[10px] text-gray-400",
  cardActions:  "flex items-center gap-1",
  statusOpen:   "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 text-xs font-semibold",
  statusClosed: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-semibold",
  statusUrgent: "inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 text-red-700 text-xs font-semibold",
  statusWaiting:"inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs font-semibold",
  thread:       "space-y-4 mt-5",
  threadMsg:    "flex items-start gap-3",
  threadBubble: "flex-1 bg-gray-50 rounded-2xl rounded-tl-sm px-4 py-3",
  threadName:   "text-xs font-bold text-gray-900",
  threadTime:   "text-[10px] text-gray-400 ml-2",
  threadText:   "text-sm text-gray-700 mt-1 leading-relaxed",
  replyWrap:    "mt-4 bg-white rounded-2xl border border-gray-200 shadow-sm p-4",
  replyInput:   "w-full outline-none text-sm text-gray-900 resize-none placeholder:text-gray-400",
  replyFoot:    "flex items-center justify-end gap-2 mt-3",
} as const;
