export const tickets = {
  root:         "ticket-root",
  inner:        "ticket-inner",
  list:         "ticket-list",
  card:         "ticket-card",
  cardHead:     "ticket-card-head",
  cardId:       "ticket-card-id",
  cardTitle:    "ticket-card-title",
  cardUser:     "ticket-card-user",
  cardAvatar:   "ticket-card-avatar",
  cardName:     "ticket-card-name",
  cardPreview:  "ticket-card-preview",
  cardFoot:     "ticket-card-foot",
  cardTime:     "ticket-card-time",
  statusOpen:   "ticket-status-open",
  statusClosed: "ticket-status-closed",
  statusUrgent: "ticket-status-urgent",
  statusWait:   "ticket-status-wait",
  thread:       "ticket-thread",
  threadMsg:    "ticket-thread-msg",
  threadBubble: "ticket-thread-bubble",
  threadName:   "ticket-thread-name",
  threadTime:   "ticket-thread-time",
  threadText:   "ticket-thread-text",
  replyWrap:    "ticket-reply-wrap",
  replyInput:   "ticket-reply-input",
  replyFoot:    "ticket-reply-foot",
} as const;
