name: Production Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Infra
        run: |
          aws cloudformation deploy \
            --template-file production/production.yaml \
            --stack-name karaadi-production \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

      - name: Build & Deploy Backend
        working-directory: backend
        run: |
          npm install
          npx prisma generate
          zip -r ../deploy.zip . -x "node_modules/*"
          aws s3 cp ../deploy.zip s3://karaadi-deploy-bucket/v-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version --application-name karaadi-backend --version-label ${{ github.sha }} --source-bundle S3Bucket="karaadi-deploy-bucket",S3Key="v-${{ github.sha }}.zip"
          aws elasticbeanstalk update-environment --environment-name karaadi-prod --version-label ${{ github.sha }}

      - name: Sync Frontend
        run: aws amplify start-job --app-id ${{ secrets.AWS_AMPLIFY_APP_ID }} --branch-name main --job-type RELEASE
